input-output-hk/mithril

README.md

This PR fixes typo and badge links in README.md
Relates to #454

Fix typo and badge links in README.md

---

mithril-test-lab/mithril-devnet/devnet-mkfiles.sh

This PR adds a `:z` option on volumes in the `devnet` `docker-compose.yaml` generated file so that we avoid `Permission denied` errors
Relates with #459

Fix attempt 'Permission Denied' in devnet

---

Cargo.lock
demo/protocol-demo/src/demonstrator.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-core/benches/size_benches.rs
mithril-core/benches/stm.rs
mithril-core/examples/key_registration.rs
mithril-core/src/error.rs
mithril-core/src/key_reg.rs
mithril-core/src/lib.rs
mithril-core/src/stm.rs
mithril-core/tests/integration.rs
mithril-signer/Cargo.toml
mithril-signer/src/single_signer.rs

This PR attempts to fix some panics that occur when a `StmInitializer` creates a `StmSigner` if the initializer is not registered.
In that case, the `new_signer` will return an error instead.

Avoid panics in 'StmInitializer'

---

mithril-aggregator/src/lib.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/error.rs
mithril-aggregator/src/store/certificate_store.rs
mithril-aggregator/src/store/error.rs
mithril-aggregator/src/store/mod.rs
mithril-aggregator/src/store/pending_certificate_store.rs
mithril-aggregator/src/store/protocol_parameters_store.rs
mithril-aggregator/src/store/single_signature_store.rs
mithril-aggregator/src/store/verification_key_store.rs
mithril-common/src/store/error.rs
mithril-common/src/store/mod.rs
mithril-common/src/store/stake_store.rs

Each stores tended to use their own specific error type, all of them
having only one value: AdapterError. This is now done within one type in
mithril-common::StoreError.

use StoreError in stores

---

docs/root/manual/getting-started/bootstrap-cardano-node.md
docs/root/manual/getting-started/run-signer-node.md
mithril-aggregator/config/preview.json
mithril-aggregator/src/entities.rs
mithril-aggregator/src/runtime/runner.rs
mithril-client/config/preview.json
mithril-client/src/main.rs
mithril-common/src/entities/cardano_network.rs
mithril-infra/Dockerfile.cardano
mithril-infra/aggregator.tf
mithril-infra/docker-compose.yaml
mithril-infra/scripts/configure-testnet.sh
mithril-signer/config/preview.json
mithril-signer/src/entities.rs

This PR upgrades the Aggregator hosted on GCP cloud so that it uses the `preview` Cardano network instead of the legacy `testnet`:
After merge, manually duplicate stores data so that we don't need to wait 2 epochs before signing
Relates to #457

Move GCP Aggregator to 'preview' network

---

docs/root/manual/getting-started/bootstrap-cardano-node.md
docs/root/manual/getting-started/run-mithril-devnet.md
docs/root/manual/getting-started/run-signer-node.md
docs/root/mithril/mithril-network/aggregator.md
mithril-common/src/entities/cardano_network.rs
mithril-test-lab/mithril-devnet/README.md

This PR:
* Fixes few typos in the documentation 
* Adds a test on the `code to Cardano Network` conversion

Fix typos in documentation

---

CONTRIBUTING.md
README.md
demo/protocol-demo/README.md
docs/blog/2022-09-07-genesis-certificate-feature.md
docs/docusaurus.config.js
docs/package.json
docs/root/manual/developer-docs/nodes/mithril-aggregator.md
docs/root/manual/developer-docs/nodes/mithril-client.md
docs/root/manual/developer-docs/nodes/mithril-signer.md
docs/root/manual/getting-started/bootstrap-cardano-node.md
docs/root/manual/getting-started/run-mithril-devnet.md
docs/root/manual/getting-started/run-signer-node.md
docs/root/manual/welcome.md
docs/root/mithril/mithril-protocol/simulation.md
docs/yarn.lock
mithril-aggregator/README.md
mithril-client/README.md
mithril-explorer/yarn.lock
mithril-signer/README.md
mithril-test-lab/mithril-end-to-end/README.md

This PR addresses some issue with the documentation:
* Add missing `Pre-requisites` information on tutorial in `Getting Started` section of website
* Update mention to Rust version needed: use `latest stable version` instead of specific version
* Add explanation of new `--json` output mode option in the Client

Enhance documentation pre-requisites

---

mithril-aggregator/src/configuration.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/src/http_server/routes/certificate_routes.rs
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/snapshot_routes.rs
mithril-aggregator/src/multi_signer.rs
mithril-client/src/aggregator.rs
mithril-client/src/main.rs
mithril-client/src/runtime.rs

- Remove all Wrapper type that only wrap on one level, usually behind an `Arc` or a `Box` (meaning every wrapper except the one over `MultiSigner`)
- Simplify Client dependencies by making most of them mandatory.
- Fix some typos in the Client.
If ok we should wait for #438 merge before merging this PR.

Clean wrappers

---

mithril-aggregator/src/http_server/routes/certificate_routes.rs
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/http_server/routes/snapshot_routes.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/entities/beacon.rs
mithril-signer/src/runtime/state_machine.rs

With this PR logs from Signers & Aggregator state machines will use the same semantic.
I've a question: should we pass to info level all logs from the `cycle` methods of both state machines ? I think it would make sense to show what's happening without flooding the logs too much, else on info only level most logs would only be `new cycle [...] current_state: [...]`.

Align signer & aggregator state machines logs

---

mithril-infra/docker-compose.yaml
mithril-infra/genesis.md

This PR fixes the `Genesis` part of the GCP infra:
* Remove unusable `mithril-aggregator-genesis` node 
* Use `mithril-aggregator` node to bootstrap genesis certificate instead
:warning: The commands to run when bootstrapping are:
1. Open a bash terminal on the `mithril-aggregator` node with `docker-compose exec mithril-aggregator bash`
2. Run the following command once connected `/app/bin/mithril-aggregator -vvv genesis bootstrap`
Relates to #364

Update Genesis GCP infra

---

.github/workflows/ci.yml
Cargo.lock
demo/protocol-demo/Makefile
mithril-aggregator/Cargo.toml
mithril-aggregator/Makefile
mithril-client/Makefile
mithril-common/Cargo.toml
mithril-common/Makefile
mithril-common/src/store/adapter/sqlite_adapter.rs
mithril-core/Makefile
mithril-signer/Makefile
mithril-signer/src/runtime/signer_services.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/Makefile

- Upgrade to latest version dependencies of all cargo projects
- Update the workspace `Cargo.lock`
- CI:
- :warning: if clippy raise a warning the pipeline will now fail
- add `--all-targets` to the clippy check so it also check the tests
- avoid multiple clippy warning for the same problem on shared dependencies by using the `--no-deps` parameter
- Makefiles: Enhance the `make check` target:
- add `cargo fmt --check` to check code formating
- add `--all-targets` to the clippy check so it also check the tests

Upgrade dependencies & enhance makefiles

---

mithril-core/src/stm.rs

This PR updates `StmSig` verification steps order and checks in `mithril-core`:
* First that the signature is valid (triggers `StmSignatureError::SingleSignatureInvalid` if not)
* Before checking that the lottery was won (triggers `StmSignatureError::LotteryLost` if not)
This will help users of the library get more understandable message when the message signed on the Signer and the Aggregator are not the same: `A provided signature is invalid` instead of `Lottery for this epoch was lost.`
- Branch
- PR

Update `StmSig` verification steps order

---

docs/blog/2022-09-07-genesis-certificate-feature.md
docs/blog/2022-09-12-certificate-signers-list.md
mithril-aggregator/src/multi_signer.rs
mithril-infra/docker-compose.yaml

* Update the `Certificate` creation so that only Signers with valid `Single Signatures` are included in its `signers` field 
* Reduce the runtime interval of the GCP hosted Signers from `60s` to `240s`
- Branch
- PR
Closes #495

Implement filtered Signers in Certificate

---

docs/root/manual/getting-started/bootstrap-cardano-node.md

This PR includes the missing mention of the `GENESIS_VERIFICATION_KEY` variable to use when restoring a node in the [`Bootstrap a Cardano Node`](https://mithril.network/doc/manual/getting-started/bootstrap-cardano-node) guide of the documentation website.

Missing Genesis Verification Key in documentation

---

docs/blog/2022-09-13-stake-distribution-retrieval.md
mithril-common/src/chain_observer/cli_observer.rs
mithril-test-lab/mithril-devnet/devnet-mkfiles.sh
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs

This PR includes a fix on the Stake Distribution retrieval. It makes use `cardano-cli query stake-snapshot` to retrieve an accurate stake distribution for each available stake pool. This allows to retrieve the `Stake Distribution` at the correct `Epoch` (previous)
- Branch
- PR
Once this PR is merged, the SPO will need to recompile their node and signing should work as expected after `2` epochs
Closes #497

Fix Stake Distribution retrieval

---

mithril-aggregator/src/bin/mithril-aggregator-migrate.rs

This PR includes a fix of the Aggregator store migrator: the path of the source directory for certificates was incorrect, which made the migration import `0` certificates without failing.
Relates to #475

Fix Aggregator store migrator

---

mithril-infra/docker-compose.yaml

This PR adds the `Store Retention Limit` to Signers and Aggregator containers running on GCP.
This will activate the `Store Pruning` features on their respective stores.
Relates to #504

Activate store pruning on GCP infra

---

mithril-aggregator/Dockerfile
mithril-client/Dockerfile
mithril-signer/Dockerfile

This PR includes a fix on the `Dockerfiles` used by the `devnet` so that they can handle multiple bins in the crates along with build cache trick (for fast build)
Relates to #475

Fix devnet Dockerfiles

---

.github/workflows/ci.yml
docs/root/manual/developer-docs/nodes/mithril-aggregator.md
docs/root/manual/developer-docs/nodes/mithril-signer.md
docs/root/manual/getting-started/run-mithril-devnet.md
docs/root/manual/getting-started/run-signer-node.md
mithril-aggregator/README.md
mithril-common/src/store/adapter/sqlite_adapter.rs
mithril-signer/README.md

Applies to your base code, this patch will:
- remove SQL explicit transaction by using `DELETE … RETURNING` SQL statements
- apply a wait & retry strategy to deal with database locking mechanism
- Branch
- PR
For now, the wait & retry strategy has only been applied on READ statements (that wait for data). If new lock problems arise, it should be considered to also wait & retry for WRITE statements.
Closes #517

fix SQLite deadlocks

---

Cargo.lock
mithril-aggregator/Dockerfile.ci
mithril-aggregator/src/store/protocol_parameters_store.rs
mithril-client/Dockerfile.ci
mithril-client/src/aggregator.rs
mithril-common/src/entities/certificate.rs
mithril-signer/Dockerfile.ci
mithril-signer/src/protocol_initializer_store.rs

This PR includes to avoid getting `libssl` shared libraries errors that is blocking the GCP nodes following merge of #517:
`error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory`
Replaces `FROM ubuntu:latest` instead of `FROM rust:latest`
This is not the best fix as we could probably use a "slimer" image.
We will address that issue more in depth in #318 
Relates to #517

Fix Dockerfile CI images

---

.github/workflows/ci.yml
docs/root/manual/developer-docs/nodes/mithril-aggregator.md
docs/root/manual/developer-docs/nodes/mithril-client.md
docs/root/manual/developer-docs/nodes/mithril-signer.md
docs/root/manual/developer-docs/references.md
docs/root/manual/getting-started/bootstrap-cardano-node.md
docs/root/manual/getting-started/run-signer-node.md
mithril-aggregator/README.md
mithril-client/README.md
mithril-signer/README.md

This PR includes documentation enhancements about the usage of the `Mithril networks` and attempts to avoid confusion between `testnet` (the legacy network) and `test networks` (aka `preview` and `preprod`). Also the documentation now uses a generic `**YOUR_TEST_NETWORK**`.
Closes #527

Enhance Mithril networks documentation

---

mithril-infra/docker-compose.yaml

This PR includes a modification of `mithril-signer-1` poolId to avoid spoofing a certifiied SPO's poolId.

Fix mithril infra configuration

---

Cargo.lock
demo/protocol-demo/Cargo.toml
mithril-aggregator/Cargo.toml
mithril-aggregator/src/command_args.rs
mithril-client/Cargo.toml
mithril-client/src/main.rs
mithril-signer/Cargo.toml
mithril-signer/src/main.rs

This PR adds the `-V|--version` to CLI tools. 
It also adds a software version in the API headers.
- Branch
- PR
Closes #541

Add version information

---

Cargo.lock

* Updated linting done by running `cargo sort -w` on `cargo.toml` files
* Updated workspace dependencies by running `cargo update`

Cargo update sort and dependencies

---

docs/yarn.lock
mithril-explorer/package.json
mithril-explorer/yarn.lock

Run 'make upgrade' to fix 'minimatch' vulnerability following security alert (https://github.com/input-output-hk/mithril/security/dependabot/20) on `docs` and `mithil-explorer`

Update docs dependencies

---

mithril-common/src/store/adapter/mod.rs

This PR removes a reference to `JsonFileStoreAdapter` in the code documentation.

fix documentation

---

mithril-aggregator/src/multi_signer.rs
mithril-common/src/crypto_helper/cardano/key_certification.rs
mithril-common/src/crypto_helper/cardano/opcert.rs
mithril-signer/src/runtime/runner.rs
openapi.yaml

This PR includes a fix that updates KES keys to the current period: 
`kes_period = current_kes_period - start_kes_period`
We still verify the full range of KES period for backward compatibility and until the `preview` network is respin
- Branch
- PR
In order to use the correct KES period, we need to manually evolve the key (as it is done in memory on the Cardano node
- @iquerejeta 
- @jpraynaud 
Relates to #548

Fix KES key update

---

docs/root/manual/getting-started/run-mithril-devnet.md

This PR includes adds the video demonstration on the [Run a Private Mithril network](https://mithril.network/doc/manual/getting-started/run-mithril-devnet) guide.
Closes #526

Add 'devnet' video demo

---

mithril-aggregator/src/configuration.rs
mithril-aggregator/src/snapshot_uploaders/remote_snapshot_uploader.rs

This PR includes a fix to use the 'snapshot_bucket_name' instead of 'cardano-testnet' in snapshot url builder.
- Branch
- PR
Relates to #542

Fix Aggregator snapshot url

---

.github/workflows/actions/build-upload-mithril-artifact/action.yml
.github/workflows/scripts/edit-cargo-toml-version.py
.github/workflows/scripts/package-distribution.py

This PR includes add a new CI step right before the `cargo build` that search all `Cargo.toml` files in the repository to edit their semver version to add the current commit short sha in the version label.
This means that the binaries built by the CI will report the commit sha when using `-V, --version`:
```bash
$ ./mithril-signer -V
mithril-signer 0.1.0-0757aef
```
- Branch
- PR
This PR also enhance the python package script: better help, better naming, add a main function.
Relates to #500 and #543

Add commit hash to toml before build in CI

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

This PR fix the names used to download previously uploaded packages in CI workflows
- Branch
- PR
Relates to #500, #543 and #579

Fix package names in CI workflows

---

.github/workflows/pre-release.yml
.github/workflows/release.yml

This PR includes a fix in the Pre-Release and Release CD workflows for tagging Docker images
- Branch
- PR
Relates to #500

Fix docker image prefix Pre-Release/Release

---

.github/workflows/ci.yml
Cargo.lock
demo/protocol-demo/Cargo.toml
demo/protocol-demo/src/demonstrator.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/tests/test_extensions/dependency.rs
mithril-client/src/aggregator.rs
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/crypto_helper/cardano/opcert.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/digesters/cardano_immutable_digester.rs
mithril-common/src/digesters/immutable_file.rs
mithril-common/src/entities/certificate_metadata.rs
mithril-core/Cargo.toml
mithril-core/src/error.rs
mithril-core/src/merkle_tree.rs
mithril-core/src/multi_sig.rs
mithril-signer/src/runtime/signer_services.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/main.rs
mithril-test-lab/mithril-end-to-end/src/utils/file_utils.rs
mithril-test-lab/mithril-end-to-end/src/utils/mithril_command.rs

This PR updates rust dependencies & the global cargo lock.
It also contains a CI improvement: Avoid recompilation when macking Debian packages using `cargo deb`
- Branch
- PR

Update rust dependencies

---

.github/workflows/docs.yml
docs/Makefile
mithril-explorer/Makefile
mithril-explorer/__tests__/AggregatorSetter.test.js
mithril-explorer/__tests__/helpers.js
mithril-explorer/__tests__/store.test.js
mithril-explorer/components/AggregatorSetter/index.js
mithril-explorer/jest.config.js
mithril-explorer/package.json
mithril-explorer/store/settingsSlice.js
mithril-explorer/store/store.js
mithril-explorer/yarn.lock

This PR fix a bug when the explorer reload its state: if there's both a aggregator in the url and data in the local storage the aggregator in the url would erase the selectedAggregator and the availableAggregators values from the local storage, meaning that all custom aggregators previously saved were lost.
- Branch
- PR
This PR add jest unit tests to the explorer :man_dancing: 
Relates to #576, bug introduced with #590

Fix explorer state reload

---

docs/root/manual/getting-started/run-signer-node.md
mithril-aggregator/Dockerfile.ci
mithril-infra/assets/docker/Dockerfile.cardano
mithril-infra/assets/docker/docker-compose-aggregator.yaml
mithril-infra/assets/docker/docker-compose-signer-unverified.yaml
mithril-signer/Dockerfile.ci

This PR includes an update of the docker images used in the CI and in the infrastructure of the deployed environments to use cardano-node / cardano-cli in version `1.35.4`. In the next days, the `preview` network will not be able to run on a previous version.
- Branch
- PR
Closes #594

Upgrade to Cardano 1.35.4

---

mithril-aggregator/src/http_server/mod.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-client/src/aggregator.rs
mithril-common/src/lib.rs
mithril-signer/src/certificate_handler.rs
openapi.yaml

This patch adds a new HTTP response header that advertise the version of the Mithril Protocol supported by the server.
- Branch
- PR

add API version in HTTP headers

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
mithril-infra/assets/docker/docker-compose-signer-unverified-light.yaml
mithril-infra/assets/docker/docker-compose-signer-unverified.yaml
mithril-infra/assets/startup-vm.sh
mithril-infra/main.vm.tf
mithril-infra/mithril.signer.tf
mithril-infra/variables.tf

This PR includes new features on the Mithril networks infrastructure:
* Add a retention delay for the VM compute disk snasphots
* Enhance the customization of VM boot disk
* Allow to restore a VM from a snapshot 
* Add a light unverified signer type (working on the Aggregator Cardano node instead of its own)
- Branch
- PR
:warning: this PR includes some breaking changes that could lead to data loss on the networks!
The modification of the boot disk involves a re-deployment via terraform.
In order to not lose data (to do on each Mithril network, i.e. `testing-preview`, `pre-release-preview` and `preprod-preview`:
* Stop all the docker containers
* Make manual snapshot of the data with `gcloud` command
* Apply `terraform` new configuration
* Restore the saved data in the `/home/curry/data` …

Enhance Mithril networks infra

---

mithril-signer/src/runtime/runner.rs

This PR includes a fix to avoid double computation of the Stake Distribution while registering to the Aggregator.
- Branch
- PR
@jpraynaud 
@Alenar 
Closes #596

Fix Signer registration

---

mithril-common/src/database/db_version.rs

Stop quitting the application when a version downgrade is detected. The problem with SemVer comparisons is that we added build information as suffix which do not compare well. This leads to application to quit event when no downgrade was made.
- Branch
- PR
This is a temporary fix, 2 other PR are also coming to handle this nicely.
Relates to #600 and Closes #603

stop quitting when version downgrade

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/pre-release.yml

This PR includes an updated Pre-release workflow that appends the version table of the crates inside a Release.
Also it adds an automatic cancellation of CI and docs workflows currently running when a newer version is triggered.
- Branch
- PR
@Alenar 
@jpraynaud 
Closes #599

Produce versions table in Release description

---

docs/root/manual/getting-started/bootstrap-cardano-node.md

This PR adds the video of the Daedalus benchmark with/without Mithril that was run on `mainnet`
- Branch
- PR
Closes #606

Add Daedalus/Mithril benchmark video

---

mithril-common/src/crypto_helper/cardano/key_certification.rs

This PR includes a restriction of the KES period range verification to `[max(0,kes_period-1), min(64,kes_period+1)]`.
- Branch
- PR
Closes #548

Fix KES period verification

---

docs/root/manual/getting-started/run-signer-node.md
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/cardano/key_certification.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-signer/tests/state_machine.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/mithril/infrastructure.rs

This PR deprecates the uncertified signer registration where only the Pool Id is provided:
* Add a `allow_uncertified_signer_registration` feature to `mithril-common` and `mithril-end-to-end`
* When this feature will be deactivated only the signer registration with KES Secret Key and Operational Certificate will be allowed
* Update the documentation to reflect that:
* Registration from Pool Id is `Deprecated`
* Registration with KES Secret Key and Operational Certificate is `Stable`
- Branch
- PR
Closes #585

Deprecate uncertified signer registration

---

.github/workflows/ci.yml
.github/workflows/docs.yml

This PR switch the event trigger used for the `ci` and `docs` workflows to `pull_request` (from `push`).
Using this trigger add the ability to run those workflows on PR from forks (if we approve them, see: [Approving workflow runs from public forks](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)).
- Branch
- PR
Fix #597

Doc & Build CI: Switch to pull_request trigger

---

.github/workflows/ci.yml

This PR fix the retrieval of the docker image id in the `deploy-testing` job in the CI workflow.
- Branch
- PR
Relates to #597, fix regression introduced by #613

Fix deploy-testing docker image id retrieval

---

mithril-common/src/database/db_version.rs
mithril-common/src/sqlite/entity.rs
mithril-common/src/sqlite/projection.rs
mithril-common/src/sqlite/provider.rs

This PR includes a code rework that remove the need of creating dedicated `Projection` structures that work always the same way. It makes  `SqLiteEntity` to return the `Projection` that can hydrate them. This removes a good part of boilerplate to use `Provider`s.
- Branch
- PR

make SQL entities to create their projection

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml

This PR replace the "pull request closed" trigger with a push trigger on the `main` or `hotfix*` branches. It also disable running the `deploy-testing` job when the triggering pull request comes from a fork (since [they don't have all the secrets needed to run it](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflows-in-forked-repositories)).
This means that only merge coming from this repository branches will trigger a deployment and that only those merge can be tagged for a version (else the `pre-release` workflow will fail since no artifacts would have been built).
This is ok since we need anyway to do a commit to update the version and/or the documentation each time we do a new distribution release.
- Branch
- PR
Hopefully having a push trigger on …

Deploy using push trigger

---

.github/workflows/actions/build-upload-mithril-artifact/action.yml
.github/workflows/actions/toolchain-and-cache/action.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/test-client.yml

This PR includes the "Mithril Client multi-platform test" workflow that can be manually triggered to test that a `mithril-client` can list, download and restore on each supported environment (linux, macOs, windows).
- Branch
- PR
This PR also fix partially #550 by replacing all `action-rs` actions with either an up to date equivalent or direct command line calls.
Closes #601

Add test-client workflow

---

.github/workflows/scripts/sign-distribution.sh

This PR includes a fix in the script that signs the distribution assets that prevented the CI to complete successfully.
- Branch
- PR
Relates to #587

Fix sign distribution CI

---

.github/workflows/scripts/sign-distribution.sh

This PR includes a fix in the script that signs the distribution assets that prevented the CI to complete successfully (second attempt).
- Branch
- PR
Relates to #587

Fix sign distribution CI v2

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml
.github/workflows/scripts/verify-distribution.sh
docs/blog/2022-12-05-release-process/index.md
mithril-infra/README.md

This PR includes a fix of the computation of the download links provided in the verification procedure in the release notes for `CHECKSUM` and `GPG Public Key`
- Branch
- PR
Relates to #587

Fix verify signature links in release notes

---

mithril-infra/mithril.signer.tf

This PR includes a fix to the computation of the verified signer attached Cardano relay node which was always using `preview` configuration in the Mithril infra. This issue prevented the synchronization of the chain on other networks.
- Branch
- PR

Fix Cardano relay node topology configuration

---

mithril-infra/assets/tools/pool/query-stake-pool.sh

This PR includes a query to retrieve KES period info for test SPOs. This will help us know when we need to renew operational certificates. 
- Branch
- PR

Add query KES period info for test SPOs

---

Cargo.lock
mithril-aggregator/src/multi_signer.rs
mithril-signer/src/single_signer.rs
mithril-stm/Cargo.toml
mithril-stm/README.md
mithril-stm/src/merkle_tree.rs
mithril-stm/src/stm.rs
mithril-stm/tests/integration.rs

This PR removes the verification key and the stake from the signature. These values are no longer required, as individual signatures no longer contain the merkle paths (it is now responsibility of the aggregator to include these values in the certificate). This required some changes in the multi_signer and single_signer, as these folders were verifying single signatures. 
Now, in order to verify aggregate signatures, they include not only the individual signatures but also the corresponding `RegParty`, to be able to verify the batched membership proof (batched merkle path).
- Branch
- PR
This PR closes #619 .

Simplify signature

---

mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-common/src/entities/epoch_settings.rs
mithril-common/src/fake_data.rs
mithril-common/src/lib.rs
mithril-explorer/components/EpochSettings/index.js
mithril-signer/src/runtime/state_machine.rs
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
mithril-test-lab/mithril-end-to-end/src/mithril/aggregator.rs
mithril-test-lab/mithril-end-to-end/src/mithril/infrastructure.rs
mithril-test-lab/mithril-end-to-end/src/utils/mithril_command.rs
openapi.yaml

This PR includes a fix to the protocol parameters transition that was preventing the Mithril network from creating certificates:
- Update the end to end test so that it fails when a protocol parameters transition is happening and it succeeds otherwise
- Fix the problem by using the protocol parameters from the next epoch (instead of the current epoch) when signer registers
- Update the `OpenAPI` specification and upgrade its version
- Update the `MITHRIL_API_VERSION` accordingly
- Update Mithril Explorer to display next protocol parameters in `Epoch Settings` block
- Branch
- PR
Closes #627

Fix protocol parameters transition

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml

This PR includes an upgrade that moves `testing-preview` and `pre-release-preview` to higher memory instances `e2-standard-2`.
- Branch
- PR

Upgrade instances capacity infrastructure

---

mithril-aggregator/src/command_args.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/error.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-aggregator/src/signer_registerer.rs
mithril-aggregator/tests/test_extensions/dependency.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/src/crypto_helper/cardano/key_certification.rs

This PR extracts the signer registration from the multi-signer in he Aggregator and remove this responsibility from it.
- Branch
- PR
@Alenar 
@ghubertpalo 
@jpraynaud 
Closes #642

Extract signer registration from muti-signer in Aggregator

---

mithril-aggregator/src/certificate_creator.rs
mithril-aggregator/src/http_server/routes/certificate_routes.rs
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/http_server/routes/snapshot_routes.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/runner.rs
mithril-client/src/aggregator.rs
mithril-common/src/crypto_helper/cardano/codec.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/digesters/immutable_file.rs
mithril-stm/benches/size_benches.rs
mithril-stm/src/stm.rs

This PR includes a fix to remove clippy warnings that arose with the new version of Rust `1.66.0`
- Branch
- PR

Fix clippy warnings from Rust `1.66.0`

---

mithril-aggregator/src/http_server/routes/router.rs
mithril-client/src/aggregator.rs
mithril-signer/src/certificate_handler.rs
openapi.yaml

This PR adds an API version check when requesting the Aggregator. If the API version does not match, the HTTP call is rejected.
- Branch
- PR
None
Closes #633

check API version

---

.github/workflows/actions/build-upload-mithril-artifact/action.yml
.github/workflows/ci.yml
Cargo.lock
demo/protocol-demo/Cargo.toml
demo/protocol-demo/src/demonstrator.rs
demo/protocol-demo/src/main.rs
demo/protocol-demo/src/types.rs
docs/blog/2022-10-11-keys-certification-badge/index.md
docs/root/manual/developer-docs/nodes/mithril-signer.md
docs/root/manual/getting-started/run-signer-node.md
docs/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/runtime/runner.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/cardano/key_certification.rs
mithril-common/src/crypto_helper/codec.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/crypto_helper/types.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml

This PR decommissions the declarative `PoolId` signer registration mode. Once this PR is merged SPOs will be required to provide their `Operational Certificate` and `KES Secret Key` to certify that they are the owner of a `PoolId`.
- Branch
- PR
Closes #621

Decommission signer registration with declarative PoolId

---

README.md

This PR includes a fix of the badge showing the status of the CI workflow on the `README` file of the repository which was not displayed anymore and needed to be updated, as explained in https://github.com/badges/shields/issues/8671.
- Branch
- PR

Fix badge workflow CI status in `README`

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

This PR deactivates all the uncertified signers in:
* `testing-preview`
* `pre-release-preview`
* `release-preprod`
Also adds a new slot for a verified signer in `testing-preview`
- Branch
- PR
Relates to #621

Deactivate uncertified signers in networks

---

.github/workflows/actions/build-upload-mithril-artifact/action.yml
.github/workflows/ci.yml
mithril-aggregator/Dockerfile
mithril-aggregator/src/command_args.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/signer_registerer.rs
mithril-aggregator/src/tools/genesis.rs
mithril-common/src/entities/epoch.rs
mithril-signer/Dockerfile
mithril-signer/src/runtime/state_machine.rs
mithril-test-lab/mithril-devnet/devnet-log.sh
mithril-test-lab/mithril-devnet/devnet-mkfiles.sh
mithril-test-lab/mithril-devnet/devnet-query.sh
mithril-test-lab/mithril-devnet/devnet-run.sh
mithril-test-lab/mithril-devnet/devnet-stop.sh
mithril-test-lab/mithril-devnet/devnet-visualize.sh
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
mithril-test-lab/mithril-end-to-end/src/main.rs
mithril-test-lab/mithril-end-to-end/src/mithril/aggregator.rs
mithril-test-lab/mithril-end-to-end/src/mithril/signer.rs

This PR includes an upgrade of the `devnet` Cardano nodes to `1.35.4`.
It also fixes few flakiness that were identified during the testing of the upgrade, and brings some optimization like:
* Adding matrix runs of the end to end tests in order to detect early flakiness
* And better handling of timeout for the launch of the Cardano `devnet` to provide fast fail
- Branch
- PR
Relates to #523

Upgrade `devnet` to Cardano `1.35.4`

---

mithril-aggregator/Cargo.toml
mithril-aggregator/Makefile
mithril-client/Makefile
mithril-common/Cargo.toml
mithril-common/Makefile
mithril-signer/Cargo.toml
mithril-signer/Makefile
mithril-stm/Cargo.toml

This PR activates by default the `portable` feature when building the nodes (to be aligned with the CI build features)
- Branch
- PR

Fix make build portable

---

mithril-test-lab/Makefile

This PR adds a `Makefile` to `mithril-test-lab`. This will avoid receiving errors when using the 'make build' command from the root of the repository. This also applies to other arguments of the `make` command: `test check debug run clean help doc`.
- Branch
- PR

Fix `make` errors from root

---

mithril-test-lab/mithril-end-to-end/src/main.rs

This PR includes an optimization that accelerates the execution of the end to end test by reducing epoch length from `60` to `45`. This enables running the end to end test in less than `~2'30"` on an average when it used to take `~3'00"`.
- Branch
- PR

Accelerate end to end test execution

---

Makefile
mithril-test-lab/Makefile

This PR includes a better fix than the one provided in #684, and does not need to introduce a `Makefile` in the `mithril-test-lab` folder (which this PR removes)
- Branch
- PR

Fix `make` errors from root v2

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/snapshot_routes.rs
mithril-aggregator/src/message_adapters/mod.rs
mithril-aggregator/src/message_adapters/to_snasphot_message.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator.rs
mithril-client/src/lib.rs
mithril-client/src/message_adapters/from_snapshot_message.rs
mithril-client/src/message_adapters/mod.rs
mithril-common/Cargo.toml
mithril-common/src/messages/mod.rs
mithril-common/src/messages/snapshot.rs
openapi.yaml

This PR adds a `SnapshotMessage` message and adapter types.
- Branch
- PR
Closes #699

Add snapshot message and adapter

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-aggregator/src/signer_registerer.rs

This PR includes an attempt to fix the problem that SPOs encountered after having installed the 2304.0-prerelease distribution on their signer node running on the pre-release-preview network. Almost all the SPOs received error messages preventing them to contribute to the creation of the multi-signatures.
- Branch
- PR
⚠ After deploying the fix on the signer node we will need a `2` epochs delay to get signer contributing to signatures
Relates to #716

Fix signer unable to sign with `2304.0 prerelease`

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/router.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator.rs
mithril-common/Cargo.toml
mithril-common/src/lib.rs
mithril-signer/Cargo.toml
mithril-signer/src/certificate_handler.rs

This PR includes a fix to use the API enforcement. No verification is actually done without this fix. as the header sent by client and signer nodes is not the one verified by the aggregator.
- Branch
- PR

Fix API version sent in wrong header

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/command_args.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/tests/test_extensions/dependency.rs
mithril-common/Cargo.toml
mithril-common/src/era/era_checker.rs
mithril-common/src/era/mod.rs
mithril-common/src/era/supported_era.rs
mithril-common/src/lib.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR includes an implementation of an era checker that helps creating switch for ear based code execution.
It also introduces a Support Era type that is an enum with all the possible variants of the eras.
- Branch
- PR
@Alenar 
@ghubertpalo 
@jpraynaud 
Closes #708

Create Era Checker

---

mithril-stm/src/multi_sig.rs

This PR reorganize the order of the structs and implementations in `multi_sig.rs`.
- Branch
- PR

Reorganize mithril-stm multi_sig.rs

---

.github/workflows/ci.yml
mithril-infra/assets/tools/pool/query-stake-pool.sh

This PR adds a third signer to the `testing-preview` network. 
:warning: This requires to update the host machine with more memory from `e2-standard-2` to `e2-highmem-2` instance.
- Branch
- PR
Relates to #729

Add new signer in 'testing-preview'

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/devnet/runner.rs

This PR includes a fix on the end to end test to use the exit code of commands executed with shell when interacting with the `devnet`. This will stop the end to end test if starting the `devnet` or delegating stakes fails e.g.
- Branch
- PR

Enhance errors catching in end to end test

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/cardano/key_certification.rs
mithril-signer/Cargo.toml
mithril-signer/src/single_signer.rs

This PR includes a fix to the error received by some signers when attempting to create a single signature: `ProtocolInitializerNotRegistered(CoreRegister(UnregisteredInitializer))`
After investigation, it appears that this error occurs when a signer is signing a message and is not registered for the next epoch: in that case the signer should be able to sign and should only skip signing at the next epoch. The fix replaces the usage of a protocol initializer with a clerk instead to compute the aggregate verification key that is embedded in the signed message.
- Branch
- PR
Closes #730

Fix 'UnregisteredInitializer' error on signer

---

mithril-stm/src/multi_sig.rs

This PR includes the helper functions that store all usage of unsafe code in `multi_sig.rs`. 
- Branch
- PR
Closes #690

helper for unsafe code

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/event_store/event.rs

This makes the aggregator compatible with Sqlite versions more recent than 3.38. 
- Branch
- PR
None
Closes #757

#757 replace unixepoch with strftime

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/command_args.rs
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/tools/era.rs
mithril-aggregator/src/tools/mod.rs
mithril-common/Cargo.toml
mithril-common/src/chain_observer/cli_observer.rs
mithril-common/src/chain_observer/mod.rs
mithril-common/src/chain_observer/model.rs
mithril-common/src/entities/mod.rs
mithril-common/src/entities/type_alias.rs
mithril-common/src/era/adapters/bootstrap.rs
mithril-common/src/era/adapters/cardano_chain.rs
mithril-common/src/era/adapters/mod.rs
mithril-common/src/era/supported_era.rs

This PR includes a Era command in the aggregator cli that:
- Lists the supported eras
- Generate a `TxDatum` JSON that can be used in an on-chain transaction
- Branch
- PR
Closes #755

Add era command in aggregator cli

---

.github/workflows/ci.yml
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-common/Cargo.toml
mithril-common/src/chain_observer/model.rs
mithril-common/src/era/supported_era.rs

This PR includes a dynamic generation of the matrix cases of the end to end tests in the CI. It now uses the list of available eras and combines them with the number of runs by era.
- Branch
- PR
Closes #760

Add dynamic matrix in CI for end to end tests

---

mithril-aggregator/utils/monitoring/stake_signer_version.sql

This PR fixes a bug present in the monitoring SQL queries that pops on SQLite 3.41.
- Branch
- PR
None
Closes #762

fix sqlite sprintf bug

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/signer_routes.rs

This PR adds a warning when the Epoch can not be fetched when sending an event.
- Branch
- PR
None
None

add warning when event can not send epoch

---

docs/root/manual/developer-docs/nodes/mithril-aggregator.md
docs/root/manual/getting-started/run-mithril-devnet.md
mithril-aggregator/README.md
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-infra/assets/startup-vm.sh

This PR includes the update of SQLite to `3.40` in the infra of the Aggregator
- Branch
- PR
Closes #765

Upgrade SQLite to `3.40` in aggregator infra

---

mithril-client/Dockerfile.ci

This PR includes a fix to client docker image built from CI that is crashing with a `/app/bin/mithril-client: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory` error.
- Branch
- PR
Relates to #769

Fix client Docker image crash

---

Cargo.lock
mithril-stm/Cargo.toml
mithril-stm/src/merkle_tree.rs

This PR includes the changes to handle tests for batched Merkle opening.
- Branch
- PR
Closes #772

Test batch opening mtree

---

docs/root/manual/developer-docs/nodes/mithril-client.md
docs/root/manual/getting-started/bootstrap-cardano-node.md
mithril-client/Dockerfile.ci

- A fix to the Docker Client image that crashes because of missing home directory for the `appuser`
- An update to the documentation with Docker images usage in:
- [Mithril Client Node](https://mithril.network/doc/manual/developer-docs/nodes/mithril-client) developers doc
- [Bootstrap a Cardano Node](https://mithril.network/doc/manual/getting-started/bootstrap-cardano-node) user guide
The [Mithril Client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) GitHub action will be updated to also test the behavior of the Docker Client image.
- Branch
- PR
Closes #791

Fix Docker Client crash

---

Cargo.lock
demo/protocol-demo/Cargo.toml
demo/protocol-demo/src/demonstrator.rs
mithril-common/Cargo.toml
mithril-common/src/chain_observer/cli_observer.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/test_utils/fixture_builder.rs
mithril-stm/Cargo.toml
mithril-stm/benches/size_benches.rs
mithril-stm/benches/stm.rs
mithril-stm/examples/key_registration.rs
mithril-stm/tests/test_stm_protocol.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/devnet/runner.rs

This PR includes a fix to remove clippy warnings that arose with the new version of Rust `1.68.0`
- Branch
- PR

Fix clippy warnings from Rust `1.68.0`

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml

This PR includes an upgrade to VM of testing networks in order to avoid OOM:
- `testing-preview` to `e2-highmem-4`
- `pre-release-preview` to `e2-highmem-2`
- Branch
- PR
Closes #801

Upgrade VM `testing-preview` & `pre-release-preview` networks

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/command_args.rs
mithril-aggregator/src/database/provider/stake_pool.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/stake_distribution_service.rs
mithril-aggregator/tests/certificate_chain.rs
mithril-aggregator/tests/test_extensions/dependency.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/Cargo.toml
mithril-common/src/chain_observer/mod.rs
mithril-common/src/database/version_checker.rs
mithril-common/src/entities/type_alias.rs
mithril-common/src/store/adapter/sqlite_adapter.rs
mithril-common/src/store/stake_store.rs
mithril-common/src/store/store_pruner.rs
mithril-common/src/test_utils/mithril_fixture.rs
mithril-signer/Cargo.toml
mithril-signer/src/main.rs
mithril-signer/src/runtime/signer_services.rs

This PR includes a refactoring to manage stakes from a dedicated service out of the `MultiSigner`.
- Branch
- PR
None
Closes #799

#799 stake pool service 

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-aggregator/tests/certificate_chain.rs
mithril-aggregator/tests/create_certificate.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/Cargo.toml

This PR includes a cleanup of the multi-signer:
- Removing unused functions
- Reducing the state to the minimum possible at the moment: keep only `current_message`, `current_beacon` and the dependencies
- Refactor function signatures for register single signatures and create multi-signature
- Branch
- PR
Closes #824

Cleanup multi-signer

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/runtime/state_machine.rs

This PR fixes a non critical error that has been mislabeled as critical error when the quorum is not reached for producing a multi-signature in the aggregator
- Branch
- PR
Relates to #824

Fix mislabeled critical error

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/epoch_setting.rs

This PR includes  the missing implementation of the `remove` function from the `StoreAdapter` trait that is called when the store is pruned. This will avoid having the node panic when Epoch transitions.
- Branch
- PR
Relates to #813

Fix Epoch Setting store panic

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/migration.rs
mithril-aggregator/src/database/provider/epoch_setting.rs
mithril-aggregator/src/database/provider/mod.rs
mithril-aggregator/src/database/provider/signer_registration.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/signer_registerer.rs
mithril-aggregator/src/store/verification_key_store.rs

Create/Migrate `signer_registration` store

---

mithril-infra/assets/docker/docker-compose-aggregator.yaml

This PR includes a temporary fix for a panic that occurs on the store pruning of the epoch settings store
- Branch
- PR
Relates to #828

Remove store retention limit in aggregator infra

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/open_message.rs
mithril-common/Cargo.toml
mithril-common/src/entities/mod.rs
mithril-common/src/entities/signed_entity_type.rs

Since each message type has its own beacon, it is now embedded in `SignedEntityType` in the `OpenMessage` type.
- Branch
- PR
None
Closes #848

embed beacon in open_message type

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/migration.rs
mithril-aggregator/src/database/provider/mod.rs
mithril-aggregator/src/database/provider/signed_entity.rs
mithril-aggregator/src/dependency_injection/builder.rs

Create/Migrate `signed_entity` store

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/ticker_service.rs

This PR adds a ticker service that is responsible of providing the current beacon for each type of message.
- Branch
- PR
None
Closes #849

849 - Add ticker service

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/certifier_service.rs
mithril-aggregator/src/database/provider/open_message.rs
mithril-aggregator/src/database/provider/single_signature.rs
mithril-aggregator/src/entities/mod.rs
mithril-aggregator/src/entities/open_message.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-aggregator/tests/test_extensions/open_message_observer.rs

This PR add an OpenMessage domain type that is used by the aggregator services & state machine instead of the record types in order to have a clear split between the domain and the database. 
- Branch
- PR
Also reintroduce a test in the aggregator state machine that we forgot to uncomment & fix in #866.
Closes #878

Add open message domain type

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/signable_builder/mod.rs
mithril-aggregator/src/signable_builder/signable_builder_service.rs
mithril-common/Cargo.toml
mithril-common/src/digesters/cache/json_provider.rs
mithril-common/src/signable_builder/cardano_immutable_full_signable_builder.rs
mithril-common/src/signable_builder/immutable_signable_builder.rs
mithril-common/src/signable_builder/mod.rs
mithril-signer/Cargo.toml
mithril-signer/src/lib.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/src/signable_builder/signable_builder_service.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR includes add SignableBuilder in the Signer binary.
- Branch
- PR
Implementation done, not yet used by the runner system.
Relates to #852

add signable builder in signer

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/artifact_builder_service.rs
mithril-aggregator/src/artifact_builder/dummy_artifact.rs
mithril-aggregator/src/artifact_builder/mithril_stake_distribution.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-common/Cargo.toml
mithril-common/src/signable_builder/interface.rs

- A fix that makes the `Artifact` trait usable as trait object (compliant with `object safety`)
- The conversion of the `ArtifactBuilderService` to a trait
- Branch
- PR
Relates to #870

Make `Artifact` usable as trait object

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/artifact_builder_service.rs
mithril-aggregator/src/artifact_builder/cardano_immutable_files_full.rs
mithril-aggregator/src/artifact_builder/mithril_stake_distribution.rs
mithril-aggregator/src/artifact_builder/mod.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/snapshot_uploaders/dumb_snapshot_uploader.rs
mithril-common/Cargo.toml
mithril-common/src/entities/snapshot.rs

This PR includes the implementation of:
- Cardano Immutable Files Full Artifact builder in aggregator
- Branch
- PR
Relates to #871

Cardano Immutable Files Full Artifact builder in aggregator

---

Cargo.lock
docs/blog/2022-09-13-stake-distribution-retrieval.md
mithril-aggregator/Cargo.toml
mithril-common/Cargo.toml
mithril-common/src/chain_observer/cli_observer.rs
mithril-signer/Cargo.toml

This PR includes the implementation of the new Stake Distribution computation:
- Use the new `query stake-snapshot --all-stake-pools` command when available (Cardano node `8.0.0+`)
- Fallback on the (now) legacy former computation of the Stake Distribution otherwise (Cardano node `1.35.7-`)
- Branch
- PR
Closes #919

Implement new Stake Distribution computation

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs

This PR includes a fix to make legacy snapshot routes redirect to new ones (prefixed by `artifact`)
- Branch
- PR
Relates to #893

Fix legacy snapshot routes redirect

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-common/Cargo.toml
mithril-common/src/chain_observer/cli_observer.rs
mithril-signer/Cargo.toml

This PR includes a fix on the new stake distribution computation that does not include pools with zero stake.
This will avoid a discrepancy in the AVK computation between legacy and new versions.
- Branch
- PR
Relates to #919

Fix stake distribution computation for zero stake pools

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-client/Cargo.toml
mithril-signer/Cargo.toml
openapi.yaml

This PR includes a rollback of the open api version to `0.1.x` to avoid a breaking change on the signer nodes. 
This should have been handled with an era switch. This will be done in another PR.
- Branch
- PR

Fix open api version

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/certifier_service.rs
mithril-aggregator/src/database/provider/certificate.rs
mithril-aggregator/src/http_server/routes/certificate_routes.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/message_adapters/mod.rs
mithril-aggregator/src/message_adapters/to_certificate_list_message.rs
mithril-common/src/messages/certificate_list.rs
mithril-common/src/messages/mod.rs
openapi.yaml

This PR includes the implementation of a new route `/certificates` that lists the latest certificates produced by the Aggregator
- Branch
- PR
Relates to #892

Add Certificate list route to aggregator REST API

---

.github/workflows/ci.yml
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/single_signature.rs
mithril-stm/Cargo.toml
mithril-stm/src/eligibility_check.rs

This PR includes fix for new clippy warnings with Rust `1.70.0` and attempts fixing the tests failing in the CI because of use of `-Z unstable-options` in the `cargo test` command.
- Branch
- PR
Relates to #958

Upgrade Rust `1.70.0`

---

Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/aggregator_client/mithril_stake_distribution_client.rs
mithril-client/src/aggregator_client/mod.rs
mithril-client/src/commands/mithril_stake_distribution/list.rs
mithril-client/src/commands/mithril_stake_distribution/mod.rs
mithril-client/src/commands/mithril_stake_distribution/verify.rs
mithril-client/src/commands/mod.rs
mithril-client/src/commands/snapshot/mod.rs
mithril-client/src/commands/snapshot/show.rs
mithril-client/src/dependencies/builder.rs
mithril-client/src/entities.rs
mithril-client/src/main.rs
mithril-client/src/message_adapters/from_mithril_stake_distribution_list.rs
mithril-client/src/message_adapters/from_mithril_stake_distribution_message.rs
mithril-client/src/message_adapters/mod.rs
mithril-client/src/services/mithril_stake_distribution.rs
mithril-client/src/services/mock.rs
mithril-client/src/services/mod.rs
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_verifier.rs

This PR includes a client subcommand to list and restore mithril stake distributions.
- Branch
- PR
Lot of refactoring needs to be made to ease calculation of messages and tests.
Closes #896

Stake distribution client subcommand

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/certifier_service.rs
mithril-aggregator/src/database/provider/open_message.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/runner.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs

This PR includes a fix on the way the open message is retrieved by signed entity type: it aligns the queries used to retrieve open message with/without single signatures in the Open Message Repository.
**Note**: 
- this will avoid collision such as described in the logs where an open message is `not certified` when used in `get_current_non_certified_open_message_for_signed_entity_type` fucntion, and `certified` in the `create_certificate` function
- the probable cause is that there must be `2` different open messages created during the same epoch but with `2` different epochs in the signed entity type field. It looks like this happens when there is a de-synchronization of the epoch inside the `CertifierService` and the epoch given by the `ChainObserver`. This is probably a cause of the …

Fix retrieve open message from correct epoch

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/open_message.rs

This PR includes a fix to the clean of open messages: they must be cleaned only for an epoch strictly lower than the one given by the chain observer.
- Branch
- PR
Relates to #953

Fix clean epoch Certifier service

---

.gitignore
Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/digesters/cardano_immutable_digester.rs
mithril-common/src/digesters/dumb_immutable_observer.rs
mithril-common/src/digesters/immutable_digester.rs

This PR includes an update of the `NotEnoughImmutable` error message. It now displays the `db_dir`, `expected_number` and `found_number` when not enough immutable files are found in the Cardano node DB directory.
- Branch
- PR
None
Close #969

Enhance ImmutableDigesterError::NotEnoughImmutable error

---

docs/blog/2023-06-14-new-client-interface.md

This PR includes a blog post to explain that the CLI options are going to change and why.
- Branch
- PR
Relates to #960

add blog article about new client API

---

docs/package.json
docs/root/manual/developer-docs/nodes/mithril-client.md
mithril-client/src/commands/mithril_stake_distribution/download.rs

This PR includes some updates of the Mithril Client Documentation. It details the new commands related to the Mithril Stake Distribution.
- Branch
- PR
None
Relates to #897

Update Mithril Client documentation

---

Cargo.lock
demo/protocol-demo/Cargo.toml
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-stm/Cargo.toml

This PR includes an upgrade of the outdated Rust dependencies except for:
- `sqlite` which requires a refactoring of the `Cursor` and `Row`
- `rand-chacha-dalek-compat` which creates a build error `error: the crate mithril-common v0.2.62 depends on crate rand_chacha v0.3.1 multiple times with different names`
- Branch
- PR

Upgrade Rust outdated dependencies

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/command_args.rs
mithril-aggregator/src/dependency_injection/builder.rs

- Branch
- PR
None
Closes #993

fix hanging critical error

---

flake.lock
flake.nix

Currently main nix build fails with
```
error: failed to remove file /build/source/target/release/crane-dummy
```
- Branch
- PR

nix: bump crane to fix build. Add basic hydraJobs.

---

mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/migration.rs

This PR fix the migration that migrate dates in the aggregator database to the rfc 3339 format.
The `created_at` & `artifact` columns of the `signed_entity` table were swapped, leading to an error when querying any artifacts.
- Branch
- PR
Relates to #946, Fix a bug introduced in #994

Fix rfc3339 datetime migration

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/certificate.rs

This PR fix master certificate retrieval on a edge case:
If on the queried epoch, epoch with already existing certificates, a genesis certificate is added then the returned certificate when asking the master of that epoch would not be the new genesis but the first certificate of the epoch.
This PR also fix a bad behavior when `CertificateRecord` are converted back to `Certificate`: this would recompute the certificate hash, meaning that the real hash, used as the id of the certificate table, would be lost.
- Branch
- PR
Closes #1006

Fix master certificate retrieval

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/signed_entity.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/tests/certificate_chain.rs
mithril-aggregator/tests/create_certificate.rs
mithril-aggregator/tests/era_checker.rs
mithril-aggregator/tests/simple.rs
mithril-aggregator/tests/test_extensions/aggregator_observer.rs
mithril-aggregator/tests/test_extensions/expected_certificate.rs
mithril-aggregator/tests/test_extensions/mod.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/Cargo.toml
mithril-common/src/entities/signed_entity_type.rs
mithril-common/src/test_utils/mithril_fixture.rs

This PR simplify the integration tests of the aggregator by replacing most asserts by a new macro `assert_last_certificate_eq`.
Before we to manually get multiple information in the tested aggregator to do our assertion, the new mactro streamlined this and a new type, `ExpectedCertificate`, allow to specify the subset of data that is meaningful to verify in a Certificate. 
- Branch
- PR
To make the new macro work the capacity to get a `SignedEntity` by its Certificate id had to be added to the `SignedEntityStorer`.

Simplify aggregator integration tests

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/runtime/error.rs
mithril-aggregator/src/runtime/runner.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/state_machine.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs

This PR includes a fix to end to end tests flakiness that occurred because the aggregator was computing an open message with the wrong epoch.
- Branch
- PR
Closes #954

Fix flaky end to end tests 

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_immutable_files_full.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/snapshotter.rs

This PR includes changes that handle the `pending_snapshot` directory cleanup.
It also includes a refacto of `GzipSnapshotter`.
- Branch
- PR
Details of `pending_snapshot` directory cleanup :
- Directory is totally cleaned in `GzipSnapshotter` constructor
- The temporary file is removed if an error occurs in `upload_snapshot_archive` in `cardano_immutable_files_full`
- The temporary file is removed if an error occurs during the creation of the archive in `Snapshotter::snapshot`
- Tests were added to control these cases
Detail of `GzipSnapshotter` refacto : 
- The creation of the `pending_snapshot` directory was moved into the `GzipSnapshotter` constructor
- `create_archive` now returns `filesize` which can be an error
Closes #983

Clean pending_snapshot directory of aggregator

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/runtime/error.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-aggregator/src/signed_entity_service.rs

This PR makes the aggregator retry when artifact creation fails. If the artifact creation still fails, the state machine is reset.
- Branch
- PR
None
Closes #984

retry when artifact creation failed

---

.config/nextest.toml
.github/workflows/actions/toolchain-and-cache/action.yml
.github/workflows/ci.yml

This PR changes the runner that are used for tests in CI to [`cargo-nextest`](https://nexte.st/index.html). This give the following benefits :
- Re-enable tests reports in our PR using [nextest junit support](https://nexte.st/book/junit.html) without the need of `cargo2junit` and unstable cargo features.
- Faster tests because of nextest execution model being more aggressive with parallelization (ie: integration tests can run in parallel of units test).
This PR also changes the way third party cargo tools are retrieved in the CI: instead of using `cargo install` that retrieve the tool source and compile them (making our github caches heavier) we now use [`cargo binstall`](https://github.com/cargo-bins/cargo-binstall) to retrieve precompiled binaries.
- Branch
- PR
Closes #978

Use cargo-nextest to run test on CI and reenable tests report

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/signer_registration.rs
mithril-aggregator/src/dependency.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/signer_registerer.rs
mithril-aggregator/src/store/mod.rs
mithril-aggregator/src/store/verification_key_store.rs
mithril-aggregator/tests/certificate_chain.rs
mithril-aggregator/tests/genesis_to_signing.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/Cargo.toml
mithril-common/src/entities/epoch.rs

This PR replace the `SignerRegistrationStoreAdapter` with a new `VerificationKeyStorer` implementation: `SignerRegistrationStore`.
This new implementation use the database provider directly instead of being a `StoreAdapter` meaning that when calling `save_verification_key` only the given value will be saved or updated, the previous store worked only on the epoch level saving all values by batch for a given epoch.
We have a guess that this previous behavior is the reason behind #1015, but since we could not establish the exact scenario that happen in this ticket we don't have tests to ensure that this will effectively solve this bug.
- Branch
- PR
This PR also change who do the pruning of old keys, before it was done in the `VerificationKeyStorer::save_verification_key` …

Signer verification key discrepancy

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/utils/spec_utils.rs

This PR includes a fix in order to avoid consistent failure from the `wait_for_the_expected_time` test of the end to end test on the Hydra CI as seen in https://ci.iog.io/build/175030/nixlog/1
- Branch
- PR

Fix failing end to end test in Hydra CI 

---

.github/workflows/ci.yml
docs/package.json
docs/root/compiled-binaries.md
docs/root/manual/developer-docs/nodes/mithril-aggregator.md
docs/root/manual/developer-docs/nodes/mithril-client.md
docs/root/manual/developer-docs/nodes/mithril-signer.md
docs/root/manual/getting-started/bootstrap-cardano-node.md
docs/root/manual/getting-started/run-mithril-devnet.md
docs/root/manual/getting-started/run-signer-node.md
docs/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-client.md
mithril-aggregator/Dockerfile
mithril-aggregator/Dockerfile.ci
mithril-client/Dockerfile
mithril-client/Dockerfile.ci
mithril-signer/Dockerfile
mithril-signer/Dockerfile.ci

This PR changes the ubuntu version used to build the linux binaries in order to depends on a earlier version of glibc (2.31 instead of 2.35) to be compatible with more systems.
The minimum required version is now stated in the documentation. 
It also add the [dependency-review](https://github.com/marketplace/actions/dependency-review) action to our check step. 
- Branch
- PR
This PR also update the documentation regarding the fact that sqlite is not required anymore to build & run the binaries (see #837). 
Closes #874, Closes #1037, Relates to #834 and #837

CI: Build linux binaries using ubuntu 20-04 and add vulnerabilities check

---

.github/workflows/ci.yml

This PR fix the dependency review action when merging PR on the main branch by providing the arguments that this action ask when running on something else than a `pull_request` action trigger.
- Branch
- PR
Relates to #1037

Fix dependency-review check when merging to main

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/certifier_service.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/error.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/tools/genesis.rs
mithril-client/Cargo.toml
mithril-client/src/services/mithril_stake_distribution.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/crypto_helper/types.rs
mithril-common/src/lib.rs
mithril-common/src/protocol/mod.rs
mithril-common/src/protocol/multi_signer.rs
mithril-common/src/protocol/signer_builder.rs
mithril-common/src/protocol/single_signer.rs
mithril-common/src/test_utils/fixture_builder.rs
mithril-common/src/test_utils/mithril_fixture.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/runner.rs
mithril-signer/src/single_signer.rs

This PR introduce three new types in `mithril-common` in order to factorize crypto operation arround issuing single/multi signatures:
- `protocol::SingleSigner`: Issue single signatures
- `protocol::MultiSigner`: Aggregate single signatures, compute avk, and verify single signatures
- `protocol::SignerBuilder`: A builder for the two previous types, handle the key registration..
- Branch
- PR
Relates to #669

Factorize crypto operation

---

.github/workflows/actions/prepare-distribution/action.yml
.github/workflows/ci.yml
.github/workflows/pre-release.yml

This PR add the minimum libc version to [the distribution release notes](https://github.com/input-output-hk/mithril/releases).
- Branch
- PR
This PR also factorize part of the distribution packaging step in a composite action.
Relates to #874

Add min libc version to distribution release note

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/tools/certificates_hash_migrator.rs
mithril-client/Cargo.toml
mithril-client/src/services/snapshot.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/cardano/codec.rs
mithril-common/src/crypto_helper/cardano/key_certification.rs
mithril-common/src/signable_builder/cardano_immutable_full_signable_builder.rs
mithril-common/src/store/adapter/memory_adapter.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/runner.rs
mithril-stm/Cargo.toml
mithril-stm/src/merkle_tree.rs

This PR includes fixes for new clippy warnings with Rust `1.71.0` release.
- Branch
- PR

Upgrade Rust `1.71.0`

---

.github/workflows/release.yml

This PR includes the `terraform` deployment of the `release-mainnet` network in the `Release` workflow of GitHub actions.
- Branch
- PR
Relates to #988

Add `release-mainnet` deployment to CD

---

.github/workflows/actions/prepare-distribution/action.yml

This PR includes a fi xto the release notes generation that did not show the `crates versions` section.
- Branch
- PR

Fix crates versions not shown in release notes

---

docs/root/networks-matrix.md
mithril-explorer/aggregators-list.js
mithril-explorer/package.json

- The configuration for the `release-mainnet` network in the network configuration blocks of the documentation
- The configuration of the `release-mainnet` network in the explorer
- Branch
- PR
Relates to #918

Add `release-mainnet` configuration in documentation and explorer

---

.github/workflows/actions/build-upload-mithril-artifact/action.yml
.github/workflows/ci.yml
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/main.rs
mithril-client/Cargo.toml
mithril-client/src/main.rs
mithril-common/Cargo.toml
mithril-signer/Cargo.toml
mithril-signer/src/main.rs

This PR add a the `bundle_openssl` feature to our main binaries (client, aggregator, signer).
This feature enable the `vendored` feature of the [openssl crate](https://crates.io/crates/openssl) in order to compile and statically link a copy of OpenSSL.
- Branch
- PR
Enabling the [`vendorded` feature](https://docs.rs/openssl/latest/openssl/index.html#vendored) as the following side effects:
- the bundled openssl loose the capacity to automatically find the system root certificates, we must find them manually using [`openssl_probe` crate](https://crates.io/crates/openssl-probe).
- to build OpenSSL the build process requires the following dependencies: a C compiler, perl (and perl-core), and make
Relates to #1073

Bundle openssl with released binaries

---

Cargo.lock
docs/root/manual/developer-docs/nodes/mithril-aggregator.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/genesis_command.rs
mithril-aggregator/src/tools/genesis.rs
mithril-common/src/crypto_helper/genesis.rs

This PR includes a new `sign` sub-command in the `genesis` command.
- Branch
- PR
Closes #1081

Add `sign` sub-command in aggregator `genesis` command

---

docs/root/manual/getting-started/SPO-on-boarding-guide.md
docs/root/manual/getting-started/run-signer-node.md
docs/static/scripts/verify_signer_registration.sh
docs/static/scripts/verify_signer_signature.sh

This PR includes improvements of the guide "Run a Mithril Signer as an SPO". Examples have been added with the appropriate values for `release-preprod` network.
Two scripts have also been created to verify that the signer node is correctly configured and to check that it's correctly signing certificates. They are located in `/docs/static/scripts/` directory.
A description of how to run them have been added at the end of the guide.
- Branch
- PR
None
Closes #1055

Enhance Run a Mithril Signer as an SPO guide

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_immutable_files_full.rs
mithril-aggregator/src/database/provider/certificate.rs
mithril-aggregator/src/database/provider/epoch_setting.rs
mithril-aggregator/src/database/provider/open_message.rs
mithril-aggregator/src/database/provider/signer_registration.rs
mithril-aggregator/src/database/provider/single_signature.rs
mithril-aggregator/src/database/provider/stake_pool.rs
mithril-aggregator/src/database/provider/test_helper.rs
mithril-aggregator/src/services/ticker.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/entities/beacon.rs
mithril-common/src/entities/epoch.rs
mithril-common/src/entities/mithril_stake_distribution.rs

This PR simplify the usage of the epoch types by removing the need to access the inner `u64` (with the `epoch.0` syntax) by implementing the `Deref` & `TryInto<i64>` traits .
- Branch
- PR
Relates to #YYY ?

Simplify epoch type by implementing Deref & TryInto<i64>

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/signer_registration.rs
mithril-aggregator/src/entities/mod.rs
mithril-aggregator/src/entities/signer_registration_message.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/store/mod.rs
mithril-aggregator/src/store/verification_key_store.rs
mithril-common/Cargo.toml
mithril-common/src/entities/epoch.rs
mithril-common/src/test_utils/apispec.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
openapi.yaml

This PR add a new route to the aggregator, `/signers/registered/{epoch}`, that allow to retrieve the signer registration for a given epoch.
- Branch
- PR
Relates to #1097

Add signers registered route to aggregator

---

Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/services/snapshot.rs

This PR make the `snapshot download` command of the client append a empty file named 'clean' in the unpacked database.
This is a trick to tell the cardano node to skip the ledger check at startup (this file is usually added by the node itself on a clean shutdown).
- Branch
- PR
Relates to #1131

Speedup node bootstrap after client download

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/signed_entity.rs
mithril-aggregator/src/snapshotter.rs

This PR includes a fix for the aggregator producing from time to time corrupted archives: the created snapshot archive is verified before being published. This is a quick term fix, and a new implementation of the snapshot production will be done shortly.
- Branch
- PR
Closes #1137

Add snapshot archive verification

---

docs/root/mithril/mithril-protocol/protocol.md

This PR includes a review of the protocol description in protocol.md
- Branch
- PR
Relates to ECS-3077

ECS-3077 Apply style guide, tighten some sentences.

---

Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/utils/unpacker.rs

This PR includes a fix to get a full subsystem error displayed when the unpack of the archive fails
- Branch
- PR
Relates to #1147

Better unpack error in client

---

mithril-explorer/Makefile
mithril-explorer/__tests__/stakeFormat.test.js
mithril-explorer/package.json
mithril-explorer/src/app/layout.js
mithril-explorer/src/app/page.js
mithril-explorer/src/app/registrations/page.js
mithril-explorer/src/components/CertificateModal/index.js
mithril-explorer/src/components/EpochSettings/index.js
mithril-explorer/src/components/LinkButton.js
mithril-explorer/src/components/Stake.js
mithril-explorer/src/constants.js
mithril-explorer/src/store/provider.js
mithril-explorer/src/store/store.js
mithril-explorer/src/utils.js
mithril-explorer/yarn.lock

This PR add a new pages to the explorer: Registrations. This pages can be navigated to by using a button at the bottom of the epoch settings card.
It display the registered signers for a given epoch, their stakes, two charts (breakdown of the stakes and the signers weigth) and allow to navigate to the registration of the previous, current or next epoch.
- Branch
- PR
Closes #1097

Registered signers page to explorer

---

docs/website/root/glossary.md

ECS-3156 Review glossary. Adjust capitalization and bolding.

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/cardano/key_certification.rs

This PR fix a regression made by https://github.com/input-output-hk/mithril/pull/1164.
After merging this PR the persist of the signer `ProtocolInitializer`, created with the registration to the aggregator, failed with the following error:
```
An error occured, runtime state kept.
message =
'Could not register to aggregator in 'unregistered → registered' phase for epoch Epoch(297).'.
nested error =
Store adapter raised an error: problem parsing the IO stream:
invalid type: map, expected a string at line 1 column 925\n\n
Caused by:\n    problem parsing the IO stream: invalid type: map, expected a string at line 1 column 925
``` 
- Branch
- PR
Relates to #668, fix regression from #1164

Regression on signer registration

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/certificate.rs
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/message_adapters/to_certificate_message.rs
mithril-aggregator/src/message_adapters/to_certificate_pending_message.rs
mithril-aggregator/src/services/certifier.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator_client/certificate_client.rs
mithril-common/Cargo.toml
mithril-common/src/entities/certificate.rs
mithril-common/src/entities/signer.rs
mithril-common/src/entities/single_signatures.rs
mithril-common/src/messages/certificate.rs
mithril-common/src/messages/certificate_list.rs
mithril-common/src/messages/certificate_pending.rs
mithril-common/src/messages/message_parts/certificate_metadata.rs
mithril-common/src/messages/message_parts/mod.rs
mithril-common/src/messages/message_parts/signer.rs
mithril-common/src/messages/mod.rs
mithril-common/src/messages/register_signature.rs
mithril-common/src/messages/register_signer.rs
mithril-common/src/test_utils/apispec.rs
mithril-signer/Cargo.toml
mithril-signer/src/message_adapters/from_pending_certificate_message.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/assertions/check.rs
mithril-test-lab/mithril-end-to-end/src/assertions/wait.rs

This PR changes implementation of the `Debug` trait from the automatic derive to manual for entities that use protocol keys or messages that use encoded keys. 
This makes the logs far more readable in exchange for not printing anymore those keys.
The keys can still be print by using a `#` / pretty print (or "alternate" mode) when logging.
- Branch
- PR
Here's a pretty printed (real logs are on one line) before/after for the pending certificate log in the signer node:
```
{
"msg": " ⋅ Epoch has NOT changed but there is a pending certificate",
"v": 0,
"name": "slog-rs",
"level": 30,
"time": "2023-08-18T15:41:23.51891215Z",
"hostname": "hostname",
"pid": 892261,
"pending_certificate": ""                                                                  
CertificatePending { …
```

Simplify logs

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/genesis_command.rs
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/signer_registerer.rs
mithril-aggregator/src/tools/genesis.rs
mithril-client/Cargo.toml
mithril-client/src/services/mithril_stake_distribution.rs
mithril-client/src/services/snapshot.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/conversions.rs
mithril-common/src/crypto_helper/genesis.rs
mithril-common/src/crypto_helper/types/alias.rs
mithril-common/src/crypto_helper/types/protocol_key.rs
mithril-common/src/crypto_helper/types/wrappers.rs
mithril-common/src/entities/signer.rs
mithril-common/src/protocol/signer_builder.rs
mithril-common/src/test_utils/mithril_fixture.rs

This PR implements ProtocolKey type to handle serialization and deserialization of the Genesis Secret Key and Genesis Verification Key.
This was achieved following the methodology described in the issue https://github.com/input-output-hk/mithril/issues/668.
Copy trait was implemented for `ProtocolKey<T>`. So unnecessary clone() have been removed.
- Branch
- PR
None
Relates to #668

Protocol key for genesis keys

---

flake.nix

>
This PR includes a quick fix to error: **failed to create file `/build/source/target/release/load-aggregator.d`** that happened in Hydra and was reproducible with `nix build .#hydraJobs.x86_64-linux.mithril-end-to-end`.
- Branch
- PR
This PR does fix the issue, but I'm not sure to understand fully the implications of the change. So reviews are welcome! :)
N/A

Fix broken `.#hydraJobs.x86_64-linux.mithril-end-to-end`

---

docs/website/root/manual/getting-started/run-signer-node.md
docs/website/static/scripts/verify_signer_registration.sh
docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md

This PR includes an update of `verify_signer_registration` script.
It now calls `/epoch-settings` and`/signers/registered/` to find out whether or not the signer is registered at the current epoch.
- Branch
- PR
Run a Mithril signer as an SPO guide was updated for both versions (current & next).
Closes #1152

Call Aggregator API to verify Signer registration

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/certificate.rs
mithril-aggregator/src/message_adapters/to_certificate_list_message.rs
mithril-aggregator/src/message_adapters/to_certificate_message.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/tools/certificates_hash_migrator.rs
mithril-aggregator/src/tools/genesis.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator_client/certificate_client.rs
mithril-client/src/message_adapters/from_certificate_message_adapter.rs
mithril-client/src/services/mithril_stake_distribution.rs
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_genesis.rs
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/crypto_helper/types/alias.rs
mithril-common/src/crypto_helper/types/wrappers.rs
mithril-common/src/entities/certificate.rs
mithril-common/src/messages/certificate.rs
mithril-common/src/protocol/multi_signer.rs
mithril-common/src/protocol/signer_builder.rs
mithril-common/src/test_utils/fake_data.rs
mithril-common/src/test_utils/fake_keys.rs
mithril-common/src/test_utils/mithril_fixture.rs
mithril-signer/Cargo.toml
mithril-signer/src/single_signer.rs

This PR update from a string to a `ProtocolKey` most usages of aggregate verification key.
- Branch
- PR
The `ProtocolMessage` `NextAggregateVerificationKey` was not updated since in order to do so we need to redesign the protocol message api to be able to handle other types than just strings.
Relates to #668

Protocol key for AVK

---

Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/aggregator_client/http_client.rs
mithril-client/src/aggregator_client/snapshot_client.rs
mithril-client/src/commands/snapshot/download.rs
mithril-client/src/services/snapshot.rs
mithril-client/src/utils/mod.rs
mithril-client/src/utils/progress_reporter.rs

This PR enhance **mithril-client** command `snapshot download` json output (`--json` parameter).
Instead of reporting nothing until the command finish using `--json` will now print:
- The current step of the process, ie:
```json
{"step_num": 1, "total_steps": 7, "message": "Checking local disk info…"}                                                                                                    
{"step_num": 2, "total_steps": 7, "message": "Fetching the certificate's information…"}                                                                                      
{"step_num": 3, "total_steps": 7, "message": "Verifying the certificate chain…"}                                                                                             
{"step_num": 4, "total_steps": 7, "message": …
```

Client snapshot download progress with json output

---

docs/website/root/manual/developer-docs/nodes/mithril-aggregator.md
docs/website/root/manual/developer-docs/nodes/mithril-client.md
docs/website/root/manual/developer-docs/nodes/mithril-signer.md
docs/website/root/manual/getting-started/bootstrap-cardano-node.md
docs/website/root/manual/getting-started/run-signer-node.md
docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-aggregator.md
docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-client.md
docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-signer.md
docs/website/versioned_docs/version-maintained/manual/getting-started/bootstrap-cardano-node.md
docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md

This PR includes a fix in Mithril documentation. 
`git switch` command was replaced by `git checkout` in guides to handle checking out tags.
- Branch
- PR
Commands were updated for both versions (current & next).
Closes #1174

Replace `git switch` with `git checkout` in docs

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/snapshotter.rs

This PR includes a fix to the archive verification in the aggregator `Snapshotter`: it now verifies that it can unpack all the archive without requiring extra space on disk.
- Branch
- PR
Relates to #1160

Fix verify archive in aggregator Snapshotter

---

docs/website/root/manual/developer-docs/nodes/mithril-client.md
docs/website/root/manual/getting-started/bootstrap-cardano-node.md
docs/website/root/manual/getting-started/run-mithril-devnet.md

This PR includes a fix of the documentation to use the new `latest` value in the client command instead of computing it manually
- Branch
- PR

Fix latest digest usage in documentation

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/utils/spec_utils.rs

This PR includes a fix to the `wait_for_the_expected_time` flaky test on nix.
- Branch
- PR

Fix flaky end to end test

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/.vsls.json
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/bin/load-aggregator/main.rs
mithril-test-lab/mithril-end-to-end/src/lib.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/aggregator_helpers.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/entities.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/fake_chain.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/fake_signer.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/mod.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/payload_builder.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/utils.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/wait.rs

This PR includes a refactoring of the aggregator stress test tool: we have created a `stress_test` sub-module to make the code easier to understand and to maintain
- Branch
- PR
Relates to #1155

Aggregator stress test refactoring

---

Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/services/snapshot.rs

This PR includes a fix that prevented the display of the warning message when the available space on the disk might not be sufficient. The message was displayed only if verbose output (`-v`) was specified.
- Branch
- PR
Relates to #1160

Fix disk space warning not displayed in client

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/codec.rs
mithril-common/src/crypto_helper/types/protocol_key.rs
mithril-common/src/test_utils/fake_keys.rs
mithril-signer/Cargo.toml
mithril-signer/src/single_signer.rs

This PR includes a first implementation related to the error refactoring with the crate anyhow.
`CodecError` is raised when an encoding or decoding occurs.
- Branch
- PR

Add common error: CodecError

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/cardano/cold_key.rs
mithril-common/src/crypto_helper/cardano/opcert.rs
mithril-common/src/crypto_helper/era.rs
mithril-common/src/crypto_helper/genesis.rs
mithril-common/src/crypto_helper/types/wrappers.rs

This PR upgrades Mithril common `ed25519-dalek` dependency from version `1.0.1` to `2.0.0`, adapting to the new api where needed.
This will solve the following dependabot issue: https://github.com/input-output-hk/mithril/security/dependabot/55
- Branch
- PR
Should we rename types to match their updated wrapped inner type ? ie:  `ProtocolGenesisSecretKey` refer to a `ProtocolKey<ed25519_dalek::SigningKey>` and could be renamed to `ProtocolGenesisSigningKey`.
Closes #1155

Upgrade ed25519-dalek to v2

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/api_version.rs

This PR includes an update of `api_version` error handling.
`compute_current_version` errors are now return with a `anyhow` context.
`APIVersionProviderError` was removed as it's no longer used.
- Branch
- PR

Add anyhow context for api_version

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/message_adapters/to_snapshot_list_message.rs
mithril-client/src/services/snapshot.rs
mithril-common/src/messages/snapshot_list.rs
mithril-explorer/package.json
mithril-explorer/src/components/Artifacts/SnapshotsList/index.js

This PR includes the display of the compression algorithm of the snapshot archive in the explorer, if it is available.
- Branch
- PR

Add snapshot archive compression algorithm in explorer

---

Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/commands/snapshot/show.rs

This PR makes the Mithril Client to display the Cardano node version used to produced the given snapshot.
- Branch
- PR
None
Relates to #948

display cardano node version in client

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/message_adapters/from_register_signature.rs
mithril-aggregator/src/message_adapters/from_register_signer.rs
mithril-client/Cargo.toml
mithril-client/src/message_adapters/from_certificate_message_adapter.rs
mithril-client/src/message_adapters/from_mithril_stake_distribution_message.rs
mithril-common/Cargo.toml
mithril-common/src/messages/interface.rs
mithril-signer/Cargo.toml
mithril-signer/src/aggregator_client.rs
mithril-signer/src/message_adapters/from_pending_certificate_message.rs
mithril-signer/src/message_adapters/to_register_signature_message.rs
mithril-signer/src/message_adapters/to_register_signer_message.rs

This PR includes an update of `adapters` modules in order to implement `anyhow` context.
- Branch
- PR
- At the moment, `AggregatorClientError::Adapter` has been added to return the context of adapters errors. This was done to avoid modifying the Signer initial error handling.
- Message adapters in the Aggregator side have not been modified as this requires more in-depth work. HTTP routes currently return `Infallible`.

Implement anyhow context for adapters

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/store/adapter/store_adapter.rs

This PR includes an update of `mithri-common/store/` related to the errors refactoring.
`MutationError`and `TypeError` have been removed since they are not used.
Errors refacto have already been made in this PR: #1162 
- Branch
- PR

Implement anyhow for common store

---

Cargo.lock
mithril-client/Cargo.toml

This PR includes an upgrade of the client version to `0.4.0`. This makes clear that the previous version is no more fully compatible with the aggregator running the new `zstandard` compression format.
- Branch
- PR
Relates to #1219

Upgrade client version to `0.4.0`

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/statistics_routes.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator_client/http_client.rs
mithril-client/src/aggregator_client/snapshot_client.rs
mithril-client/src/message_adapters/mod.rs
mithril-client/src/message_adapters/to_snapshot_download_message.rs
mithril-common/Cargo.toml
mithril-common/src/messages/mod.rs
mithril-common/src/messages/snapshot_download.rs
openapi.yaml

This PR includes a fix to the recording of the snapshot download statistics which was not working properly on `testing-preview`.
- Branch
- PR
Relates to #1127

Fix record download statistics

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/signer_registerer.rs

This PR includes an update of mithril-aggregator `signer_register` with `anyhow` context.
`VerificationKeyStorer::Codec` has been removed as it is not used.
- Branch
- PR

Implement anyhow context in aggregator/signer_register

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/single_signer.rs

This PR includes the update of the signer single-signer to use `anyhow`.
- Branch
- PR

Use anyhow in signer `single-signer`

---

mithril-explorer/package.json
mithril-explorer/src/components/Artifacts/SnapshotsList/index.js
mithril-explorer/src/utils.js

This PR includes a fix on the units used to display file size in the explorer.
- Branch
- PR

Fix explorer display units

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-common/src/crypto_helper/cardano/key_certification.rs
mithril-common/src/protocol/multi_signer.rs
mithril-common/src/protocol/signer_builder.rs
mithril-stm/Cargo.toml
mithril-stm/src/error.rs
mithril-stm/src/lib.rs

This PR includes an update of `multi_signer` and `signer_builder` in aggregator.
`error.to_string().contains()` were removed from tests and replaced by asserts on existing error types.
- Branch
- PR

Get rid of string error comparison in tests

---

CONTRIBUTING.md
docs/website/adr/006-errors-implementation.md

This PR includes a new ADR that relates to error standardization in the Rust crates of the repository. 
Also, the `CONTRIBUTING.md` has been modified to mention the ADRs.
- Branch
- PR

Add errors standards ADR

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/tests/certificate_chain.rs
mithril-aggregator/tests/test_extensions/aggregator_observer.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/Cargo.toml
mithril-common/src/digesters/immutable_file_observer.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/assertions/check.rs
mithril-test-lab/mithril-end-to-end/src/assertions/exec.rs
mithril-test-lab/mithril-end-to-end/src/assertions/wait.rs
mithril-test-lab/mithril-end-to-end/src/devnet/runner.rs
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
mithril-test-lab/mithril-end-to-end/src/main.rs
mithril-test-lab/mithril-end-to-end/src/mithril/aggregator.rs
mithril-test-lab/mithril-end-to-end/src/mithril/client.rs
mithril-test-lab/mithril-end-to-end/src/mithril/infrastructure.rs
mithril-test-lab/mithril-end-to-end/src/mithril/signer.rs
mithril-test-lab/mithril-end-to-end/src/run_only.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/wait.rs
mithril-test-lab/mithril-end-to-end/src/utils/file_utils.rs
mithril-test-lab/mithril-end-to-end/src/utils/mithril_command.rs

This PR upgrades aggregator integration tests & the end-to-end crate to use `anyhow` result & error.
Note: there was nothing to do for `mithril-signer` integration tests
- Branch
- PR
This PR also simplify the aggregator integration tests by building all dependencies before start, removing the need to call the deps builder everytime one is needed (which need error handling).

Add anyhow in integration & e2e tests

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/error.rs
mithril-aggregator/src/signer_registerer.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator_client/http_client.rs
mithril-client/src/services/mithril_stake_distribution.rs
mithril-client/src/utils/unpacker.rs
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_retriever.rs
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/chain_observer/interface.rs
mithril-common/src/chain_observer/model.rs
mithril-common/src/crypto_helper/cardano/codec.rs
mithril-common/src/crypto_helper/era.rs
mithril-common/src/crypto_helper/genesis.rs
mithril-common/src/digesters/cache/provider.rs
mithril-common/src/digesters/immutable_digester.rs
mithril-common/src/digesters/immutable_file.rs
mithril-common/src/digesters/immutable_file_observer.rs
mithril-common/src/era/adapters/builder.rs
mithril-common/src/era/adapters/cardano_chain.rs
mithril-common/src/era/era_reader.rs
mithril-common/src/store/adapter/store_adapter.rs
mithril-signer/Cargo.toml
mithril-signer/src/aggregator_client.rs
mithril-signer/src/runtime/state_machine.rs
mithril-signer/src/single_signer.rs

This PR add the `#[source]` attribute to all wrapped errors if it was missing (which was mostly the case), this allow us to remove the manual print of those wrapped error in the error message.
- Branch
- PR
This PR also contains two small fixes:
- Remove the indirection to a string for the `ChainObserver` variant of the `SignerRegistrationError`.
- Use `tokio::time::sleep` in the mithril-signer state machine, since the one from std block the whole thread and   doesn't yield execution back to the tokio executer.
Closes #1265

Use source attribute in wrapped errors

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/mod.rs
mithril-aggregator/src/http_server/routes/root_routes.rs
mithril-aggregator/src/http_server/routes/router.rs

This PR includes an update of /aggregator/ endpoint behaviour.
Instead of returning a 404 status code error, it now sends a JSON message containing `open_api_version` and `documentation_url` with a status code 200.
- Branch
- PR
Closes #1103

Add a JSON message response on /aggregator endpoint calls

---

Cargo.lock
Cargo.toml
demo/protocol-demo/Cargo.toml
docs/website/package.json
docs/website/yarn.lock
mithril-aggregator/Cargo.toml
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-explorer/package.json
mithril-explorer/yarn.lock
mithril-signer/Cargo.toml
mithril-stm/Cargo.toml
mithril-test-lab/mithril-end-to-end/Cargo.toml

This PR includes updates of the dependencies of the repository:
* Crate `tungstenite` to version `0.20.1`, which fixes the security advisory [`GHSA-9mcr-873m-xcxp`](https://github.com/advisories/GHSA-9mcr-873m-xcxp)
* Rust dependencies for the nodes and libraries
* Documentation website
* Explorer website
- Branch
- PR
Closes #1274

Upgrade dependencies

---

docs/website/docusaurus.config.js
docs/website/package.json

This PR adds a footer link to the [Mithril networks status page](https://mithril.cronitorstatus.com/) on the website.
- Branch
- PR
Relates to #1277

Add Mithril networks status page in website footer

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/serve_command.rs
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/database/migration.rs
mithril-aggregator/src/database/provider/signer.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/dependency_injection/containers.rs
mithril-aggregator/src/entities/mod.rs
mithril-aggregator/src/entities/signer_ticker_message.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/mod.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/signer_registerer.rs
mithril-aggregator/src/tools/mod.rs
mithril-aggregator/src/tools/signer_importer.rs
mithril-aggregator/src/tools/signer_tickers_importer.rs
mithril-common/Cargo.toml
mithril-common/src/test_utils/mod.rs
mithril-common/src/test_utils/test_http_server.rs
openapi.yaml

This PR add to the aggregator:
- The `SignerImporter` services and traits (to define how it retrieves its data and how it persist them)
- Run this service in an infinite loop within a thread when using the serve commands (if an source url is defined, else the thread won't be spawned)
- Add a new route: `/signers/tickers` that expose a simplified view of the `signer` table.
- Add a new field in the `signer` table: `last_registered_at`, since we will now import signers into that table from external source and not create them anymore only at registration.
This PR also add a `TestHttpServer` that allow test to define a http server, configured using warp routes as it's done in the aggregator.
- Branch
- PR
Relates to #1185

Add signers ticker automatic import process + `/signers/tickers` route to aggregator http server 

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/runtime/state_machine.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator_client/certificate_client.rs
mithril-client/src/aggregator_client/mithril_stake_distribution_client.rs
mithril-client/src/services/snapshot.rs
mithril-common/Cargo.toml
mithril-common/src/database/version_checker.rs
mithril-common/src/entities/certificate.rs
mithril-common/src/entities/signer.rs

This PR includes fixes for new clippy warnings with Rust `1.73.0` release.
Some ordering traits have been re-implemented according to the clippy rule: https://rust-lang.github.io/rust-clippy/master/index.html#/incorrect_partial_ord_impl_on_ord_type
- Branch
- PR

Upgrade Rust `1.73.0`

---

mithril-explorer/package.json
mithril-explorer/src/app/page.js
mithril-explorer/src/app/registrations/page.js
mithril-explorer/src/store/poolsSlice.js

This PR add a cache to the request to `/signers/tickers` in explorer, on each page refresh a check is made that clear caches older than 6 hours.
- Branch
- PR
Relates to #1185

Cache `/signers/tickers` calls in explorer

---

Cargo.lock
mithril-stm/CHANGELOG.md
mithril-stm/Cargo.toml
mithril-stm/build.rs
mithril-stm/src/multi_sig.rs
mithril-stm/src/stm.rs

This PR fixes the compilation of the `mithril-stm` library when targeting WASM: 
- The batch signature verification provided by `blst` is not available with WASM
- A build script detects a if WASM is targeted and applies the feature `batch-verify-aggregates` if this is not the case
- The `batch_verify` function is available if the `batch-verify-aggregates` feature is activated
- Branch
- PR
Relates to #1254

Fix `mithril-stm` WASM build

---

.github/workflows/scripts/sign-distribution.sh
.github/workflows/scripts/verify-distribution.sh

This PR includes the renaming of the GPG public key in the releases from `gpg-public.key` to `public-key.gpg`
- Branch
- PR
Closes #1292

Rename GPG public key in releases

---

mithril-test-lab/mithril-devnet/devnet-mkfiles.sh

This PR includes a fix to the aggregator configuration in the `devnet`:
- Added the required `CARDANO_NODE_VERSION` configuration
- Switched to `zstandard` compression with the optional `SNAPSHOT_COMPRESSION_ALGORITHM` configuration
- Branch
- PR
Relates to #1272

Fix missing aggregator configuration in `devnet`

---

mithril-aggregator/Dockerfile.ci
mithril-client/Dockerfile.ci
mithril-signer/Dockerfile.ci

Refactors the Dockerfile and Dockerfile.ci to use release binaries. 
- Branch
- PR
* Reduces the size of existing containers. 
* Does not implement a BuildX cache to leverage identical image layers from previous CI runs.
Relates to #1272

Refactor Dockerfile.ci to slim containers

---

Cargo.lock
mithril-stm/src/stm.rs

This PR includes the fix for the wrong calculation of the total stake in the setup of a core verifier and a test for total stake calculation.
- Branch
- PR
Closes #1306

total_stake calculation corrected

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/router.rs

This PR includes the declaration of the `mithril-api-version` header in the allowed list. This fix avoids getting CORS errors from the WASM Mithril client when it tries to fetch data from the aggregator.
- Branch
- PR
Relates to #1284

Fix aggregator HTTP server CORS

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/certificate.rs

This PR includes a limit in Certificate SQL queries in order to speed up runtime.
- Branch
- PR
The implementation follows some guidelines of SQL [good practices](https://use-the-index-luke.com/sql/partial-results).
Relates to #1310

add soft limit in certificate query

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/services/certifier.rs
mithril-aggregator/src/tools/genesis.rs
mithril-client/Cargo.toml
mithril-client/src/dependencies/builder.rs
mithril-client/src/services/mithril_stake_distribution.rs
mithril-client/src/services/mock.rs
mithril-client/src/services/snapshot.rs
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/crypto_helper/genesis.rs
mithril-common/src/test_utils/fake_keys.rs

This PR simplify the usage of the `CertificateVerifier` by moving the `CertificateRetriever` from its methods parameters to its the implementation.
The goal is to allow to design a simple certificate verification api in the client.
- Branch
- PR
Relates to #1311

Simplify certificate verifier usage

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/snapshot/download.rs
mithril-client-cli/src/commands/snapshot/list.rs

This PR fixes the two regressions detected after the merge of the PR #1291.
- Branch
- PR
- Fix `snapshot list` command: displays the number of locations in the "Locations" column, as before:
- Fix `snapshot run` command: the absolute path is now provided in the docker command in the output after the execution of a `snapshot download` command.
Closes #1321

Client regressions in snapshot list and download

---

mithril-aggregator/Dockerfile.ci
mithril-aggregator/Makefile
mithril-client-cli/Dockerfile.ci
mithril-client-cli/Makefile
mithril-signer/Dockerfile.ci
mithril-signer/Makefile
mithril-test-lab/mithril-devnet/README.md
mithril-test-lab/mithril-devnet/devnet-mkfiles.sh
mithril-test-lab/mithril-devnet/devnet-run.sh

- Building Docker images by default with the CI images (pre-compiled binaries)
- Added the possibility to use a different slim image in the CI images
- Implemented the possibility to use the "legacy" rust builder in the Docker file
- Branch
- PR
Closes #1272

Enhance Mithril nodes `devnet` Docker images

---

mithril-test-lab/mithril-devnet/devnet-mkfiles.sh

This PR includes a fix to the `devnet` that stopped working following modifications of remote file on the `Conway` [genesis file](https://book.world.dev.cardano.org/environments/private/conway-genesis.json) that created a crash at startup: 
```bash
Command failed: genesis create  Error: Error while decoding Shelley genesis at: shelley/genesis.conway.spec.json Error: Error in $: key "genDelegs" not found
```
- Branch
- PR

Fix `devnet` crashing at startup

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

This PR includes a fix for handling a custom **Docker package name** for the `mithril-client-cli` in the CI/CD workflows.
- Branch
- PR
Relates to #1322

Fix client CLI Docker package name in CI/CD

---

mithril-test-lab/mithril-end-to-end/README.md

This PR includes a modification in the README file of mithril-end-to-end.
The paragraph explains how to use the `--skip-cardano-bin-download` command to run the tests.
This option was added with the merge of the PR #1052.
- Branch
- PR

Add Mithril end to end instructions for `--skip-cardano-bin-download` command

---

Cargo.lock
docs/runbook/recompute-certificates-hash/README.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/tools/certificates_hash_migrator.rs

This PR includes a fix of the certificate chain hashes recomputation:
- Avoid reaching the SQLite limit of variables in a query by chunking the inserts
- Minor fixes in the associated runbook
- Branch
- PR

Fix certificate chain hashes recomputation

---

mithril-test-lab/mithril-end-to-end/README.md
mithril-test-lab/mithril-end-to-end/src/main.rs

This PR includes updates of `mithril-end-to-end` related to the the feedback in the PR #1331.
The modifications are linked to issues with the run of the end to end with MacOS: 
- Enhancement of the Readme file to solve the `sed` issue
- Replacement of the default value of `work_directory` as its value was too long
- Branch
- PR

Enhance end to end readme and fix `work_directory` default value on MacOS

---

.github/workflows/actions/prepare-distribution/action.yml

This PR includes a new section in the note published with `unstable` releases.
This subnote explains how to fetch the latest version of the unstable tag from a local repository.
- Branch
- PR
Closes #1235

Add subnote and git command for unstable release

---

.github/workflows/actions/prepare-distribution/action.yml

This PR includes a fix to PR #1334.
The `contains` expression in "Fetch the latest version of the unstable tag" part was not used correctly.
- Branch
- PR
Relates to #1235

Fix github action contains expression

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/services/stake_distribution.rs
mithril-aggregator/src/services/ticker.rs
mithril-aggregator/src/tools/mocks.rs
mithril-aggregator/src/tools/mod.rs
mithril-client-cli/Cargo.toml
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-common/src/chain_observer/interface.rs
mithril-common/src/chain_observer/mod.rs
mithril-common/src/digesters/cache/json_provider_builder.rs
mithril-common/src/test_utils/mod.rs
mithril-common/src/test_utils/test_http_server.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/signer_services.rs

This PR reworks `mithril-common` dependencies:
- Move the `APISpec` and the `TestHttpServer` behind features, allowing to make several common dependencies optional (`glob`, `http`, `jsonschema` and `warp`).
- Remove mockall from the dependencies (now used only internally as a dev-dependency).
- Limit tokio features to just what's actually used: from `full` to `fs`, `io-util`, `process`, `rt`, and `sync` for main dependencies + `macros` and `time` for dev-dependencies.
- Remove `slog-scope`: as it's should only be used for binaries, libraries should be able to set their logger freely.
- Branch
- PR
Less dependency tree for common will simplify wasm adaptation for the client-lib.

Simplify common deps

---

Cargo.lock
docs/runbook/recompute-certificates-hash/README.md
docs/runbook/recompute-certificates-hash/config/tools.json
docs/runbook/terraform-lock/README.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/tools/certificates_hash_migrator.rs

- a fix to the aggregator tool that re-computes certificates hashes (and allows some hashes to remain unchanged, e.g. for genesis certificate)
- an updated and more robust process for the re-computation of the hashes of the certificates
- a fix of a typo in the terraform lock runbook
- Branch
- PR
Closes #1343

Fix certificate hashes re-computation in aggregator

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/serve_command.rs
mithril-aggregator/src/dependency_injection/builder.rs

This PR includes fixes to enhance Aggregator node REST API performances.
- Branch
- PR
Regarding SQLite optimization, the following documentations have been found useful:
* [SQLite documentation](https://www.sqlite.org/pragma.html#pragma_optimize)
* [SQLite Pragma Cheatsheet for Performance and Consistency](https://cj.rs/blog/sqlite-pragma-cheatsheet-for-performance-and-consistency/)
Relates to #1327

enhance Aggregator REST API performances

---

.github/workflows/actions/publish-crate-package/action.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
Cargo.lock
docs/website/root/manual/developer-docs/nodes/mithril-client-library.md
mithril-client/Cargo.toml
mithril-client/Makefile
mithril-client/src/client.rs
mithril-client/src/lib.rs
mithril-client/src/message.rs
mithril-client/src/snapshot_client.rs
mithril-client/src/utils/mod.rs
mithril-client/tests/extensions/fake.rs

This PR gates the snapshot download and snapshot message computation of the mithril-client library behind a `fs` feature. 
This feature is disabled by default because it simpler to enable a feature than to disable a default feature.
The doc is updated to add "Available on **crate feature fs** only" labels, ie:
But for those labels to show we need to trick cargo since [this features is still unstable](https://doc.rust-lang.org/unstable-book/language-features/doc-cfg.html).
For that we took inspiration from tokio, a major crate that use this feature, cf their [main toml](https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml#L157) (for how to trick doc rs to add a rustc flag that will be used to enable the feature) and their [dedicated doc …

Mithril-client-lib: Gate snapshot download & message computation behind a feature

---

Cargo.lock
mithril-relay/Cargo.toml
mithril-relay/src/lib.rs
mithril-relay/src/p2p/error.rs
mithril-relay/src/p2p/peer.rs

This PR includes some fixes for the **Mithril relay** Rust documentation.
> [!NOTE]
> This PR has been created from a fork
- Branch
- PR

Fix Mithril relay Rust doc

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/main.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/state_machine.rs
mithril-signer/tests/era_switch.rs
mithril-signer/tests/state_machine.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR includes an update of the `mithril-signer` node. There is now a goodbye message when the node terminates with no error.
This mechanism handles SIGTERM, SIGQUIT signals and Ctrl+C interrupts.
- Branch
- PR
Relates to #1312

Add goodbye message for signer node

---

.github/workflows/test-deploy.yml

This PR includes a fix to the protocol parameters of the `dev-preview` network (previous would have never allowed siging).
- Branch
- PR
Relates to #1361

Fix `dev-preview` network protocol parameters

---

.github/workflows/release.yml

This PR includes for missing credentials for crates.io publication in the `release.yml` workflow.
- Branch
- PR

Fix crates.io release credentials

---

.github/workflows/actions/publish-crate-package/action.yml
Cargo.lock
mithril-common/Cargo.toml
mithril-common/build.rs

This PR includes a fix to the process to publish `mithril-common` on crates.io: the OpenAPI specs file must be published with the package on crates.io so that the build script that computes available API versions.
- Branch
- PR

Fix `mithril-common` publication on crates.io

---

.github/workflows/ci.yml
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/mod.rs
mithril-client-cli/Cargo.toml
mithril-client-cli/src/main.rs
mithril-relay/Cargo.toml
mithril-relay/src/main.rs
mithril-signer/Cargo.toml
mithril-signer/src/main.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/README.md
mithril-test-lab/mithril-end-to-end/src/main.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/entities.rs

This PR includes a fix for log levels problems that was raised in the issue #1325.
This consists of: 
- correctly adjust verbosity according to verbosity level (`-v`, `-vv`, `-vvv`)
- display `critical` level logs when parameter is absent
Changes have been implemented into:
- `mithril-client-cli`
- `mithril-aggregator`
- `mithril-signer`
- `mithril-relay`
- `mithril-test-lab` (`mithril-end-to-end` & `stress-test`)
- Branch
- PR
Log level management has been added to the `mithril-end-to-end`, as it wasn't already included.
Closes #1325

Fix verbosity log levels

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/aggregator_client.rs
mithril-signer/src/lib.rs
mithril-signer/src/runtime/signer_services.rs

This PR includes an update to the `AggregatorHTTPClient` in the signer node which adds a 15 seconds timeout for HTTP requests.
- Branch
- PR
Closes #1312

Add timeout on signer node HTTP requests

---

Cargo.lock
mithril-common/Cargo.toml

This PR adds the `full` feature to `mithril-common` so that it does not break the CI with publication to crates.io checks.
> [!NOTE]
> The `full` feature does nothing at the moment, and will be activated in PR #1368 
- Branch
- PR
Relates to #1336

Add `full` feature to `mithril-common`

---

Cargo.lock
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-common/src/chain_observer/mod.rs

This PR removes unused dependencies from the `mithril-common` crate when called in the `mithril-client` crate.
- Branch
- PR
Closes #1390

Fix `mithril-client` dependencies

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/mithril_stake_distribution/list.rs
mithril-client-cli/src/commands/snapshot/list.rs
mithril-client-cli/src/commands/snapshot/show.rs

This PR includes a fix on a breaking change introduced by the PR #1395.
Some commands of `mithril-client-cli` (`snapshot show`, `snapshot list` and `msd list`) don't need to a `genesis_verification_key` configured to be runned.
Now that `mithril-client-cli` uses the `mithril-client-cli` that needs a `genesis_verification_key` to build a `Client`, we have to provide a value, even for commands that don't need it.
- Branch
- PR

Fix breaking change introduced with `mithril-client-cli` using `mithril-client` library

---

.github/workflows/ci.yml

This PR includes an optimization of the CI pipeline:
- External contribution from forks are now tested for network deployment when a PR is cretaed on the main repository.
- Forks will not have the toggle activated by default, thus will not run the testing for network deployment (in particular when the fork is synchronized).
- Branch
- PR

Add toggle for network deployment in CI

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/migration.rs
mithril-aggregator/src/database/provider/open_message.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/dependency_injection/containers.rs
mithril-aggregator/src/entities/open_message.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-aggregator/src/services/certifier.rs
mithril-aggregator/tests/open_message_expiration.rs
mithril-aggregator/tests/open_message_newer_exists.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/Cargo.toml
mithril-common/src/entities/signed_entity_type.rs

This PR includes a mechanism that associates a timeout (or not) to any signed entity type. When an open message is opened for longer than its timeout (if exists), the open message is discarded and thus allows for handling the next open message.
Open message timeouts:
| Signed Entity Type | Timeout |
| --- |:---:|
| `MithrilStakeDistribution` | - |
| `CardanoStakeDistribution` | 600s |
| `CardanoImmutableFilesFull` | - |
- Branch
- PR
Closes #1387

Implement `open_message` timeout in aggregator

---

Cargo.lock
docs/website/root/manual/developer-docs/nodes/mithril-client.md
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/snapshot/download.rs
mithril-client-cli/src/main.rs
mithril-client-cli/src/utils/progress_reporter.rs

This PR includes an update of `mithril-client-cli`.
- Fix the case inconsistency issue (use only snake case now).
- Fix a formatting problem with `seconds_left` and `seconds_elapsed` ("5s" and "001ms" was formatted as "5.1" in logs, instead of "5.001").
- Add `timestamp` in JSON progress logs.
- Add `--log-format-json` argument in `mithril-client-cli` commands, which displays `slog` logs in json format.
- Add `--log-output` argument in `mithril-client-cli` commands to redirect the `slog` logs to a file.
> [!IMPORTANT]  
> This PR includes impacting modifications `mithril-client-cli`. JSON progress logs were modified:
> -  `bytesDownloaded` is now `bytes_downloaded`
> -  `bytesTotal` is now `bytes_total`
> -  `secondsLeft` is now `seconds_left`
> -  `secondsElapsed` is now …

Enhance machine readable logs in client

---

.github/workflows/ci.yml

This PR includes an optimization of the CI pipeline:
- Forks will not have the toggle activated by default and will not attempt to create an unstable release when fork is synchronized.
- Branch
- PR

Add toggle for unstable release publication in CI

---

.github/workflows/ci.yml

This PR includes a fix to the toggle for unstable release publication in CI , which was always deactivated.
- Branch
- PR

Fix toggle for unstable release publication in CI

---

docs/website/blog/2024-01-03-signer-service-new-configuration.md

This PR includes an update of the blog post published in the PR #1419.
- Branch
- PR
Relates to #1404

Update new signer configuration blog post

---

.github/workflows/ci.yml

This PR includes an update of `ci.yml`. 
As the contents of `docs.yml` have been moved to `ci.yml` with the merge of the PR #1426, the paths-ignore filter must be removed.
- Branch
- PR
Relates to #1409

Update `ci.yml` after the deletion of `doc.yml`

---

docs/website/root/manual/getting-started/SPO-on-boarding-guide.md
docs/website/versioned_docs/version-maintained/manual/getting-started/SPO-on-boarding-guide.md

This PR removes the contact form from the documentation website.
- Branch
- PR

Remove contact form in the documentation website

---

.github/workflows/ci.yml
Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/mithril_stake_distribution/download.rs
mithril-client-cli/src/commands/mithril_stake_distribution/list.rs
mithril-client-cli/src/commands/snapshot/download.rs
mithril-client-cli/src/commands/snapshot/list.rs
mithril-client-cli/src/commands/snapshot/show.rs
mithril-client-cli/src/configuration.rs
mithril-client-cli/src/lib.rs
mithril-client-cli/src/main.rs
mithril-client-cli/src/utils/expander.rs
mithril-client-cli/src/utils/feedback_receiver.rs
mithril-client-cli/src/utils/mod.rs
mithril-client-cli/src/utils/progress_reporter.rs
mithril-client-cli/src/utils/snapshot.rs
mithril-client-cli/src/utils/unpacker.rs

This PR reinstate the `#![warn(missing_docs)]` directive on the Mithril Client Cli. It was removed by error when refactoring the cli to use the new client library (#1395).
Going further the `command` module is now declared in the `lib.rs` instead of the main, like all our other projects (this change was done when we were working on the first mithril library that still had both lib and cli in order to remove the lib only code from the library api).
This PR also fix the issue of [our self-hosted client library documentation](https://mithril.network/rust-doc/mithril_client/index.html) that is overwritten by the cli bin doc.
- Branch
- PR
Closes #1439

Warn missing docs directive missing in Mithril Client Cli

---

.github/workflows/ci.yml
Cargo.lock
mithril-client-wasm/Cargo.toml
mithril-client-wasm/Makefile
mithril-client-wasm/src/client_wasm.rs
mithril-client-wasm/src/lib.rs

This PR includes tests for `mithril-client-wasm`.
- The Makefile was updated to start a `mithril-aggregator-fake` when the command `make test` is executed.
- A job was added in the CI to start a `mithril-aggregator-fake` before running the tests.
- Tests in `mithril-client-wasm` were updated with the default values of `mithril-aggregator-fake`
- Branch
- PR
Closes #1407

Implement fake aggregator in wasm tests

---

.github/workflows/actions/publish-npm-package/action.yml

This PR includes a fix for authenticating to the `npm` registry in the CI/CD.
- Branch
- PR

Fix `npm` authentication to registry in CI

---

.github/workflows/pre-release.yml

This is a tentative fix to avoid 403 errors when the tag is not the head of any branchs.
- Branch
- PR

Specify explicitly permissions for prerelease creation

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_transactions.rs
mithril-aggregator/src/services/signed_entity.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/merkle_tree.rs
mithril-common/src/crypto_helper/mod.rs
mithril-common/src/entities/cardano_transaction.rs
mithril-common/src/entities/cardano_transactions_commitment.rs
mithril-common/src/entities/signed_entity.rs
mithril-common/src/signable_builder/cardano_transactions.rs

- Computation of the Merkle tree of the Cardano transactions set and the associated Merkle root 
- Use the Merkle root as a protocol message part to be signed in the signer and aggregator
- Branch
- PR
Closes #1436

Compute message to sign for Cardano transactions

---

flake.nix

This PR includes a fix in the `nix flake` CI builds to make test data available.
The missing test data created these errors (as in this [job](https://ci.iog.io/build/2574301/nixlog/6)):
```
failures:
---- cardano_transaction_parser::tests::test_parse_up_to_given_beacon stdout ----
thread 'cardano_transaction_parser::tests::test_parse_up_to_given_beacon' panicked at mithril-common/src/cardano_transaction_parser.rs:249:9:
assertion failed: get_number_of_immutable_chunk_in_dir(db_path) >= 2
---- cardano_transaction_parser::tests::test_parse_expected_number_of_transactions stdout ----
thread 'cardano_transaction_parser::tests::test_parse_expected_number_of_transactions' panicked at mithril-common/src/cardano_transaction_parser.rs:227:9:
assertion failed: …
```

Fix missing test data in nix flake build

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/Makefile
mithril-common/src/chain_observer/builder.rs
mithril-common/src/chain_observer/mod.rs
mithril-common/src/crypto_helper/cardano/cold_key.rs
mithril-common/src/crypto_helper/cardano/mod.rs
mithril-common/src/crypto_helper/era.rs
mithril-common/src/crypto_helper/mod.rs
mithril-common/src/entities/signed_entity.rs
mithril-common/src/lib.rs
mithril-common/src/messages/certificate.rs
mithril-common/src/messages/message_parts/signer.rs
mithril-common/src/messages/mithril_stake_distribution.rs
mithril-common/src/messages/register_signature.rs
mithril-common/src/messages/register_signer.rs

This PR fix the building of mithril-common for all it's matrix of features and targets.
Some examples that raise errors right now:
- building with only the `test_tools` features fails because it's need the `ColdKeyGenerator` that's behind the `random` feature.
- building with only the `--all-targets` directive fails horribly (30 errors) because the tests use a lot of tools that are behind the `test_tools` feature.
- building it with only the `fs` and `random` features would fails since the `FakeObserver` is behind the `test_tools` feature that is disabled.
- Branch
- PR
In order to check more easily if a feature combinatory is failing a new target has been added to the mithril-common makefiles that compute all features combinatory (the "powerset" of features) and run a cargo clippy on …

Fix building mithril-common with some features and targets combinatory

---

.github/workflows/ci.yml

This PR includes a fix to the naming of failed artifacts in the end to end CI.
- Branch
- PR

Failed end to end tests artifact names

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/digesters/immutable_file.rs

This PR enhance the immutable files listing, making it more resilient:
- Instead of simply skipping the last three files to remove an incomplete trio, it skip the file(s) with the highest number (meaning that if for example the "secondary" file is missing from the "99" trio this won't remove a file from the "98" trio).
- The condition to be recognize as an immutable is not only being in a "immutable" folder but also to have one of the following file extension: "chunk", "primary", "secondary".
- If will first search for the "immutable" folder and won't walk in its subfolder in search for immutables.
- **_This point needs to be discussed_** It will fails if it can't find a "immutable" folder instead of returning an empty list.
- Branch
- PR
Closes #1450

List immutables resilience

---

.github/workflows/scripts/parse-wasm-headless-tests-results.sh
.github/workflows/scripts/run-wasm-tests-browser-headless.py
.github/workflows/test-client.yml
mithril-client-wasm/Makefile
mithril-client-wasm/www-test/.gitignore
mithril-client-wasm/www-test/README.md
mithril-client-wasm/www-test/bootstrap.js
mithril-client-wasm/www-test/index.html
mithril-client-wasm/www-test/index.js
mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www-test/webpack.config.js

This PR includes tests implementation for `mithril-client-wasm`. This tests are executed in headless mode with Google Chrome and Firefox from the manual workflow `Mithril Client multi-platform test`.
Two scripts were added:
- `run-wasm-tests-browser-headless.py`: call by the manual workflow to run browsers in headless mode and save the output to a html file with the test results. It takes the browser as argument (`chrome` or `firefox`).
- `parse-wasm-headless-tests-results.sh`: call by the manual workflow to handle both browsers test results
- Branch
- PR
Close to #1408

Add `mithril-client-wasm` tests in multi platform test

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/signed_entity.rs
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_transaction.rs
mithril-aggregator/src/http_server/routes/artifact_routes/mithril_stake_distribution.rs
mithril-aggregator/src/http_server/routes/artifact_routes/mod.rs
mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/message_adapters/mod.rs
mithril-aggregator/src/message_adapters/to_cardano_transaction_list_message.rs
mithril-aggregator/src/message_adapters/to_cardano_transaction_message.rs
mithril-aggregator/src/services/message.rs
mithril-common/Cargo.toml
mithril-common/src/entities/cardano_transactions_commitment.rs
mithril-common/src/messages/cardano_transaction.rs
mithril-common/src/messages/cardano_transaction_list.rs
mithril-common/src/messages/mod.rs
mithril-common/src/test_utils/fake_data.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/assertions/check.rs
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
openapi.yaml

This PR includes the new routes in the aggregator REST API which give access to the `CardanoTransactions` artifacts.
- Branch
- PR
Closes #1478

Implement `CardanoTransactions` artifact routes in aggregator

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/cardano_transaction.rs
mithril-aggregator/src/http_server/routes/mod.rs
mithril-aggregator/src/http_server/routes/proof_routes.rs
mithril-aggregator/src/message_adapters/to_cardano_transactions_proof_message.rs
mithril-aggregator/src/services/prover.rs
mithril-aggregator/src/services/signed_entity.rs
mithril-aggregator/tests/open_message_expiration.rs
mithril-aggregator/tests/open_message_newer_exists.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/types/wrappers.rs
mithril-common/src/entities/cardano_transactions_set_proof.rs
mithril-common/src/messages/cardano_transactions_proof.rs
mithril-common/src/messages/message_parts/cardano_transactions_set_proof.rs
mithril-common/src/messages/message_parts/mod.rs
openapi.yaml

This PR modify the `/proof/cardano-transaction` endpoint so it returns the certificate hash on which the proof merkle root relates to.
This also means that the `ProverService::compute_transactions_proofs` (and the repository behind it) now limit the set of transactions that's they works on. This in order to only works on what have been certified else they could work on transactions that are not in a certificate yet (typically the aggregator is waiting for single signatures).
- Branch
- PR
Relates to #1468

Certificate hash in transaction set message

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/utils/unpacker.rs

This PR makes error message when unpacking a snapshot and the `db/` directory is unwritable a bit more explicit and provides some guidance to the user.
- Branch
- PR

More explicit error message when db dir is not writable

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/chain_observer/cli_observer.rs
mithril-common/src/signable_builder/mod.rs
mithril-stm/Cargo.toml
mithril-stm/src/merkle_tree.rs

This PR fix the clippy lints that are raised from the latest rust version (1.76)
- Branch
- PR

Fix clippy lint from rust 1.76

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/chain_observer/mod.rs
mithril-common/src/chain_observer/model.rs
mithril-common/src/lib.rs

This PR fix the clippy warning that can be seen in some [CI jobs](https://github.com/input-output-hk/mithril/actions/runs/7889979563/job/21532181108) : 
```shell
Run cargo build --lib --release --package mithril-stm --package mithril-client --features full,unstable 
Compiling mithril-common v0.3.2+80ee079 (/home/runner/work/mithril/mithril/mithril-common)
Compiling mithril-stm v0.3.15+80ee079 (/home/runner/work/mithril/mithril/mithril-stm)
warning: function `try_inspect` is never used
--> mithril-common/src/chain_observer/model.rs:33:12
|
33 |     pub fn try_inspect<R>(inner: Vec<u8>) -> StdResult<R>
|            ^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: type alias `Datums` is never used
--> mithril-common/src/chain_observer/model.rs:46:14
|
46 |     pub type …
```

Fix clippy warning in common when using only `fs` flag

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/snapshot/download.rs

This PR includes a regression after the merge of the PR #1395 related to the `snapshot download` command of `mithril-client-cli`.
The unpack directory was no longer removed when the certificate signed message and computed message did not match.
- Branch
- PR

Mithril client CLI: fix remove archive directory

---

.github/workflows/actions/build-upload-mithril-artifact/action.yml
.github/workflows/actions/deploy-terraform-infrastructure/action.yml
.github/workflows/ci.yml
.github/workflows/manual-publish-crates.yml
.github/workflows/manual-publish-npm.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/test-client.yml
.github/workflows/test-deploy-network.yml
.github/workflows/test-docker-distribution.yml

This PR upgrades the versions of the actions we use in the CI, this should solve most "upgrade to node 20" warnings.
- Branch
- PR
Relates to #1520

CI: Upgrade actions

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml

This PR fix a regression in our CI workflows introduced by #1521 : the `tubone24/update_release` don't support import by giving only the major version.
- Branch
- PR
Relates to #1520

Fix `update_release` action version in CI

---

.github/workflows/test-client.yml
mithril-client-wasm/www-test/index.js

This PR includes update to the GitHub Actions workflow `Mithril Client multi-platform test` to support testing for Cardano transactions.
- Implementation of a conditional step to certify Cardano transactions if the aggregator capability is enabled.
- Fix function names in `mithril-client-wasm/www-test/index.js` to ensure consistency in test naming.
Run on `testing-sanchonet` with Cardano transaction signing capability:
https://github.com/input-output-hk/mithril/actions/runs/8020577209
Run on `testing-preview` without Cardano transaction signing capability:
https://github.com/input-output-hk/mithril/actions/runs/8020604356
- Branch
- PR
Closes #1510

Adapt multi platform test for Cardano transactions

---

docs/website/blog/2024-02-26-mithril-client-cli-output-breaking-change.md

This PR includes a new blog post for the update of `mithril-client-cli` output.
- Branch
- PR

Add dev blog post for `mithril-client-cli` output update

---

docs/website/root/manual/getting-started/run-signer-node.md

This PR includes a new **Mihtril signer footprint** in the [SPO setup guide](https://mithril.network/doc/manual/getting-started/run-signer-node)
- Branch
- PR
Closes #1519

Document Mithril signer footprint in SPO Setup guide

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/metrics/mod.rs

This PR includes the fix of a typo in the name of the signature related metrics in the signer.
- Branch
- PR
Grafana dashboard need to be updated on the `testing-preview` and `testing-sanchonet` networks
Relates to #1096

Fix signature related metrics name in signer

---

.github/workflows/actions/publish-npm-package/action.yml

This PR includes an update of the `publish-wasm-package` workflow.
A new step has been added to manage the promote to the `latest` tag on the npm package version when a new distribution is released.
- Branch
- PR
Closes #1531

Add new npm package step dedicated to release process (`latest` tag)

---

Cargo.lock
docs/website/adr/002-use-structured-logging.md
docs/website/adr/003-release/index.md
docs/website/adr/004-mithril-network-update-strategy.md
docs/website/adr/006-errors-implementation.md
docs/website/adr/007-standardize-log-output.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/mod.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/main.rs

This PR includes an update of `mithril-aggregator` logs output.
Following the type of command (`Server` and `CommandLine`), aggregator logs won't be send in the same output.
- Server (`serve` command) -> `stdout`
- Command line (`genesis`, `era`, `tools`) -> `stderr`
A new ADR has been aded to describe this behavior.
- Branch
- PR
Closes #1515

Send aggregator logs in the right output (`stdout` / `stderr`)

---

mithril-client-wasm/www/index.js
mithril-client-wasm/www/package.json

This PR includes an update of the Javascript implementation that calls the `mithril-client-wasm` library.
It improves the way results are displayed and tests with more convincing data.
- Branch
- PR
Closes #1552

Enhance Cardano transaction part in `mithril-client-wasm/www`

---

docs/website/root/manual/getting-started/run-signer-node.md
docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md

This PR includes a fix to the minimum recommended version of `Squid` to `6.8+` in the [Run a Mithril signer as an SPO](https://mithril.network/doc/manual/getting-started/run-signer-node)
- Branch
- PR

Fix minimum `Squid` version in SPO guide

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db/download.rs
mithril-client-cli/src/utils/cardano_db.rs
mithril-client-cli/src/utils/cardano_db_download_checker.rs
mithril-client-cli/src/utils/mod.rs
mithril-client-cli/src/utils/unpacker.rs

This PR changes the checks that are done for the `cardano-db download` commands:
The `db` directory inside the `download_dir` can now exist beforehand, but it still required to be empty. As before if it doesn't exist it will be created.
- Branch
- PR
Relates to #1572, alternatives to #1573

Accept existing but empty `db` dir for `client-cli` cardano-db download

---

SECURITY.md

This is an adapted copy from the [Hydra project](https://github.com/input-output-hk/hydra/blob/master/SECURITY.md) which also points to Github security vulnerability disclosure mechanism instead of the security@iohk.io email address.

Establish a more explicit security policy

---

.github/workflows/actions/publish-npm-package/action.yml

This PR fixes the npm publication workflow release
- Branch
- PR
Closes 1595

Fix variable substitution in npm publication workflow release

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/chain_observer/cli_observer.rs
mithril-common/src/chain_observer/pallas_observer.rs
mithril-common/src/crypto_helper/cardano/opcert.rs
mithril-common/src/crypto_helper/codec.rs

This PR includes the update of crate `bech32` to version `0.11.0` which introduced some breaking change in the API.
- Branch
- PR

Upgrade `bech32` crate

---

docs/runbook/recompute-certificates-hash/README.md
docs/runbook/recompute-certificates-hash/config/tools.json

This PR includes a fix to the runbook for [certificate hashes re-computation](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/recompute-certificates-hash)
- Branch
- PR

Fix runbook for certificate hashes re-computation

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/migration.rs

This PR includes a new migration for the aggregator node database.
The migration creates indexes on foreign keys columns.
- Branch
- PR
Indexes are named `tablecolumn_index` to avoid conflicts when columns have the same name in different tables.
Closes #1603

New migration to add indexes on foreign keys

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/metrics/server.rs

This PR includes a fix to prevent the `MetricsServer: shutting down HTTP server after receiving signal`  log to be displayed on the signer even when no signal has been caught (i.e. the metrics server is still operating correctly).
- Branch
- PR
Closes #1620

Fix signer metrics server caught signal log

---

.github/workflows/ci.yml

This PR includes an upgrade of the `testing-preview` VM from `e2-standard-8` to `e2-highmem-8`.
This will help avoid reaching memory limit which has occurred since the activation of the Cardano transactions signature on the network.
- Branch
- PR
Relates to #1591

Upgrade `testing-preview` VM

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/tools/mocks.rs
mithril-common/Cargo.toml
mithril-common/src/chain_observer/cli_observer.rs
mithril-common/src/chain_observer/fake_observer.rs
mithril-common/src/chain_observer/interface.rs
mithril-common/src/chain_observer/pallas_observer.rs
mithril-common/src/chain_observer/test_cli_runner.rs
mithril-common/src/entities/block_range.rs
mithril-common/src/entities/cardano_chain_point.rs
mithril-common/src/entities/cardano_transaction.rs
mithril-common/src/entities/mod.rs
mithril-common/src/test_utils/fake_data.rs
mithril-common/src/time_point_provider.rs

This PR includes the support for the chain observers of the retrieval of the current Cardano chain point:
- Upgraded `ChainObserver` trait.
- Upgraded `FakeChainObserver` and mocks implementations.
- Upgraded `CardanoCliObserver` implementation.
- Prepared `PallasChainObserver` implementation (not implemented yet).
- Branch
- PR
The `PallasChainObserver` does not currently implement the `get_current_chain_point`. 
This will be done in a separate PR by @falcucci .
Relates to #1589

Chain observer retrieves the current Chain Point

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
demo/protocol-demo/Cargo.toml
mithril-aggregator/Cargo.toml
mithril-client-cli/Cargo.toml
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-signer/Cargo.toml
mithril-stm/CHANGELOG.md
mithril-stm/Cargo.toml
mithril-test-lab/mithril-end-to-end/Cargo.toml

This PR changes the `mithril-stm` dependencies in order to always enforce the `portable` features of [BLST](https://crates.io/crates/blst).
This enable a runtime check of the ADX instruction set instead of the compile time check that we used before, allowing users with older CPUs to use our compiled binaries instead of needing to compile them themselves.
Making this changes make the `mithril-stm` portable feature, and all equivalent features in all our crates, useless as it now do strictly nothing.
For compatibility purpose, since those crates are published to crates.io, the portable feature is kept on `mithril-stm` and `mithril-client` but is removed on the other crates (the CI have been adapted for this change).
We should communicate this change to advertise users that depends on our …

Use BLST portable feature to enable runtime ADX instruction set check

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db/download.rs
mithril-client-cli/src/commands/cardano_db/list.rs
mithril-client-cli/src/commands/cardano_db/mod.rs
mithril-client-cli/src/commands/cardano_db/show.rs
mithril-client-cli/src/main.rs

This PR outputs client deprecation warning formatted in JSON when the --json option is used
With --json option, the output is:
`` {"warning": "`snapshot` command is deprecated, use `cardano-db` instead", "type": "deprecation"} ``
without the option, the output is:
`` `snapshot` command is deprecated, use `cardano-db` instead ``
- Branch
- PR
Closes #1616

fix: Output deprecation warning in JSON format when option --json is set

---

.github/workflows/test-deploy-network.yml
.github/workflows/test-docker-distribution.yml
mithril-infra/variables.tf

This PR includes the activation of the `testing-mainnet` development network and its manual deployment in GitHub Actions workflow.
- Branch
- PR
Closes #1617

Deploy `testing-mainnet` network

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/Makefile
mithril-client-cli/Cargo.toml
mithril-client-cli/Makefile
mithril-client/Cargo.toml
mithril-client/Makefile
mithril-common/Cargo.toml
mithril-common/Makefile
mithril-signer/Cargo.toml
mithril-signer/Makefile

This PR includes removal of remaining `portable` feature usage in make commands.
- Branch
- PR

Remove 'portable' feature in make commands

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/provider/cardano_transaction/get_cardano_transaction.rs
mithril-aggregator/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/src/services/prover.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/merkle_map.rs
mithril-common/src/digesters/cardano_immutable_digester.rs
mithril-common/src/signable_builder/cardano_immutable_full_signable_builder.rs
mithril-common/src/signable_builder/cardano_transactions.rs
mithril-common/src/test_utils/mod.rs

This PR do some memory usage enhancement when computing a proof of Cardano transactions. Nothing ground breaking but this should reduce somehow the maximum memory needed for this operation.
- It mostly reduce the number of copy of the full transactions set retrieved from database needed to compute the merkle tree used for proof generation.
- It also separate the retrieval of the transactions to prove from the retrieval of the full transactions set (before we walked through the later to find the former).
- Branch
- PR
Relates to #1629

Proof generation memory optimisation

---

.github/workflows/ci.yml
cardano-min-versions.json
docs/runbook/README.md
docs/runbook/maintain-cardano-min-versions-file/README.md
docs/website/root/manual/getting-started/run-signer-node.md
networks.json

This PR includes a new file `networks.json` at the root of the repository.
It contains the list of the minimum supported Cardano node versions for each network.
- Branch
- PR
Closes #1615

Minimum supported Cardano node versions for Mithril signers

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/tests/open_message_expiration.rs

This PR includes fixes for:
- `get_current_non_certified_open_message`: the `open_message.is_expired` condition was never verified.
- `list_allowed_signed_entity_types_discriminants`: if the same valid `signed_entity_types` was provided several times in the configuration, it was nevertheless added (filter was only on default `signed_entity_types`).
In addition, we also refactored the UT in the aggregator `runner` and `configuration`.
- Branch
- PR

Fix `open_message.is_expired` in aggregator runner

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/lib.rs
mithril-signer/Cargo.toml
mithril-signer/src/lib.rs

This PR includes the activation of a different memory allocator `jemallocator` through a feature. This will likely avoid having memory fragmentation resulting in resident memory of signer/aggregator not being correctly released when signing/proving Cardano transactions.
See https://github.com/input-output-hk/mithril/issues/1629#issuecomment-2069016167 for details.
- Branch
- PR
Closes #1629

Use new memory allocator 'jemallocator'

---

.github/workflows/aggregator-stress-test.yml

This PR includes a new Github workflow for the aggregator stress test.
It makes it easy (triggered manually) to run stress tests on the aggregator by specifying the number of concurrent signers and clients.
- Branch
- PR

Add aggregator stress test workflow

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-signer/Cargo.toml
mithril-signer/src/cardano_transactions_importer.rs

This PR includes an optimization on the computation of the block range roots so that there is a limited accumulation of the computed root before they are stored in the database (in particular to avoid the error `variable number must be between ?1 and ?32766` from SQLite).
- Branch
- PR
Relates to #1633

Optimize block range roots computation

---

.github/workflows/aggregator-stress-test.yml

This PR includes a fix for the aggregator stress test github workflow.
The aggregation node binary required to run the stress test was missing.
- Branch
- PR

Fix missing `mithril-aggregator` binary in the `stress-test` job

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/configuration.rs
mithril-common/Cargo.toml
mithril-common/src/entities/signed_entity_type.rs

This PR enforce an order implementation for the signed entity type discriminant.
The order is defined as the following:
>  MithrilStakeDistribution < CardanoStakeDistribution < CardanoImmutableFilesFull < CardanoTransactions
This order was already correctly implement using a simple derive Ord with the work on #1496 (to allow the `capabilities` field of the aggregator root endpoint to use a BTreeSet).
This PR:
-  add tests to ensure that the defined order is the one defined above doesn't change by mistake by, for example, reordering the signed entity enum variants.
- change aggregator `Configuration::list_allowed_signed_entity_types_discriminants` return type to a BTreeSet for automatic order based on the type and automatic de-duplication. This simplify a bit the open message generation …

Ord on signed entity type discriminants

---

CHANGELOG.md

This PR includes the rotation of the `CHANGELOG` file following the release of the [`2418.1`](https://github.com/input-output-hk/mithril/releases/tag/2418.1) distribution.
- Branch
- PR
Relates to #1614

Update CHANGELOG with `2418.1` distribution release

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/benches/cardano_transactions_get.rs
mithril-aggregator/src/database/cardano_transaction_migration.rs
mithril-aggregator/src/database/provider/cardano_transaction/get_cardano_transaction.rs
mithril-aggregator/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-signer/Cargo.toml
mithril-signer/src/cardano_transactions_importer.rs
mithril-signer/src/database/cardano_transaction_migration.rs
mithril-signer/src/database/provider/block_range_root/get_block_range_root.rs
mithril-signer/src/database/provider/cardano_transaction/get_cardano_transaction.rs
mithril-signer/src/database/repository/cardano_transaction_repository.rs

This PR changes the order of retrieval of the Cardano transactions from the database.
Before we used SQLite `rowid` but this order isn't guaranteed to be consistent across node since it depends on the order of insertion in the database.
To solve this issue this PR change the order to the use the transaction `block_number` then its `transaction_hash`.
An composite index on those columns is added to ensure a fast retrieval, plus a benchmark is added to measure the retrieval performances. 
- Branch
- PR
Closes #1657

Consistent transactions sort

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/utils/progress_reporter.rs

ProgressBar calculates elapsed time and left time using function `now`. 
Even we set ProgressBar with hard coded values, we could never be sure what the json looks like.
Depending on the machines, the result may not be the same.
For testing, we create a format function that is not time dependent.
We create a second test which checks that we send the right parameters to the format function. 
It doesn't check the exact values but only if they are consistent. 
- Branch
- PR
Closes #1466

Stabilize test removing most of the time dependency

---

.github/workflows/aggregator-stress-test.yml
.github/workflows/ci.yml
mithril-test-lab/mithril-end-to-end/src/stress_test/aggregator_helpers.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/wait.rs

This PR includes a fix for the aggregator stress test.
Due to updates on the aggregator node, the bootstrap of the aggregator stress test was no longer working (e.g. [here](https://github.com/input-output-hk/mithril/actions/runs/8846364647/job/24292095762#step:8:153)).
To succeed, an additional step was required, involving a restart of the aggregator and to move one epoch forward before the signing registration.
The results of the Github workflow that the aggregator stress test with 500 signers and 500 clients can be found [here](https://github.com/input-output-hk/mithril/actions/runs/9109203593/job/25041569586#step:8:273).
- Branch
- PR
Closes #1676

Fix aggregator stress test

---

docs/website/root/manual/getting-started/run-signer-node.md
docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md

This PR includes some fix on the **Squid service** configuration of the [Run a Mithril signer as an SPO](https://mithril.network/doc/manual/getting-started/run-signer-node):
- Add command to stop the previously installed Squid service before building from source.
- Add debug logs to the service.
- Add tip with a fix when a `FATAL: /dev/null (13) Permission denied` error occurs at service startup.
- Branch
- PR

Fix `squid` service configuration in signer guide for SPO

---

CHANGELOG.md
Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/provider/cardano_transaction/delete_cardano_transaction.rs
internal/mithril-persistence/src/database/provider/cardano_transaction/mod.rs
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
internal/mithril-persistence/src/sqlite/connection_extensions.rs
internal/mithril-persistence/src/sqlite/mod.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/configuration.rs
mithril-signer/Cargo.toml
mithril-signer/src/aggregator_client.rs
mithril-signer/src/configuration.rs
mithril-signer/src/database/repository/cardano_transaction_repository.rs
mithril-signer/src/lib.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/src/transactions_importer_with_prune_decorator.rs
mithril-signer/src/transactions_importer_with_pruner.rs

This PR add, to the signer only, a pruning of the cardano transactions after the computation of block ranges roots.
This is done using a decorator wrapping the existing `CardanoTransactionsImporter`.
Two new configuration parameters have been added to signer `Configuration` structure:
- `network_security_parameter`, default to `2160` (mainnet value).
- `enable_transaction_pruning`, default to `true`.
Since both have a default value our signer won't have to update their configurations.
- Branch
- PR
- As it was the third time that we needed to do a simple query to retrieve a single result from database, a system using a  extension trait on the [sqlite connection](https://docs.rs/sqlite/0.36.0/sqlite/struct.ConnectionThreadSafe.html) has been added to do that simply with …

Prune cardano transactions in signer after block range roots computation

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/entities/signed_entity_type.rs

This PR includes a fix to extend the tiemeout of the **Cardano transaction** signed entity type from `600s` to `1800s`. This will avoid timeout on the `mainnet` when importing transactions from immutable files may take longer than expected which is responsible for the `testing-mainnet` unable to sign for few days.
- Branch
- PR
Relates to #1681

Fix Cardano transaction signed entity type timeout

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/prover.rs
mithril-common/Cargo.toml
mithril-common/src/signable_builder/cardano_transactions.rs
mithril-common/src/test_utils/cardano_transactions_builder.rs
mithril-common/src/test_utils/mod.rs

This PR adds the `CardanoTransactionsBuilder`, which aims to easily build transactions for test cases.
- Branch
- PR
Closes #1667

Create a test Cardano transactions builder

---

docs/website/root/manual/getting-started/bootstrap-cardano-node.md
docs/website/root/mithril/intro.md
docs/website/root/mithril/mithril-protocol/protocol.md
docs/website/versioned_docs/version-maintained/manual/getting-started/bootstrap-cardano-node.md
docs/website/versioned_docs/version-maintained/mithril/intro.md
docs/website/versioned_docs/version-maintained/mithril/mithril-protocol/protocol.md

This PR includes fixes of the [Bootstrap a Cardano node]()https://mithril.network/doc/manual/getting-started/bootstrap-cardano-node) guide in the documentation website:
- Fix Docker registry used to start a Cardano node
- Updated the performances of restoration to actual figures (`20 minutes` instead of `2 hours`)
- Removed the stale Daedalus restoration video presentation
- Added a tip with configuration values used in the restoration commands
- Simplified the long display when starting the Cardano node
- Also removed the **New** mentions in some information blocks
- Branch
- PR

Fix `Bootstrap a Cardano node` guide

---

.github/workflows/pre-release.yml

This PR includes an updated **Mithril network compatibility table** for **(pre)releases** which makes 'testing-preview' and 'testing-sanchonet' incompatible with the released version.
- Branch
- PR

Update network compatibility table for releases

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-common/Cargo.toml
mithril-common/src/cardano_block_scanner/block_scanner.rs
mithril-common/src/cardano_block_scanner/dumb_block_scanner.rs
mithril-common/src/cardano_block_scanner/immutable_block_streamer.rs
mithril-common/src/cardano_block_scanner/interface.rs
mithril-signer/Cargo.toml
mithril-signer/src/cardano_transactions_importer.rs

This PR includes a modification of the `BlockStreamer` trait to be able to handle rollbacks.
- Branch
- PR
Closes #1704

Update `BlockStreamer` return type 

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/tools/certificates_hash_migrator.rs
mithril-aggregator/tests/certificate_chain.rs
mithril-aggregator/tests/create_certificate.rs
mithril-aggregator/tests/era_checker.rs
mithril-aggregator/tests/genesis_to_signing.rs
mithril-aggregator/tests/open_message_expiration.rs
mithril-aggregator/tests/open_message_newer_exists.rs
mithril-common/Cargo.toml
mithril-common/src/cardano_block_scanner/interface.rs
mithril-common/src/chain_observer/fake_observer.rs
mithril-common/src/entities/cardano_chain_point.rs
mithril-common/src/entities/time_point.rs
mithril-common/src/test_utils/mod.rs
mithril-common/src/time_point_provider.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/src/runtime/state_machine.rs
mithril-signer/tests/test_extensions/certificate_handler.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR modify the `TimePoint` structure to add a `chain_point` property and update the `TimePointProvider` to retrieve it using `ChainObserver::get_current_chain_point`.
In order to keep the Ord capability of the `TimePoint`, Ord is added to `ChainPoint` as well.
- Branch
- PR
Relates to #1697

Add `chain_point` to `TimePoint` structure

---

.github/workflows/test-client.yml

This PR includes a fix for the manual workflow `Mithril Client multi-platform test` that removes command compatibility steps due to the removal of the `snapshot` command.
- Branch
- PR

Remove manual workflow step for old `snapshot` commands availability

---

Cargo.lock
examples/client-cardano-transaction/Cargo.toml
examples/client-cardano-transaction/src/main.rs
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/query/cardano_transaction/get_cardano_transaction.rs
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/src/services/prover.rs
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_transaction/certify.rs
mithril-client-wasm/Cargo.toml
mithril-client-wasm/www/index.js

This PR includes a fix to the **Cardano transactions prover** to avoid certifying transactions stored in the database, but not already certified. This was causing the error: `Proof and certificate don't match` when trying to verify this type of transactions instead of marking them as **not certified**.
| Total Requests | Concurrency | Transactions/Request | Pool (x50) : Request/s | Pool (x50) + Fix not yet certified transactions: Request/s |
| -------------- | ----------- | -------------------- | ---------------------- | ---------------------------------------------------------- |
| 1000           | 100         | 1                    | **273.78**                 | **275.95**                                                     |
| 1000           | 100         | 2                    | …

Fix: make prover not certify transactions stored but not certified yet

---

mithril-client-wasm/Makefile
mithril-client-wasm/www-test/Makefile
mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www/Makefile
mithril-client-wasm/www/package-lock.json
mithril-client-wasm/www/package.json

This PR includes two new `Makefile` for `www` and `www-test`.
It facilitates the update of the projects dependencies.
From `mithril-client-wasm` directory, run: `make upgrade-www-deps`
- Branch
- PR

Add `Makefiles` to facilitate the update of `www` and `www-test` dependencies

---

CHANGELOG.md
Cargo.lock
mithril-client/Cargo.toml

The `mithril-client` library uses the `reqwest` crate.  By default, `reqwest` uses `OpenSSL` for TLS support in HTTPS requests.  This causes any consumer of the library to have a dynamic dependency on a system OpenSSL library.
`reqwest` has a number of options for fulfilling `tls` functionality.  This patch just exposes that, using the same feature flags that `reqwest` uses.
- Branch
- PR
This PR came about because our project requires static linking of dependent libraries, and this was not possible when using the `mithril-client` crate.
Closes #1737

feat(tls): Allow the underlying TLS implementation to be selected by feature flags.

---

CHANGELOG.md

This PR includes the rotation of the `CHANGELOG` file following the release of the [`2423.0`](https://github.com/input-output-hk/mithril/releases/tag/2423.0) distribution.
- Branch
- PR
Relates to #1695

Update CHANGELOG with `2423.0` distribution release

---

demo/protocol-demo/README.md
docs/website/root/manual/developer-docs/nodes/mithril-aggregator.md
docs/website/root/manual/developer-docs/nodes/mithril-client-library.md
docs/website/root/manual/developer-docs/nodes/mithril-client.md
docs/website/root/manual/developer-docs/nodes/mithril-signer.md
docs/website/root/manual/getting-started/bootstrap-cardano-node.md
docs/website/root/manual/getting-started/run-mithril-devnet.md
docs/website/root/manual/getting-started/run-signer-node.md
mithril-relay/README.md
mithril-stm/README.md
mithril-test-lab/mithril-end-to-end/README.md

This PR includes the missing pre-requisites for building crates: 
- `build-essential` and `m4` tools were missing.
- Branch
- PR

docs: add missing pre-requisites for building crates

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/prover.rs
mithril-common/benches/merkle_map.rs
mithril-common/src/crypto_helper/merkle_map.rs
mithril-common/src/crypto_helper/merkle_tree.rs

This PR includes fix of some **bottlenecks identified in the proof generation** of the Merkle map:
- Fix bottleneck when Merkle map computes a proofs.
- Fix bottleneck when computing the list of certified items in a Mekle map proof.
- Refactor Merkle map benchmarks to make them more accurate.
| Total Requests | Concurrency | Transactions/Request | Pool (x50): Request/s | Pool (x50) + Optimization MKMap proof computation: Request/s |
| -------------- | ----------- | -------------------- | --------------------- | ------------------------------------------------------------ |
| 1000           | 100         | 1                    | **281.4**                 | **1403.97**                                                      |
| 1000           | 100         | 2                    | **192.84** …

Remove bottleneck in proof generation of Merkle map

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
internal/mithril-persistence/src/sqlite/connection_extensions.rs
internal/mithril-persistence/src/sqlite/mod.rs
internal/mithril-persistence/src/sqlite/transaction.rs

This PR add a light layer to easily open, commit, and rollback SQLite transactions.
This is done by adding a `Transaction` struct to `mithril-persistence` that:
- wrap a **borrowed** SQLite connection.
- define three public methods: `begin` (the constructor), `commit` and `rollback`.
- `commit` and `rollback` method move self, meaning that using either of them remove the transaction of the current scope: the compiler won't allow to use several `commit` or `rollback` on the same transaction.
- Implement `Drop` to automatically rollback the transaction when it goes out of scope if it was still active.
Also a `begin_transaction` extension method is added to the sqlite transaction so they can be created without needing to import the new type.
- Branch
- PR
While this system make using SQLite …

Sqlite auto rollback

---

docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-aggregator.md
docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-client-library.md
docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-client.md
docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-signer.md
docs/website/versioned_docs/version-maintained/manual/getting-started/bootstrap-cardano-node.md
docs/website/versioned_docs/version-maintained/manual/getting-started/run-mithril-devnet.md
docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md

This PR includes the rotation of the documentation with the release of the new `2423` distribution
- Branch
- PR
Relates to #1695

Rotate documentation for `2423` distribution

---

CHANGELOG.md

This PR includes the rotation of the `CHANGELOG` file following the release of the [`2423.0`](https://github.com/input-output-hk/mithril/releases/tag/2423.0) distribution.
- Branch
- PR
Relates to #1695

Update CHANGELOG with `2423.0` distribution release 

---

docs/website/blog/2024-06-12-client-cli-removed-command.md

This PR includes a new **dev blog post** about the **removed `snapshot` command** from the Mithril client CLI.
- Branch
- PR
Relates to #1695

Dev blog post for removed `snapshot` command in client CLI

---

CHANGELOG.md
Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/merkle_map.rs
mithril-common/src/resource_pool.rs

When resources are given back to a resource pool (e.g. Merkle maps in the Cardano transaction prover), they need to be reset properly (e.g. the Merkle map should be compressed so that all its values are represented by their root). This will guarantee that pooled resources are consistent and do not depend from previous computations. (e.g. this will avoid the risk of memory overflow and provide a consistent proving time).
- A `Reset` trait to be implemented by pooled resources of the `ResourcePool` (with a blanket implementation).
- Implementation of the `Reset` trait by the `MerkleMap` with a compression of the provable values to their root.
| Total Requests | Concurrency | Transactions/Request | Pool (x50) : Request/s | Pool (x50) + Reset given back pooled MKMaps: …

Implement pooled resource item reset when given back

---

CHANGELOG.md
Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/query/block_range_root/delete_block_range_root.rs
internal/mithril-persistence/src/database/query/block_range_root/mod.rs
internal/mithril-persistence/src/database/query/cardano_transaction/delete_cardano_transaction.rs
internal/mithril-persistence/src/database/query/cardano_transaction/get_cardano_transaction.rs
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-aggregator/tests/certificate_chain.rs
mithril-aggregator/tests/create_certificate.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/Cargo.toml
mithril-common/src/cardano_block_scanner/dumb_block_scanner.rs
mithril-common/src/cardano_block_scanner/interface.rs
mithril-common/src/chain_observer/fake_observer.rs
mithril-common/src/crypto_helper/merkle_tree.rs
mithril-signer/Cargo.toml
mithril-signer/src/cardano_transactions_importer.rs
mithril-signer/src/database/repository/cardano_transaction_repository.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/tests/create_cardano_transaction_single_signature.rs
mithril-signer/tests/create_immutable_files_full_single_signature.rs
mithril-signer/tests/era_switch.rs
mithril-signer/tests/test_extensions/certificate_handler.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR implement on the transaction importer rollback logic. If a Rollback event is received, the importer will:
- Delete the transaction records with a block number strictly greater than the block number of the roll backward chain point.
- Delete the block range root records with a start greater or equal to the start of the block range compute from the roll backward chain point.
- Branch
- PR
Closes #1724

Handle rollbacks when reading blocks from the chain

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/store/adapter/memory_adapter.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/store/verification_key_store.rs

This PR includes fixes to clippy warnings occurring following the release of Rust `1.79.0`.
- Branch
- PR

fix: clippy warnings with Rust `1.79.0`

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/dependency_injection/containers.rs
mithril-aggregator/src/runtime/runner.rs
mithril-common/Cargo.toml
mithril-common/src/entities/signed_entity_config.rs
mithril-common/src/lib.rs
mithril-common/src/signed_entity_lock.rs
mithril-common/src/signed_entity_type_lock.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR add a lock mechanism to make our state machines skip a signed entity when needed (ie: when we need to do a costly computation on a signed entity but we still want our state machines to run).
On aggregator the skip is done when it try to create open messages.
On signer the skip is done when it check if it can sign a pending certificate.
- Branch
- PR
Closes #1693

Signed entity lock mechanism

---

.github/workflows/actions/build-upload-mithril-artifact/action.yml
.github/workflows/actions/prepare-distribution/action.yml
.github/workflows/ci.yml
.github/workflows/pre-release.yml
.github/workflows/test-client.yml
CHANGELOG.md

This PR adds a new [macOS-arm64 runner](https://github.com/actions/runner-images/blob/macos-14-arm64/20240611.1/images/macos/macos-14-arm64-Readme.md) used for the following steps in the CI:
- build step for `mithril-client` binary, `mithril-client` and `mithril-stm` librairies
- test step for `mithril-client` binary and library
- packaging the pre-built binaries in the releases
- Mithril Client multi-platform test manual workflow
- Branch
- PR
Relates to #1751

Use `macOS-arm64` runner in CI

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/serve_command.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/dependency_injection/containers.rs
mithril-common/Cargo.toml
mithril-common/src/cardano_transactions_preloader.rs
mithril-common/src/lib.rs
mithril-signer/Cargo.toml
mithril-signer/src/configuration.rs
mithril-signer/src/main.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR includes a preload system for `CardanoTransaction` & `BlockRangeRoot`, it's simply a system that is spawned in a separate thread at aggregator & signer startup that run the transaction importer.
The CardanoTransaction signed entity type is lock during the preload and is released when it finish even if the preload fail.
- Branch
- PR
We designed this system specifically for the Cardano Transactions import first so we have a rough idea of what's needed before we can consider generalizing it to other tasks that need preload (such as immutable file digester cache or even maybe the import of signers pool tickers).
Closes #1692

Warmup/Preload cardano transactions & block range roots

---

mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www/package-lock.json
mithril-client-wasm/www/package.json
mithril-explorer/package-lock.json
mithril-explorer/package.json

This PR includes an upgrade of `mithril-explorer`, `www` and `www-test` dependencies (including patched version `8.17.1` for [ws](https://github.com/advisories/GHSA-3h5v-q93c-6h6q))
- Branch
- PR

Upgrade `mithril-explorer`, `www` and `www-test` dependencies

---

CHANGELOG.md
Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/configuration.rs
mithril-signer/src/database/repository/cardano_transaction_repository.rs
mithril-signer/src/lib.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/src/transactions_importer_by_chunk.rs
mithril-signer/src/transactions_importer_with_pruner.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/mithril/signer.rs

This PR break up in chunk the `mithril-signer` transactions import process, so the transactions pruning is done more frequently, reducing the number of transactions stored at any given time, reducing the disk footprint.
The chunk size is set to `1500` and is configurable.
- Branch
- PR
Closes #1766

Import transactions in sequence on signer

---

.github/workflows/actions/toolchain-and-cache/action.yml

This PR limit the cache generation for rust code to only the `main` branch.
As of `2024-06-21` our cache size is more than `6Gb`, since github only allow up to `10Gb` that means that we can't allow caches to be generated for non main branches, else it means that the cache from the `main` branch maybe be pruned automatically, slowing down drastically ou builds.
- Branch
- PR

Only save rust cache on main branch

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/http_server/mod.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/proof_routes.rs
mithril-aggregator/src/http_server/routes/root_routes.rs
mithril-aggregator/src/http_server/validators/mod.rs
mithril-aggregator/src/http_server/validators/prover_transactions_hash_validator.rs
mithril-aggregator/src/services/prover.rs
mithril-common/Cargo.toml
mithril-common/src/entities/http_server_error.rs
mithril-common/src/test_utils/fake_data.rs
mithril-common/src/test_utils/mod.rs
mithril-explorer/__tests__/CardanoTransactionsFormInput.test.js
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-explorer/src/components/Artifacts/CardanoTransactionsSnapshotsList/index.js
mithril-explorer/src/components/CardanoTransactionsFormInput.js
mithril-explorer/src/constants.js
mithril-explorer/src/store/settingsSlice.js
openapi.yaml

This PR includes a validation step for the transaction hashes transmitted via the HTTP route `/proof/cardano-transaction`. It was implemented with:
- **a new configuration parameter for the aggregator node**: `cardano_transactions_prover_max_hashes_allowed_by_request` that limits the number of hashes accepted as parameters on the `/proof/cardano-transaction` route.
- **a new structure `cardano_transactions_prover`** exposed on the root route `/`.
This structure is stored within the existing `capabilities` structure and currently contains only the previous configuration parameter value under the property name `max_hashes`.
- **a validator** that returns an error if the hash validation criteria are not met (empty string, length != 64, ASCII hexadecimal digit characters only). In case of an …

Ensure validation of transaction hashes to provide to the prover

---

.github/workflows/actions/toolchain-and-cache/action.yml
.github/workflows/ci.yml
.github/workflows/manual-publish-npm.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/cardano_transaction_migration.rs
internal/mithril-persistence/src/sqlite/connection_builder.rs
internal/mithril-persistence/src/sqlite/mod.rs
mithril-aggregator/src/commands/tools_command.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-signer/Cargo.toml
mithril-signer/src/lib.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/src/transactions_importer_with_vacuum.rs

This PR:
- Enable SQLite auto-vacuum for the Cardano transactions databases so they shrink automatically.
- Make `mithril-aggregator` & `mithril-signer` Vacuum their databases at startup (this can take a while so a log message is print).
- Modify preloading of Cardano transaction in `mithril-signer` so it execute a Vacuum after each chunk imported.
We do that since we observed that auto-vacuum isn't executed until the whole import is finished (maybe because the db is a lot busy in this phase) so a manual operation is needed.
- Branch
- PR
After merging #1766 we observed that the SQLite database file size did not decrease after pruning transactions in signer. This is due to SQLite not automatically reclaiming free pages by itself, we need to use the [`vacuum` …

Vacuum sqlite database at startup & after transactions preload

---

docs/website/root/manual/getting-started/bootstrap-cardano-node.md

This PR adds MSYS2 building instructions for mithril-client-cli.
I'm assuming the user has git or knows how to setup that part, and provide the necessary ssh credentials for git.
N/A

Add MSYS2 building instructions

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/query/block_range_root/get_block_range_root.rs
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/Cargo.toml
mithril-common/Cargo.toml
mithril-common/src/signable_builder/cardano_transactions.rs
mithril-signer/Cargo.toml

This PR fixes #1762:
It was due to the request to retrieve the pre-computed block range roots in database using a exclusive bound comparison instead of an inclusive, leading to the exclusion of the last block range root from the retrieved data.
This means that not only the prover was impacted but the protocol message generation for the single & multi signatures too.
- Branch
- PR
Even if `mithril-signer` and `mithril-aggregator` are not modified by this PR, their behavior is impacted so their version number should be upgraded.
Closes #1762

Fix #1762: CardanoTransactionSnapshot block number is not certified

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/prover.rs
mithril-common/Cargo.toml
mithril-common/src/signable_builder/cardano_transactions.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/runner.rs

This PR includes a fix to avoid copying the iterator in the `retrieve_block_range_roots` function of the `BlockRangeRootRetriever` trait.
- Branch
- PR
Relates to #1760

Fix: avoid iterator copy in `BlockRangeRootRetriever`

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-common/Cargo.toml
mithril-signer/Cargo.toml

This PR includes a fix to some blocks not being correctly parsed by `pallas` `0.27.0`. 
The fix is included with the upgrade to pallas `0.28.0`.
- Branch
- PR
Relates to #1750

Fix `sanchonet` blocks parsing

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-aggregator/tests/create_certificate.rs
mithril-signer/Cargo.toml
mithril-signer/src/cardano_transactions_importer.rs
mithril-signer/tests/create_cardano_transaction_single_signature.rs

This PR includes a fix to the aggregator and signer nodes which are blocked during the database insertions of the Cardano transactions: the state machines and the REST API were completely inaccessible.
- Branch
- PR
Closes #1797

Fix: aggregator and signer blocked during Cardano transactions import

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/query/block_range_root/delete_block_range_root.rs
internal/mithril-persistence/src/database/query/block_range_root/get_block_range_root.rs
internal/mithril-persistence/src/database/query/block_range_root/mod.rs
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/prover.rs
mithril-aggregator/tests/create_certificate.rs
mithril-aggregator/tests/prove_transactions.rs
mithril-aggregator/tests/test_extensions/aggregator_observer.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-aggregator/tests/test_extensions/utilities.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/merkle_map.rs
mithril-common/src/entities/signed_entity_config.rs
mithril-common/src/signable_builder/cardano_transactions.rs
mithril-signer/Cargo.toml

This PR includes a fix for #1785, there was several problems:
- The computed block number to be signed was not taking in account the fact that block range ends is exclusive, meaning that it overflowed over the next block range, a block range which end after the block number that we want to sign.
To solve this we simply subtract one to the computation.
- The request that retrieved block range when computing merkle roots excluded the last block range.
Not directly related to the bug: 
- The prover would add leaf to it's merkle tree in some condition, corrupting it as this changed its merkle root so it no longer matcher the one in the certificate.
This was worrisome since this corrupted merkle tree is returned to a resource pool after use, meaning that a subsequent requests would also yield …

Bugfix: Can't generate proof for transactions on the last signed block number

---

Cargo.lock
mithril-client-wasm/Cargo.toml
mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www/package-lock.json
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs
mithril-common/src/entities/http_server_error.rs
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-explorer/src/components/CertifyCardanoTransactionsModal/index.js

- Fix explorer crash when an error is returned when proving transaction (#1784)
- Enhance error transmission from the `mithril-client` when the queried aggregator return a 4xx or a 5xx error.
- Branch
- PR
Closes #1784

Fix explorer crash when proving transaction & enhance mithril-client error

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/prover.rs

This PR includes a fix to avoid some timeout occurring when trying to acquire a Merkle map from the resource pool when it is being refreshed.
- Branch
- PR
Closes #1793

Fix: avoid pool acquire timeout during Cardano transaction prover cache computation

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/upkeep.rs
mithril-signer/Cargo.toml
mithril-signer/src/upkeep_service.rs

This PR includes a tentative fix of CI flakiness observed for `UpkeepService` tests on both aggregator & signer.
- Branch
- PR

UpkeepService tests flakiness

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/certificate_routes.rs
mithril-aggregator/src/message_adapters/to_certificate_pending_message.rs
mithril-common/Cargo.toml
mithril-common/src/entities/cardano_db_beacon.rs
mithril-common/src/messages/certificate_pending.rs
openapi.yaml

Improve certificate pending route performance of the aggregator removing the call to the Chain Observer used to retrieve the time point.
The beacon is now optional in the certificate pending route so it could be removed in a future version.
- Branch
- PR
Output of `ab` command on `testing-preview` with 1000 requests **before applying changes**:
`ab -n 1000 -c 10 -w https://aggregator.testing-preview.api.mithril.network/aggregator/certificate-pending`
| key                  | value                                          |
| -------------------- | ---------------------------------------------- |
| Server Hostname      | aggregator.testing-preview.api.mithril.network |
| Server Port          | 443                                            |
| Document Path        | …

Remove call to chain observer on pending certificate route

---

CHANGELOG.md

This PR includes the rotation of the `CHANGELOG` file preparing the release of the `2428` distribution.
- Branch
- PR
Relates to #1810

Update CHANGELOG with `2428` distribution release

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/aggregator_client.rs

This PR includes modifications in the `aggregator_client` tests of the `mithril-signer`.
`MockServer` passed as a parameter was being consumed, leading to errors in the tests.
- Branch
- PR
Closes #1816

Fix Signer `make test` command errors

---

.github/workflows/actions/deploy-terraform-infrastructure/action.yml

This PR includes a fix to the terraform deployment action in the CI/CD where a configuration parameter was missing
- Branch
- PR
Relates to #1814

Fix: missing configuration in terraform deployment action in CI/CD

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-aggregator/tests/create_certificate.rs
mithril-aggregator/tests/prove_transactions.rs
mithril-signer/Cargo.toml
mithril-signer/src/cardano_transactions_importer.rs
mithril-signer/tests/create_cardano_transaction_single_signature.rs
mithril-test-lab/mithril-end-to-end/src/bin/load-aggregator/main.rs

This PR includes a small refactor of aggregator & signer `CardanoTransactionImporter` threading logic to use [task::spawn_blocking](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) instead of [task::block_in_place](https://docs.rs/tokio/latest/tokio/task/fn.block_in_place.html).
- Branch
- PR

Remove `task::block_in_place` in transaction importer

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-common/Cargo.toml
mithril-common/src/cardano_block_scanner/chain_reader_block_streamer.rs
mithril-signer/Cargo.toml
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/mithril/aggregator.rs

This PR changes how the `ChainReaderBlockStreamer` handle it's upper bound (its `until` parameter): 
Before its upper bound was exclusive, this was fine when others subsystems were also exclusive but this changed with the fixes for #1785: now the `until` parameter is the last block to include in the signature instead of being the block where to stop polling.
- Branch
- PR
Should this parameter be still named `until` ?
Relates to #1785

Make upper bound of `ChainReaderBlockStreamer` inclusive

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/record/certificate.rs
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db/download.rs
mithril-common/Cargo.toml
mithril-common/src/messages/certificate.rs
mithril-common/src/messages/certificate_list.rs
openapi.yaml

This PR make the, deprecated, `beacon` field an Option in the `Certificate` & `CertificateList` messages.
This will allow us to remove them completely in the future when enough nodes have been updated, making the switch to "variable" beacon, aka SignedEntityType, complete.
- Branch
- PR
Closes #1807

Make deprecated `beacon` field optional in `Certificate` & `CertificateList` messages

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/resource_pool.rs

This PR includes a fix to the **ResourcePool** to reset the resource given back even when it is done through the `ResourcePoolItem` wrapper. 
- Branch
- PR

fix: Resource not Reset when given back to Pool

---

CHANGELOG.md
Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/chain_reader/pallas_chain_reader.rs
mithril-test-lab/mithril-end-to-end/src/mithril/aggregator.rs

This PR includes a fix to the **Chain Reader**: 
when the **Chain Sync** client does not have agency (i.e. is waiting for the server to callback), the find intersect point call to the **Chain Sync** is not allowed and is now skipped in the `find_intersect_point` function of the **Chain Reader**.
- Branch
- PR
Closes #1836

fix: `ChainReader` fails on `find_intersect_point` without agency

---

Cargo.lock
internal/mithril-build-script/Cargo.toml
internal/mithril-build-script/src/fake_aggregator.rs
mithril-client-cli/Cargo.toml
mithril-client-cli/src/lib.rs
mithril-client/Cargo.toml
mithril-client/src/cardano_transaction_client.rs
mithril-client/src/lib.rs
mithril-common/Cargo.toml
mithril-common/src/entities/certificate.rs
mithril-common/src/entities/signed_entity_config.rs
mithril-common/src/lib.rs
mithril-stm/Cargo.toml
mithril-stm/src/merkle_tree.rs
mithril-stm/src/stm.rs

This PR includes fixes to clippy warnings occurring following the release of Rust `1.80.0`.
- Branch
- PR

fix: clippy warnings with Rust `1.80.0`

---

.github/workflows/release.yml

This PR includes an upgrade on the `release-mainnet` aggregator VM data disk from `pd-standard` to `pd-balanced`.
- Branch
- PR
Relates to #1830

Upgrade `release-mainnet` aggregator VM data disk

---

Cargo.lock
demo/protocol-demo/Cargo.toml
examples/client-cardano-transaction/Cargo.toml
examples/client-mithril-stake-distribution/Cargo.toml
examples/client-snapshot/Cargo.toml
flake.lock
internal/mithril-build-script/Cargo.toml
internal/mithril-doc-derive/Cargo.toml
internal/mithril-doc/Cargo.toml
internal/mithril-persistence/Cargo.toml
mithril-aggregator/Cargo.toml
mithril-client-cli/Cargo.toml
mithril-client-wasm/Cargo.toml
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-relay/Cargo.toml
mithril-signer/Cargo.toml
mithril-stm/Cargo.toml
mithril-test-lab/mithril-aggregator-fake/Cargo.toml
mithril-test-lab/mithril-end-to-end/Cargo.toml

This PR includes the upgrade of Rust dependencies in the repository.
- Branch
- PR
Relates to #1830

Upgrade Rust dependencies

---

.github/workflows/scripts/run-wasm-tests-browser-headless.py

This PR includes a modification to the timeout for the client WASM headless browser tests (executed by Mithril Client multi-platform test).
Since certificate chain verification takes longer on `preview` than on `sanchonet`, the timeout has been increased from `3` minutes to `10` minutes.
Mithril Client multi-platform test results:
https://github.com/input-output-hk/mithril/actions/runs/10141858789/job/28039918080
- Branch
- PR

Increase timeout for client WASM headless browser tests

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-common/Cargo.toml
mithril-common/src/messages/register_signature.rs
mithril-signer/Cargo.toml
mithril-signer/src/message_adapters/to_register_signature_message.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/stress_test/payload_builder.rs

This PR makes the `signed_entity_type` non optional in `RegisterSignatureMessage`
- Branch
- PR
All the SPOs are now running a version that supports non optional so we do not provide compatibility tests without signed_entity_type.
Closes #1863

Make signed_entity_type non optional in RegisterSignatureMessage

---

.github/workflows/ci.yml

When we access to the documentation with `index.html` at the end of the url (https://mithril.network/doc/index.html), the page content is displayed twice.
We inject a javascript in the `doc/index.html` to redirect to the clean url without `index.html`at the end.
The script is added at the beginning of the `index.html`.
```
<script type="text/javascript"> 
if (window.location.href.endsWith("/index.html")) {
end_of_clean_url = window.location.href.lastIndexOf("/");
window.location.href = window.location.href.substring(0, end_of_clean_url);
}
</script>
```
- Branch
- PR
The issue is referenced in `docusaurus` repository: https://github.com/facebook/docusaurus/pull/10059
Closes #1867

Add a redirection on index.html to clean url

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/cardano_block_scanner/chain_reader_block_streamer.rs
mithril-common/src/chain_reader/fake_chain_reader.rs

This PR includes a fix to the `ChainReaderBlockStreamer` which skips `RollForward` blocks at the tip of the chain.
- Branch
- PR
Closes #1875

Fix: `ChainReaderBlockStreamer` skips `RollForward` blocks at the tip

---

CHANGELOG.md
Cargo.lock
internal/mithril-persistence/src/sqlite/condition.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/migration.rs
mithril-aggregator/src/database/query/signed_entity/get_signed_entity.rs
mithril-aggregator/src/database/record/signed_entity.rs
mithril-aggregator/src/database/repository/signed_entity_store.rs
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_stake_distribution.rs
mithril-aggregator/src/http_server/routes/artifact_routes/mod.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/message_adapters/mod.rs
mithril-aggregator/src/message_adapters/to_cardano_stake_distribution_list_message.rs
mithril-aggregator/src/message_adapters/to_cardano_stake_distribution_message.rs
mithril-aggregator/src/services/message.rs
mithril-aggregator/src/services/signed_entity.rs
mithril-aggregator/tests/cardano_stake_distribution_verify_stakes.rs
mithril-aggregator/tests/test_extensions/aggregator_observer.rs
mithril-common/Cargo.toml
mithril-common/src/entities/signed_entity.rs
mithril-common/src/messages/cardano_stake_distribution.rs
mithril-common/src/messages/cardano_stake_distribution_list.rs
mithril-common/src/messages/mod.rs
mithril-common/src/test_utils/fake_data.rs
mithril-test-lab/mithril-devnet/mkfiles/mkfiles-mithril-delegation.sh
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/assertions/check.rs
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
mithril-test-lab/mithril-end-to-end/src/mithril/infrastructure.rs
openapi.yaml

This PR introduces new HTTP routes in the Aggregator REST API specifically for handling the signed entity type `CardanoStakeDistribution`:
- `/artifact/cardano-stake-distributions`
- `/artifact/cardano-stake-distribution/{hash}`
- `/artifact/cardano-stake-distribution/epoch/{epoch}`
The end to end test has been updated to include the verification of `CardanoStakeDistribution` certification, ensuring that the new routes respond correctly.
- Branch
- PR
Closes #1841

Implement Cardano stake distribution HTTP routes

---

CHANGELOG.md
Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs
mithril-client/src/cardano_stake_distribution_client.rs
mithril-client/src/client.rs
mithril-client/src/lib.rs
mithril-client/src/message.rs
mithril-client/src/type_alias.rs
mithril-common/Cargo.toml
mithril-common/src/signable_builder/cardano_stake_distribution.rs

This PR adds new functionalities to the `mithril-client` crate related to Cardano stake distribution. The library now supports the following features:
- Retrieve a Cardano stake distribution by its hash.
- Retrieve a Cardano stake distribution by its epoch.
- Get a list of available Cardano stake distributions.
- Branch
- PR
Closes #1842

Implement Cardano stake distribution in `mithril-client` library

---

.github/workflows/test-client.yml
CHANGELOG.md
Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_stake_distribution/download.rs
mithril-client-cli/src/commands/cardano_stake_distribution/list.rs
mithril-client-cli/src/commands/cardano_stake_distribution/mod.rs
mithril-client-cli/src/commands/mod.rs
mithril-client-cli/src/main.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/assertions/check.rs
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
mithril-test-lab/mithril-end-to-end/src/mithril/client.rs
mithril-test-lab/mithril-end-to-end/src/mithril/mod.rs

This PR adds support for new commands in the `mithril-client` CLI for `CardanoStakeDistribution`.
These commands are currently unstable and must be used with the `--unstable` option.
- **list**: `./mithril-client --unstable cardano-stake-distribution list`
- **download**: `./mithril-client --unstable cardano-stake-distribution download $UNIQUE_IDENTIFIER`
The `$UNIQUE_IDENTIFIER` can be either the  `hash` or the `epoch` of the `CardanoStakeDistribution`.
The identifier `latest` is also supported.
An alias `csd` has been created for `cardano-stake-distribution`.
- Branch
- PR
Closes #1880

Implement Cardano stake distribution commands in `mithril-client` CLI

---

CHANGELOG.md
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-explorer/src/app/page.js
mithril-explorer/src/components/Artifacts/CardanoStakeDistributionsList/index.js

This PR includes an update to `mithril-explorer` that implements a new tab, which displays the Cardano Stake Distribution list only when the signed entity type is advertised by the aggregator.
- Branch
- PR
Closes #1843

Add new tab Cardano Stake Distribution in the explorer

---

Cargo.lock
Cargo.toml
docs/website/root/manual/developer-docs/nodes/mithril-client-library-wasm.md
docs/website/root/manual/developer-docs/nodes/mithril-client-library.md
docs/website/root/manual/developer-docs/nodes/mithril-client.md
examples/client-cardano-stake-distribution/.gitignore
examples/client-cardano-stake-distribution/Cargo.toml
examples/client-cardano-stake-distribution/README.md
examples/client-cardano-stake-distribution/src/main.rs
mithril-client-wasm/README.md
mithril-client-wasm/npm/README.md
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs

This PR includes updates to the documentation website and provides an example crate demonstrating how to implement a Mithril client and its features related to the Cardano stake distribution.
A blog post will be published in an upcoming PR.
- Branch
- PR
Relates to #1844

Document Cardano Stake Distribution

---

CHANGELOG.md
Cargo.lock
docs/website/root/manual/developer-docs/nodes/mithril-client-library-wasm.md
mithril-client-wasm/Cargo.toml
mithril-client-wasm/src/client_wasm.rs
mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www/index.js
mithril-client-wasm/www/package-lock.json
mithril-client-wasm/www/package.json
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs
mithril-client/src/client.rs
mithril-explorer/package-lock.json

This PR introduces the ability to set custom HTTP headers in the Mithril client WASM.
A new optional parameter for client options has been added to the `MithrilClient` constructor, allowing users to specify custom headers.
This enhancement is backward-compatible. The constructor can still be called without passing any options, ensuring no breaking changes.
```js
// Passing custom HTTP headers
let http_headers_map = new Map();
http_headers_map.set("Authorization", "Bearer YourBearerToken");
http_headers_map.set("X-Custom-Header", "YourCustomHeaderValue");
let client_options = {
http_headers: http_headers_map,
};
let client = new MithrilClient(
"YOUR_AGGREGATOR_ENDPOINT",
"YOUR_GENESIS_VERIFICATION_KEY",
client_options,
);
```
- Branch
- PR
Closes #1878
Relates to #1720

Add support for custom HTTP Headers in Mithril client WASM library

---

.gitignore
CHANGELOG.md
Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/snapshot_downloader.rs

[LW-11112](https://input-output.atlassian.net/browse/LW-11112)
This PR includes support for the `file://` scheme in URLs of the snapshots.
This is very useful for live demos, where you don’t want to repeatedly download from Google Cloud Storage because of the wait time and cost.
- Branch
- PR
It requires a proxy modifying responses from the aggregator, e.g. [this](https://github.com/input-output-hk/lace/pull/1350).
[LW-11112](https://input-output.atlassian.net/browse/LW-11112)

feat: support `file://` URLs for snapshot locations

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_stake_distribution.rs
mithril-aggregator/tests/cardano_stake_distribution_verify_stakes.rs
mithril-common/Cargo.toml
mithril-common/src/entities/epoch.rs
mithril-common/src/signable_builder/cardano_stake_distribution.rs

This PR includes a fix to compute the message and the artifact on the correct epoch for the **Cardano stake distribution** signed entity type.
- Branch
- PR
Closes #1895

Fix: Cardano stake distribution certification epoch discrepancy

---

CHANGELOG.md
Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-aggregator/src/services/prover.rs
mithril-common/Cargo.toml
mithril-common/benches/merkle_map.rs
mithril-common/benches/merkle_tree.rs
mithril-common/src/crypto_helper/merkle_map.rs
mithril-common/src/crypto_helper/merkle_tree.rs
mithril-common/src/crypto_helper/mod.rs
mithril-common/src/entities/cardano_transactions_set_proof.rs
mithril-common/src/messages/cardano_transactions_proof.rs
mithril-common/src/signable_builder/cardano_stake_distribution.rs
mithril-common/src/signable_builder/cardano_transactions.rs
mithril-signer/Cargo.toml
mithril-signer/benches/mktree_store_sqlite.rs
mithril-signer/src/cardano_transactions_importer.rs
mithril-signer/src/lib.rs
mithril-signer/src/mktree_store_sqlite.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/signer_services.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR includes the **optimization of the memory usage of the signer** when signing Cardano transactions:
- The capability of the Merkle tree `MKTree` to support multiple `MKTreeStorer` implementations for data storage.
- The implementation of a signing specific Merkle store which is dedicated for the signer and with optimized memory usage.
- The benchmarks of the new signer Merkle store.
- Also some enhancements of the benchmarks of the Merkle tree.
The signer memory usage (Resident memory) is **~-67%** less.
The Merkle tree creation takes **~+50%** longer than with the original in memory store.
- **Merkle tree creation for 100,000 leaves**
- **Merkle tree creation for 1,000,000 leaves**
- **Merkle tree creation for 10,000,000 leaves**
- Branch
- PR
Closes #1903

Optimize memory usage of signer for Cardano transactions

---

.prettierignore
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/root_routes.rs
mithril-common/Cargo.toml
mithril-common/src/messages/aggregator_features.rs
openapi.yaml

This PR enhance add Cardano transactions signing configuration to the message returned by the Aggregator '/' route if the Cardano transactions are enabled on said Aggregator, else it's omitted.
- Branch
- PR
Closes #1898

Add Cardano transactions signing configuration in Aggregator '/' route

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/record/single_signature.rs
mithril-aggregator/src/message_adapters/from_register_signature.rs
mithril-common/Cargo.toml
mithril-common/src/entities/single_signatures.rs
mithril-common/src/messages/register_signature.rs
mithril-common/src/protocol/single_signer.rs
mithril-signer/Cargo.toml
mithril-signer/src/message_adapters/to_register_signature_message.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/stress_test/payload_builder.rs
openapi.yaml

This PR add an optional field to single signatures: `signed_message`.
In order to decentralize signatures orchestration we will need to buffer incoming single signatures when the Aggregator has yet to create an open message for the signed entity type.
But in that case we won't be able to some validation to reject immediately malicious signatures from bad actors. 
This new field will allow us to do an integrity check of incoming signatures, by checking their validity against their signed message and the current stake distribution, .
- Branch
- PR
Closes #1899

Optional signed message in registered signatures

---

CHANGELOG.md
Cargo.lock
mithril-client/Cargo.toml
mithril-client/README.md
mithril-common/Cargo.toml
mithril-stm/Cargo.toml
mithril-stm/src/eligibility_check.rs

To allow disable `LGPL` usage which discussed [in](https://github.com/input-output-hk/mithril/issues/1786), added `rug-backend` feature for `mithril-client` and `mithril-common` crates.
Closes #1786

feat: Make `rug-backend` optional for `mithril-client` crate

---

CHANGELOG.md
Cargo.lock
docs/website/root/manual/developer-docs/nodes/mithril-client-library-wasm.md
mithril-client-wasm/Cargo.toml
mithril-client-wasm/src/client_wasm.rs
mithril-client-wasm/www-test/index.js
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www-test/webpack.config.js
mithril-client-wasm/www/index.js
mithril-client-wasm/www/package.json
mithril-client-wasm/www/webpack.config.js
mithril-client/Cargo.toml
mithril-client/src/client.rs
mithril-explorer/package.json
mithril-explorer/src/components/CertifyCardanoTransactionsModal/index.js

This PR includes an update of the **support of unstable features in the WASM client**:
- the `unstable` client has been removed
- the client options have a new `unstable` flag (activated for WASM only)
- the WASM client enforces the usage of the `unstable` flag for unstable features 
- when transitioning from `unstable` to `stable` there is no more breaking change for the users
- Branch
- PR
Closes #1911

Refactor: seamless `unstable` to `stable` transition in WASM client

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/snapshotter.rs

This PR fixes clippy warning added in [rust 1.81](https://releases.rs/docs/1.81.0/) _(released on the 5 September)_.
- Branch
- PR

Fix clippy warnings from Rust 1.81

---

docs/runbook/upgrade-repository-dependencies/README.md
docs/runbook/upgrade-repository-dependencies/upgrade_dependencies.sh

Updating dependencies is described in the runbook `docs/runbook/upgrade-repository-dependencies/README.md`.
To avoid doing all these operations manually and limit the risk of error, we want to provide a script that does all these operations
- Branch
- PR

Add a script to update all dependencies

---

CHANGELOG.md
Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/configuration.rs
mithril-signer/src/main.rs
mithril-test-lab/mithril-end-to-end/src/mithril/signer.rs

This PR includes an **infinite preloader of Cardano transactions** in the signer.
- Branch
- PR
Closes #1920

Feat: add infinite Cardano transactions preloader in signer

---

Cargo.lock
demo/protocol-demo/Cargo.toml
docs/website/package-lock.json
docs/website/package.json
examples/client-cardano-stake-distribution/Cargo.toml
examples/client-cardano-transaction/Cargo.toml
examples/client-mithril-stake-distribution/Cargo.toml
examples/client-snapshot/Cargo.toml
flake.lock
flake.nix
internal/mithril-build-script/Cargo.toml
internal/mithril-doc-derive/Cargo.toml
internal/mithril-doc/Cargo.toml
internal/mithril-persistence/Cargo.toml
mithril-aggregator/Cargo.toml
mithril-client-cli/Cargo.toml
mithril-client-wasm/Cargo.toml
mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www/package-lock.json
mithril-client-wasm/www/package.json
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-relay/Cargo.toml
mithril-signer/Cargo.toml
mithril-stm/Cargo.toml
mithril-test-lab/mithril-aggregator-fake/Cargo.toml
mithril-test-lab/mithril-end-to-end/Cargo.toml

This PR upgrades our project dependencies to their latest version in preparation for release 2437 by running the [upgrade script from the runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/upgrade-repository-dependencies) 
Note: In order to upgrade nix `flake.lock`, we needed to set in stone the version of [crane](https://github.com/ipetkov/crane) since the latest version contains breaking changes should be handled in a dedicated PR.
- Branch
- PR

Update dependencies for release 2437

---

CHANGELOG.md

This PR includes the final change log for `2437.0` release.
- Branch
- PR

Update CHANGELOG for `2437.0` distribution release

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/cardano_transaction_migration.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-common/src/chain_reader/pallas_chain_reader.rs
mithril-signer/Cargo.toml
mithril-signer/src/dependency_injection/builder.rs

This PR includes a fix that prevents **data inconsistency in the Cardano transactions store** if it has been created with stale versions of the signer.
- Branch
- PR

Fix: data inconsistency in Cardano transactions stores

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-common/Cargo.toml
mithril-common/src/entities/epoch_settings.rs
mithril-common/src/messages/epoch_settings.rs
mithril-common/src/test_utils/fake_data.rs
mithril-signer/Cargo.toml
mithril-signer/src/message_adapters/from_epoch_settings.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/state_machine.rs
mithril-signer/src/services/epoch_service.rs
openapi.yaml

This PR includes  a way for the signer to access the Cardano transaction signing configuration from the aggregator via the `/epoch-settings` route.
The configuration is retrieved by the signer at each epoch transition and stored in its epoch service.
- Branch
- PR
Closes #1923

Retrieve custom signing configuration with epoch settings in Signer

---

CHANGELOG.md

This PR includes the final change log for `2437.1` distribution release.
- Branch
- PR

Docs: final CHANGELOG for '2437.1' distribution

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/logging.rs

This PR fix an error detailed in the [draft issue](https://github.com/orgs/input-output-hk/projects/26/views/14?pane=issue&itemId=80847117).
The linting reason has been removed, as it's still experimental and cannot be applied yet.
The initial error from Hydra CI: https://github.com/input-output-hk/mithril/pull/1948/checks?check_run_id=30529857732
```
error[E0658]: lint reasons are experimental
--> mithril-common/src/logging.rs:31:9
|
31 |         reason = "A field is needed to add the lifetime but is unused"
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #54503 <https://github.com/rust-lang/rust/issues/54503> for more information
```
- Branch
- PR

Fix: hydra CI error when `allow` lint attribute specifies a reason

---

docs/website/root/manual/getting-started/run-signer-node.md

This PR includes an update of the signer registration verification section in the "Run a Mithril signer as an SPO"
documentation.
- Branch
- PR

docs: improve clarity in "Verify your signer is registered" section

---

.github/workflows/ci.yml

This PR includes a fix to the **Swagger UI build** step in the CI: the missing 'GITHUB_TOKEN' is now required.
- Branch
- PR

Fix: swagger build step failing in CI

---

CHANGELOG.md
Cargo.lock
examples/client-mithril-stake-distribution/Cargo.toml
examples/client-mithril-stake-distribution/src/main.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/services/signable_builder/signable_seed_builder.rs
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/mithril_stake_distribution/download.rs
mithril-client-wasm/Cargo.toml
mithril-client-wasm/npm/README.md
mithril-client-wasm/src/client_wasm.rs
mithril-client-wasm/www-test/index.js
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www/index.js
mithril-client-wasm/www/package-lock.json
mithril-client-wasm/www/package.json
mithril-client/Cargo.toml
mithril-client/src/message.rs
mithril-client/tests/extensions/fake.rs
mithril-client/tests/mithril_stake_distribution_list_get_show_verify.rs
mithril-common/Cargo.toml
mithril-common/src/entities/protocol_message.rs
mithril-common/src/signable_builder/interface.rs
mithril-common/src/signable_builder/signable_builder_service.rs
mithril-signer/Cargo.toml
mithril-signer/src/dependency_injection/builder.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/services/signable_builder/signable_seed_builder.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR includes a **new computation of the protocol message** in the `Pythagoras` Mithril era:
- The **next protocol parameters** are appended to the protocol message
- The **current epoch** is appended to the protocol message
> [!IMPORTANT]
> :fire: This PR introduces a breaking-change in the `mithril-client` and `mithril-client-wasm` crates.
* [`examples/client-mithril-stake-distribution/Cargo.toml`](diffhunk://#diff-887fc60a9b9bc268630f88ffb4746333e0f8c76d0a2dc8800abe456fd8c2ce39L4-R4): Updated the version from `0.1.17` to `0.2.0`.
* [`mithril-aggregator/Cargo.toml`](diffhunk://#diff-5ae504281312c194e5e8cf6aa890f49508756041db9dbce0fd89fbf04438f90dL3-R3): Updated the version from `0.5.68` to `0.5.69`.
* [`mithril-client-cli/Cargo.toml`](diffhunk://#diff-2a39f2159ddf8206fa697498383f3b5c6 …

Feat: sign protocol parameters and epoch in certificate

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/repository/epoch_settings_store.rs
mithril-aggregator/src/dependency_injection/builder.rs

This PR includes a fix for the issue introduced by the merged PR #1964, which added a migration to the `epoch_setting` table.
The `cardano_transactions_signing_config` column had a JSON default value that was not deserializable by `serde`.
This PR adds a new migration to correct this by providing a deserializable default value.
Error on `testing-preview` aggregator:
```
thread 'main' panicked at /home/runner/work/mithril/mithril/internal/mithril-persistence/src/sqlite/cursor.rs:35:76:
called `Result::unwrap()` on an `Err` value: InvalidData("Could not turn string '{}' to CardanoTransactionsSigningConfig. Error: missing field `security_parameter` at line 1 column 2")
```
- Branch
- PR
Relates to #1924

Fix: add migration to resolve deserialization issue with `cardano_transactions_signing_config`

---

docs/website/blog/2024-07-30-cardano-transaction-certification/index.md

- Updates on the [Certification of Cardano transactions](https://mithril.network/doc/dev-blog/2024/07/30/cardano-transaction-certification) dev blog post.
- Branch
- PR

Docs: dev blog post for activation of the Cardano transaction certification

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/services/aggregator_client.rs

This PR fix #1976 by making changing to a "ok" the result of an error received when sending a single signature to an aggregator if that aggregator already certified the signature message.
- Branch
- PR
Closes #1976

Fix signer stuck if signature already aggregated

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/test_utils/fake_data.rs
mithril-signer/Cargo.toml
mithril-signer/src/dependency_injection/builder.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/state_machine.rs
mithril-signer/src/services/aggregator_client.rs
mithril-signer/src/services/certifier.rs
mithril-signer/src/services/epoch_service.rs
mithril-signer/src/services/signable_builder/signable_seed_builder.rs
mithril-signer/src/services/single_signer.rs
mithril-signer/src/store/protocol_initializer_store.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR refactor the `mithril-signer` in order to move the sign & send signatures responsibility from the state machine runner to the signer `Certifier` service.
One of the main concern for this refactor was to minimize the number of new dependencies that needed to be add to the certifier.
Simply moving the code from the runner to the certifier would have result in adding the following dependencies:
- `epoch_service` and `protocol_initializer_store` and `single_signer`: to issue the single signature.
- `certificate_handler`: to send the signatures but we would only need one method of it's whole api.
The protocol initializer of the current epoch is now stored on the epoch service.
It's stored as an option since it's only available if a signer is registered in the Mithril stake distribution …

Signer certifier service sign & send signatures

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/tools/genesis.rs
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_genesis.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/test_utils/mithril_fixture.rs

This PR includes the **signature of the genesis epoch in the genesis certificate**.
* [`mithril-common/src/certificate_chain/certificate_genesis.rs`](diffhunk://#diff-d08972d7d55a30e9dab9426e7b031c0a4b786ac050b30c707fe34dcf3af464c7R46): Added `genesis_epoch` parameter to the `create_genesis_protocol_message` method and updated the method to include the `CurrentEpoch` part in the protocol message. [[1]](diffhunk://#diff-d08972d7d55a30e9dab9426e7b031c0a4b786ac050b30c707fe34dcf3af464c7R46) [[2]](diffhunk://#diff-d08972d7d55a30e9dab9426e7b031c0a4b786ac050b30c707fe34dcf3af464c7R58-R61) [[3]](diffhunk://#diff-d08972d7d55a30e9dab9426e7b031c0a4b786ac050b30c707fe34dcf3af464c7L97-R102)
* [`mithril-aggregator/src/tools/genesis.rs`](diffhunk://#diff-0e9381b29a84023643030c84795d59ebf49e69a048f9afc37623 …

Feat: sign epoch in genesis certificate

---

.github/workflows/test-client.yml
CHANGELOG.md
Cargo.lock
docs/website/root/manual/developer-docs/nodes/mithril-client.md
docs/website/root/manual/getting-started/bootstrap-cardano-node.md
examples/client-cardano-transaction/Cargo.toml
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_transaction/mod.rs
mithril-client-cli/src/main.rs
mithril-client-wasm/Cargo.toml
mithril-client-wasm/src/client_wasm.rs
mithril-client-wasm/www-test/index.js
mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www/package-lock.json
mithril-client-wasm/www/package.json
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs
mithril-client/src/client.rs
mithril-client/src/lib.rs
mithril-client/src/message.rs
mithril-client/src/type_alias.rs
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/mithril/client.rs

This PR includes the stabilization of the Cardano transaction client, previously available as an `unstable` feature.
This update ensures the Cardano transaction client is now stable using `mithril-client`, `mithril-client-cli` and `mithril-client-wasm`.
- Branch
- PR
Closes #1952

Make Cardano transaction client stable

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs

This PR includes the following changes to improve throughput in the `/register-signer` route:
- Replaces direct calls to the chain observer (via the ticker service) with calls to the epoch service.
- Removes the `with_ticker_service` middleware since it's not used anymore.
- Branch
- PR
Closes #1982

Optimize `/register-signer` route by replacing ticker service with epoch service

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/mithril_stake_distribution.rs
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/dependency_injection/containers.rs
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/root_routes.rs
mithril-aggregator/src/multi_signer.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-aggregator/src/services/certifier/certifier_service.rs
mithril-aggregator/src/services/epoch_service.rs
mithril-aggregator/src/services/signable_builder/signable_seed_builder.rs
mithril-aggregator/tests/test_extensions/aggregator_observer.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs
mithril-common/Cargo.toml
mithril-common/src/entities/signed_entity_config.rs

This PR includes the use of the constant stored signing configurations for creating the signed entity type in the aggregator. This information is exposed by the epoch service.
Additionally, it removes the signed entity configuration from the aggregator’s dependency container.
The testing tools for the epoch service have also been simplified to improve ease of use and understanding.
- Branch
- PR
Closes #1961

Feat: use stored signing configuration in aggregator when creating signed entity type

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/main.rs
mithril-test-lab/mithril-end-to-end/src/mithril/aggregator.rs
mithril-test-lab/mithril-end-to-end/src/mithril/infrastructure.rs
mithril-test-lab/mithril-end-to-end/src/mithril/signer.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/aggregator_helpers.rs

This PR move into sub-directories the artifacts generated during an `mithril-end-to-end` run in order reduce the number of file in the work directory (that became quite packed).
Before a typical run would yield:
```shell
$ tree -L 1 /tmp/mithril-end-to-end/
Downloads/tmp/mithril-e2e-tests-artifacts-run_7180-attempt_1-mode_p2p-era_thales-cardano-9.1.1-fork-0-run_id_#1/
├── devnet
├── devnet-e11-i2.3fbf74bd9da957b719e80b562c7a845c4c87161e530c962c073bf887944865f7.tar.zst
├── devnet-e12-i2.f0b62520d4689fb37c3f8c5f611d357a2f4b0df1387fe845f6a6e67e081e5e73.tar.zst
├── devnet-e13-i2.c811e3d6e4ce658b1207ba131db4aaea2a30c7b2262239c641212d2bf2164d1e.tar.zst
├── devnet-e13-i3.c194fd6096c42dafe4788a82d11b77d26f568370fb78e08370184f80a79ff527.tar.zst
├── …
```

Better folder structure for End to End test

---

mithril-test-lab/mithril-end-to-end/README.md

This PR includes instructions for troubleshooting Cardano node issues on macOS environments when running the end to end test.
- Branch
- PR

Docs: add timeout troubleshooting macOS section in E2E README

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/mithril/aggregator.rs

This PR includes a modification that disables store pruning for genesis commands, an operation that is unnecessary in this context.
An issue was identified through E2E tests and was causing a panic during the pruning of the epoch setting table: https://github.com/input-output-hk/mithril/actions/runs/11146785295/job/30979818861#step:6:642
- Branch
- PR
Closes #1983

Fix: aggregator panics in CI

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_stake_distribution.rs
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_transaction.rs
mithril-aggregator/src/http_server/routes/artifact_routes/mithril_stake_distribution.rs
mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs
mithril-aggregator/src/http_server/routes/certificate_routes.rs
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/proof_routes.rs
mithril-aggregator/src/http_server/routes/root_routes.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/http_server/routes/statistics_routes.rs

This PR simplify the aggregator http server dependencies by providing the dependency container by reference instead of by move, allowing to remove the numerous `.clone()` used before.
- Branch
- PR

Refactor(aggregator): simplify http server dependencies

---

.github/workflows/pre-release.yml

This PR includes updates of the CI jobs that create `pre-release` and `release` to replace the unmaintained `marvinpinto/action-automatic-releases` action.
The https://github.com/softprops/action-gh-release is a suitable replacement for the pre-release job as it can handle the tasks previously managed by both [marvinpinto/action-automatic-releases](https://github.com/marvinpinto/actions/tree/master/packages/automatic-releases) and [tubone24/update_release](https://github.com/tubone24/update_release) , including updating the release notes body.
Examples of releases created from a fork of Mithril using these new GitHub Action: https://github.com/dlachaume/mithril/releases
- Branch
- PR
Closes #1691

Use new GitHub action for creating releases

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/main.rs

This PR includes an update to the **default preloader refresh interval of the signer** which has been set to **12 hours instead of 2 hours**.
- Branch
- PR
Relates to #1943

Chore: update signer preloader refresh interval

---

Cargo.lock
demo/protocol-demo/Cargo.toml
docs/website/package-lock.json
docs/website/package.json
examples/client-cardano-stake-distribution/Cargo.toml
examples/client-cardano-transaction/Cargo.toml
examples/client-mithril-stake-distribution/Cargo.toml
examples/client-snapshot/Cargo.toml
flake.lock
internal/mithril-build-script/Cargo.toml
internal/mithril-doc-derive/Cargo.toml
internal/mithril-doc/Cargo.toml
internal/mithril-persistence/Cargo.toml
mithril-aggregator/Cargo.toml
mithril-client-cli/Cargo.toml
mithril-client-wasm/Cargo.toml
mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www/package-lock.json
mithril-client-wasm/www/package.json
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-common/src/test_utils/apispec.rs
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-relay/Cargo.toml
mithril-signer/Cargo.toml
mithril-stm/Cargo.toml
mithril-test-lab/mithril-aggregator-fake/Cargo.toml
mithril-test-lab/mithril-end-to-end/Cargo.toml

This PR **upgrades the repository dependencies to their latest version in preparation of the distribution `2442`** by running the [upgrade script from the runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/upgrade-repository-dependencies).
* [`demo/protocol-demo/Cargo.toml`](diffhunk://#diff-7aac6f0e8796fce4168b46544f2b6985b9092a1dbca5460b87a9accfd41eb529L3-R3): Updated package version to `0.1.43`.
* [`docs/website/package.json`](diffhunk://#diff-6b3fee1f3a38ae94985c198b966e4146e25ef58d5a0065a27fcfe6c4dc20093aL3-R3): Updated package version to `0.1.43`.
* [`examples/client-cardano-stake-distribution/Cargo.toml`](diffhunk://#diff-8baa47aa186a41f172e17b0c12722a34ff55063eb44827a7d8a5a99ed4e0464cL4-R4): Updated package version to `0.1.2`.
* …

Chore: update dependencies for distribution `2442`

---

CHANGELOG.md

This PR includes the final change log for `2442.0` release.
- Branch
- PR
Relates to #1943

Docs: update CHANGELOG for `2442.0` distribution release

---

docs/runbook/upgrade-repository-dependencies/README.md
docs/runbook/upgrade-repository-dependencies/upgrade_dependencies.sh

This PR includes a fix to the steps in the `Upgrade the project's dependencies in the repository` runbook and the associated script `upgrade_dependencies.sh`:
- Reorder steps to compile `mithril-client-wasm` crate before updating the explorer
- Remove  from the script the npm package version bump (in `/mithril-client-wasm/pkg` file) for `mithril-client-wasm`
- Branch
- PR

Fix: update dependencies runbook and script

---

.github/workflows/ci.yml

This PR includes updates the CI jobs responsible for creating the `unstable` release release by replacing the unmaintained `marvinpinto/action-automatic-releases` action.
The https://github.com/softprops/action-gh-release now replaces both the [marvinpinto/action-automatic-releases](https://github.com/marvinpinto/actions/tree/master/packages/automatic-releases) [tubone24/update_release](https://github.com/tubone24/update_release) actions.
An additional step has been added to remove the previous `unstable` distribution and tag using the GitHub CLI's dedicated [`gh release delete`](https://cli.github.com/manual/gh_release_delete) command. This task was originally handled by the `marvinpinto/action-automatic-releases` action.
Example of unstable release created from a fork of Mithril using …

Use new GitHub action for creating `unstable` release

---

.github/workflows/ci.yml

This PR includes a fix following the merge of PR #2007.
The auto-generated part of the `unstable` release note, which contains the commit history, is no longer published.
- Branch
- PR
Relates to #1691

Fix: add missing automatically generated release note section for `unstable` releases

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/version_checker.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-common/Cargo.toml
mithril-common/src/cardano_block_scanner/chain_reader_block_streamer.rs
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/chain_reader/pallas_chain_reader.rs
mithril-common/src/digesters/cardano_immutable_digester.rs
mithril-common/src/logging.rs
mithril-common/src/messages/cardano_transactions_proof.rs
mithril-common/src/signable_builder/cardano_immutable_full_signable_builder.rs
mithril-common/src/signable_builder/cardano_transactions.rs
mithril-common/src/signable_builder/signable_builder_service.rs
mithril-signer/Cargo.toml
mithril-signer/src/dependency_injection/builder.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/state_machine.rs
mithril-signer/src/services/certifier.rs
mithril-signer/src/services/epoch_service.rs
mithril-signer/src/services/single_signer.rs
mithril-signer/src/services/upkeep_service.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

Following the light rules we decided to applies for logs when working on the aggregator (see #2009), this PR applies those rules on `mithril-signer`, `mithril-common` and `mithril-persistence`:
- Harmonize all "function enter" logs message to be in the form of `>> function_name`. 
- Capitalize the first letters of all "functional" logs.
It also:
- For signer runner function enter logs: add the value of some of the function parameters to the log to provide more context.
- rework where the function entries logs are done when using signable builders: instead of be sent by the child buiders they are sent by the parent (avoiding repetition and making sure that no builders are left out ... as before).
- Branch
- PR
Relates to #1981

Standardize logs in common, signer, and persistence

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/genesis.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/test_utils/certificate_chain_builder.rs
mithril-common/src/test_utils/mod.rs

This PR includes the implementation of a **Certificate Chain Builder for tests**:
- This part of the code is now more readable and maintainable
- The certificate chains allows alteration of the genesis and standard certificates with closures
- The computation of the number of signers per epoch is now configurable with a closure
- Branch
- PR

Feat: implement certificate chain builder for tests

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/command_context.rs
mithril-client-cli/src/commands/cardano_db/download.rs
mithril-client-cli/src/commands/cardano_db/list.rs
mithril-client-cli/src/commands/cardano_db/mod.rs
mithril-client-cli/src/commands/cardano_db/show.rs
mithril-client-cli/src/commands/cardano_stake_distribution/download.rs
mithril-client-cli/src/commands/cardano_stake_distribution/list.rs
mithril-client-cli/src/commands/cardano_stake_distribution/mod.rs
mithril-client-cli/src/commands/cardano_transaction/certify.rs
mithril-client-cli/src/commands/cardano_transaction/mod.rs
mithril-client-cli/src/commands/cardano_transaction/snapshot_list.rs
mithril-client-cli/src/commands/cardano_transaction/snapshot_show.rs
mithril-client-cli/src/commands/mithril_stake_distribution/download.rs
mithril-client-cli/src/commands/mithril_stake_distribution/list.rs
mithril-client-cli/src/commands/mithril_stake_distribution/mod.rs
mithril-client-cli/src/commands/mod.rs
mithril-client-cli/src/configuration.rs
mithril-client-cli/src/lib.rs
mithril-client-cli/src/main.rs

This PR change how parameters are passed to client-cli commands: Instead of providing a `ConfigBuilder` from the config crate a `CommandContext` new struct is passed so we can provide more than just configuration parameters to sub-commands.
This change is needed in order to remove `slog_scope` so we can share the main logger defined in the bin `main`.
Two others changes are included:
- Introduce a `SharedArgs` struct so to define in one place arguments shared between all commands (only the `--json` option for now). It's flattened so this doesn't change the api.
- Minimize use of the config crate by instead using a "source" system with the `ConfigParameters`. Using both crate to fetch the same thing (parameters) was quite confusing, this is changed so config is only used for its capacity …

Refactor client cli command parameters

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db/download.rs
mithril-client-cli/src/commands/cardano_db/list.rs
mithril-client-cli/src/commands/cardano_db/show.rs
mithril-client-cli/src/commands/cardano_stake_distribution/download.rs
mithril-client-cli/src/commands/cardano_stake_distribution/list.rs
mithril-client-cli/src/commands/cardano_transaction/certify.rs
mithril-client-cli/src/commands/cardano_transaction/snapshot_list.rs
mithril-client-cli/src/commands/cardano_transaction/snapshot_show.rs
mithril-client-cli/src/commands/mithril_stake_distribution/download.rs
mithril-client-cli/src/commands/mithril_stake_distribution/list.rs
mithril-client-cli/src/commands/mod.rs
mithril-client-cli/src/main.rs
mithril-client-cli/src/utils/feedback_receiver.rs
mithril-client-cli/src/utils/progress_reporter.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs
mithril-client/src/certificate_client.rs
mithril-client/src/feedback.rs
mithril-client/src/message.rs
mithril-client/src/snapshot_client.rs
mithril-client/src/snapshot_downloader.rs

This PR refactor the log usage in `mithril-client` and `mithril-client-cli`:
- A dedicated child logger is used for each service (only `mithril-client`)
- Each child logger is tagged with its service name in order to identify quickly a log source without the need of a prefix in the log message.
- Change the name property in all logs from the default `slog-rs` to `mithril-client` (only `mithril-client-cli`).
- Capitalize the first letters of all "functional" logs.
- Remove `slog_scope` to enforce the usage of a name tagged child logger.
- Move away from the log message into a property huge structure (ie: some logs joined errors into their message, those errors have been moved to a "error" property).
- Branch
- PR
Relates to #1981

Enhance logs in client and client-cli

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/stress_test/entities.rs

This PR fixes clippy warning added in [rust 1.82](https://releases.rs/docs/1.82.0/) _(released on: 17 October, 2024)_.
- Branch
- PR

 Fix clippy warnings from Rust 1.82 

---

Cargo.lock
mithril-relay/Cargo.toml
mithril-relay/src/commands/aggregator.rs
mithril-relay/src/commands/context.rs
mithril-relay/src/commands/mod.rs
mithril-relay/src/commands/passive.rs
mithril-relay/src/commands/relay.rs
mithril-relay/src/commands/signer.rs
mithril-relay/src/lib.rs
mithril-relay/src/main.rs
mithril-relay/src/p2p/peer.rs
mithril-relay/src/relay/aggregator.rs
mithril-relay/src/relay/passive.rs
mithril-relay/src/relay/signer.rs
mithril-relay/src/repeater.rs
mithril-relay/tests/register_signer_signature.rs

This PR refactor the log usage in `mithril-relay`:
- A dedicated child logger is used for each service
- Each child logger is tagged with its service name in order to identify quickly a log source without the need of a prefix in the log message.
- Capitalize the first letters of all "functional" logs.
- Remove `slog_scope` to enforce the usage of a name tagged child logger.
- Move away from the log message into a property huge structure (ie: some logs joined errors into their message, those errors have been moved to a "error" property).
- Branch
- PR
Closes #1981

Enhance logs in mithril-relay

---

.github/workflows/ci.yml
.github/workflows/test-client.yml

This PR upgrades x86 mac os runners from macOs 12 to macOs 14 (following their upcoming removal) and fix an incorrect parameter name used with the action that build our open api static website.
- Branch
- PR
Closes #2016, #2017

Upgrade mac runner + Fix incorrect param

---

docs/website/blog/2024-10-15-cardano-stake-distribution-certification.md

This PR adds a blog post introducing the certification of Cardano stake distribution.
- Branch
- PR
Relates to #1943

Create dev blog post for certification of Cardano stake distribution

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/serve_command.rs

This PR includes a fix that prevents `clap` arguments from systematically overriding the configuration with boolean arguments.
- Branch
- PR
Relates to #1980

Fix: `clap` arguments are always overriding configuration

---

docs/runbook/era-markers/README.md

This pull request includes extensive updates to the `docs/runbook/era-markers/README.md` to improve clarity and ensure proper configuration for managing Mithril activation eras on the Cardano chain. The changes focus on enhancing the documentation format, updating environment variables, and providing detailed steps for setting up, bootstrapping, and updating era markers.
* Enhanced warning format for critical steps using `[!IMPORTANT]` and `:fire:` to emphasize potential risks. [[1]](diffhunk://#diff-2d57a3e53672e9bb187ee7c7a4cb310d950d62dd1ff620b9cce3077efd8b5e4eL7-R8) [[2]](diffhunk://#diff-2d57a3e53672e9bb187ee7c7a4cb310d950d62dd1ff620b9cce3077efd8b5e4eL144-R226)
* Added detailed instructions for setting up environment variables, including examples for both testnet and mainnet …

Docs: enhance era markers runbook

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/metrics/service.rs

This PR includes the renaming of `certificate_total_produced_since_startup` metric (leftover related to the original name).
- Branch
- PR
Relates to #1980

Fix: rename `certificate_total_produced_since_startup` metric name in aggregator

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-common/Cargo.toml
mithril-common/src/cardano_block_scanner/chain_reader_block_streamer.rs
mithril-common/src/cardano_block_scanner/dumb_block_scanner.rs
mithril-common/src/cardano_block_scanner/interface.rs
mithril-common/src/cardano_block_scanner/scanned_block.rs
mithril-common/src/chain_reader/entity.rs
mithril-common/src/chain_reader/fake_chain_reader.rs
mithril-common/src/chain_reader/pallas_chain_reader.rs
mithril-common/src/signable_builder/cardano_transactions.rs
mithril-signer/Cargo.toml
mithril-signer/src/services/cardano_transactions/importer/service.rs

This PR fix the issue described in #2021.
To do so the way that the importer obtains its starting point change:
- Before it would compute it by getting data from the highest stored transactions in database, this caused the issue since in test networks there may be huge ranges of blocks without transactions.
- Now if keep stored the last `ChainPoint` that was polled by its block streamer after each import, so it can be used as the next import start point, solving the issue.
The same start block number is used repeatedly 
```json
{ "msg": "Retrieving Cardano transactions between block_number '0' and '150'" }
{ "msg": "Retrieving Cardano transactions between block_number '0' and '300'" }
{ "msg": "Retrieving Cardano transactions between block_number '254' and '419'" }
{ "msg": "Retrieving …
```

Fix unneeded rescan when importing transactions in chunk

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/metrics/service.rs

This PR includes a renaming of aggregator metrics, removing the `_counter` suffix.
- Branch
- PR
Relates to #1980

Fix: remove `_counter` suffix from aggregator metrics

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_retriever.rs
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/certificate_chain/fake_certificate_retriever.rs
mithril-common/src/certificate_chain/mod.rs
mithril-common/src/test_utils/certificate_chain_builder.rs

This PR includes a fix to the chaining computation of the certificate chain in tests:
The previous certificate is either:
- the first certificate of the previous epoch if the certificate is the first of the epoch
- otherwise the first certificate of the epoch
- Branch
- PR

Fix: computation of the chaining of the certificates in tests

---

Cargo.lock
mithril-signer/Cargo.toml
mithril-signer/src/dependency_injection/builder.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/src/runtime/state_machine.rs
mithril-signer/src/services/certifier.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR includes a fix that was triggered by flakiness failures on the CI.
The problem occurred when there was an epoch change after the signer had already begun its signature process.
To resolve this, the current epoch is now passed as a parameter when the signer retrieves the beacon to sign, instead of retrieving it with the ticker service, ensuring consistency throughout the signature process.
This fixes all the CI errors such as:
`Mithril End to End test in failed: Minimum expected mithril stake distribution epoch not reached : 18 < 20`
- Branch
- PR
Closes #2044

Fix: ensure epoch consistency during epoch changes when signer is signing

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/main.rs

This PR rework the termination system of the end to end test runner by doing all stop operation at one unique place and listening to some unix signals (aka "graceful shutdown").
This will limit the possibility of a run finishing without terminating either its devnet or infrastructure (such as when the devnet start failed it was not stopped).
- Branch
- PR

Enhance end-to-end tests termination

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/cardano_transactions_importer.rs
mithril-common/Cargo.toml
mithril-common/src/cardano_block_scanner/block_scanner.rs
mithril-common/src/cardano_block_scanner/chain_reader_block_streamer.rs
mithril-common/src/cardano_block_scanner/dumb_block_scanner.rs
mithril-common/src/cardano_block_scanner/interface.rs
mithril-common/src/cardano_block_scanner/mod.rs
mithril-common/src/cardano_block_scanner/raw_cardano_point.rs
mithril-common/src/cardano_block_scanner/scanned_block.rs
mithril-common/src/chain_reader/entity.rs
mithril-common/src/chain_reader/fake_chain_reader.rs
mithril-common/src/chain_reader/interface.rs
mithril-common/src/chain_reader/pallas_chain_reader.rs
mithril-common/src/entities/cardano_chain_point.rs
mithril-signer/Cargo.toml
mithril-signer/src/services/cardano_transactions/importer/service.rs

This PR introduce a new type, `RawCardanoPoint`, that is used in place of our `ChainPoint` in the transaction import process.
The `RawCardanoPoint` doesn't have a block number unlike `ChainPoint`, this allow a lossless conversion from and to the pallas point used in their chainsync implementation, avoiding the creation of `ChainPoint` with a block number of `0`.
Also this PR changes the `ScannedBlock` block hash to be a bytes array as this reduce the number of conversion needed when working with pallas types as this type is only used in conjunction with those types (`RawCardanoPoint` also use a bytes array for the same reason).
- Branch
- PR
Closes #2037

Refactor ChainPoint conversion from pallas Point

---

.github/workflows/test-client.yml
CHANGELOG.md
Cargo.lock
docs/website/root/manual/developer-docs/nodes/mithril-client.md
docs/website/root/manual/getting-started/bootstrap-cardano-node.md
examples/client-cardano-stake-distribution/Cargo.toml
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_stake_distribution/mod.rs
mithril-client-cli/src/main.rs
mithril-client-wasm/Cargo.toml
mithril-client-wasm/src/client_wasm.rs
mithril-client-wasm/www-test/package-lock.json
mithril-client-wasm/www-test/package.json
mithril-client-wasm/www/package-lock.json
mithril-client-wasm/www/package.json
mithril-client/Cargo.toml
mithril-client/README.md
mithril-client/src/aggregator_client.rs
mithril-client/src/client.rs
mithril-client/src/lib.rs
mithril-client/src/message.rs
mithril-client/src/type_alias.rs
mithril-client/tests/extensions/fake.rs
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/mithril/client.rs

This PR includes the release of Cardano stake distribution in a `stable` version, previously available as an `unstable` feature.
This update ensures the Cardano stake distribution client is now stable using `mithril-client`, `mithril-client-cli` and `mithril-client-wasm`.
- Branch
- PR
Closes #2024

Feat: Make Cardano stake distribution stable in client

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/statistics_routes.rs
mithril-aggregator/src/metrics/service.rs

This PR includes the implementation of a new metric in the Prometheus endpoint of the aggregator, tracking the total number of restorations of the Cardano database.
The `cardano_db_total_restoration_since_startup` counter metric is recorded in the `/statistics/snapshot` route.
- Branch
- PR
Closes #2054

Feat: add aggregator metric to record the number of restoration of the Cardano database

---

.github/workflows/nightly-docker-builds.yml
.github/workflows/scheduled-docker-builds.yml

This PR includes the introduction of a scheduled Docker builds workflow, set to run daily at 2:00 AM UTC, with the option to trigger it manually.
- Branch
- PR
Closes #2026

CI: add scheduled Docker builds workflow

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-explorer/src/app/registrations/page.js
openapi.yaml

This PR modify the aggregator `signers/registered/{epoch}` route to accept not only numbers for the epoch but also `latest`. If `latest` is ask then the route handler will call the aggregator epoch service to obtain the current working epoch of the aggregator.
Plus the explorer "Signers registrations" page is updated to support `latest` as the epoch in its url.
Note: in order to describe this change in the openapi I had to upgrade to openapi version `3.1` (else I can't describe "const" parameter such as `latest`).
- Branch
- PR
Closes #1689

Access registered signers for latest epoch in explorer

---

mithril-explorer/Makefile
mithril-explorer/next.config.js
mithril-explorer/package-lock.json
mithril-explorer/package.json

This PR upgrade mithril explorer main dependencies, NextJs, to its latest major version.
There's some caveat:
* Vercel, the NextJs editor, recommend to use React 19 that's still a release candidate, but it's not compatible with `@reduxjs/toolkit` so React 18.3 is kept.
* Version 15 of `eslint-config-next` is compatible with eslint 9 but still ask for version `8.57.1` in its package json, leading to warnings when using `npm install`.
We should keep using eslint `8.57` until this is solved.
* Vercel say that Turbopack, its webpack replacement made with rust, is  ready for use in dev, but when we use it the app crash because it can't import properly the wasm library.
We should keep using webpack until this is solved.
Note: To test this tool, add `--turbopack` to the `dev` scripts in …

Upgrade mithril explorer to Next 15

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/dependency_injection/containers.rs
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_stake_distribution.rs
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_transaction.rs
mithril-aggregator/src/http_server/routes/artifact_routes/mithril_stake_distribution.rs
mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs
mithril-aggregator/src/http_server/routes/certificate_routes.rs
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-aggregator/src/http_server/routes/middlewares.rs
mithril-aggregator/src/http_server/routes/proof_routes.rs
mithril-aggregator/src/http_server/routes/root_routes.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/http_server/routes/statistics_routes.rs
mithril-aggregator/src/runtime/runner.rs

This PR changes the way the `Configuration` structure is used by the aggregator: except for one case (for tests), it's now only used in the dependency builder.
The `Configuration` struct contains un-validated, raw, values that must be transformed using an error prone operation. We should strictly limit its usages to the dependency builder to limit such errors to the application startup.
The main user of the `Configuration` beside the dependency container is the HTTP Server. In order to provide for its need validated configuration key the following refactor was done:
1. A new structure is introduced to hold validated configuration keys: `RouterConfig`
2. Another new structure, `RouterState`, is added to hold the dependency container (to access services) and the `RouterConfig`
3. **All** …

Streamline configurations usage in aggregator

---

.github/workflows/nightly-backward-compatibility.yml

This PR includes enhancements for the nightly backward compatibility testing workflow.
It schedules the workflow to run at night (2:30 UTC) and uploads artifacts upon failure.
Additionally, it introduces a comprehensive published summary for the runs:
- Branch
- PR
Closes #2027

CI: enhance nightly backward compatibility testing workflow

---

CHANGELOG.md

This PR includes the final change log for `2445.0` release.
- Branch
- PR
Relates to #2030

Docs: update CHANGELOG for `2445.0` distribution release

---

.github/workflows/nightly-backward-compatibility.yml

This PR updates the nightly backward compatibility workflow to include **signed entity types**
- Branch
- PR
Relates to #2027

Feat: custom signed entity types in backward compatibility test in CI

---

docs/devbook/upgrade-crates-and-openapi-versions/upgrade_crates_and_openapi_versions.sh

Add `--update` git option to not commit unfollow files.
- Branch
- PR

Do not add unfollow files when commit with upgrade_crates_and_openapi_versions.sh

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/event_store/database/query.rs
mithril-aggregator/src/event_store/database/repository.rs
mithril-aggregator/src/event_store/event.rs
mithril-aggregator/src/event_store/transmitter_service.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/http_server/routes/statistics_routes.rs
mithril-aggregator/src/services/usage_reporter.rs

Separates the creation of the event message from its sending.
This allows messages to be easily injected into the database while guaranteeing the same construction as in production
This PR move the `EventMessage` creation from `TransmitterService` to the `EventMessage`.
- Branch
- PR
Relates to #2086

Refactor event message creation

---

mithril-client-wasm/Makefile

Dear Mithril-team,
we need a commonjs package to run the mithril-client-wasm module within our ibc gateway setup. 
Would it be possible to bundle the module for the nodejs target as well and publishing it within your pipeline to the npm package regsitry? I added the needed line to your Makefile. 
Thanks for your support and keep up the great work ! 💪 
Fabian

chore: add build target nodejs

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/certificate_chain/fake_certificate_retriever.rs
mithril-common/src/test_utils/certificate_chain_builder.rs
mithril-common/src/test_utils/mod.rs

This PR includes **enhancements to the verification of the certificate chain**:
- Improved readability of the code by creating multiple sub verification functions
- Refactoring of the `CertificateVerifier` trait
- Simplified and strengthened testing 
- Branch
- PR

Feat: enhance certificate chain verification

---

docs/runbook/aggregator-metrics/README.md
docs/runbook/registrations-monitoring/README.md

This pull request includes updates to the **runbooks for monitoring metrics and signer registration monitoring**. The changes improve clarity and provide more detailed examples.
* [`docs/runbook/aggregator-metrics/README.md`](diffhunk://#diff-9b1572e3be3ac3e5c9c7511ba42360a363c726d1c9c125c7c52e4b83f39d2b3cL3-R62): Updated the description of the `metrics_per_day` view and provided a clearer example of how to display aggregated metric values by day.
* [`docs/runbook/registrations-monitoring/README.md`](diffhunk://#diff-8bc2a01ef864f753a84f5e249ff54fd3b03875bd09040a66de3bcf1ea90a9addL1-R51): Renamed the section to "Signer registration monitoring" and updated the description of the `signer_registration_summary` view with a clearer example of how to display aggregated signer versions and total …

Docs: enhance runbook for aggregator metrics and signer registrations

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/runtime/state_machine.rs
mithril-aggregator/src/services/epoch_service.rs
mithril-common/Cargo.toml
mithril-common/src/chain_observer/fake_observer.rs

This PR includes storing all the necessary information in the `EpochService` to support the future `/status` route on the aggregator.
The following data is now saved:
- Current Cardano era
- Current Mithril era
- Total number of SPOs for the current epoch
- Total stake for the current epoch
This PR will allow the `/status` route to expose these details when implemented.
- Branch
- PR
Relates to #2071

Feat: record informations in epoch service for status route

---

CHANGELOG.md
Cargo.lock
docs/website/root/manual/develop/nodes/mithril-aggregator.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/era_command.rs
mithril-aggregator/src/commands/genesis_command.rs
mithril-aggregator/src/tools/genesis.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/genesis.rs
mithril-common/src/crypto_helper/types/protocol_key.rs

This PR includes the implementation and documentation of the new `genesis generate-keypair` command in the aggregator that is used to **create Genesis keypairs**.
* Added `generate-keypair` command to the list of subcommands in `mithril-aggregator.md`.
* Documented parameters for the `generate-keypair` command in `mithril-aggregator.md`.
* Added `GenerateKeypair` variant to the `GenesisSubCommand` enum in `genesis_command.rs`.
* Implemented the `execute` method for the `GenerateKeypairGenesisSubCommand` struct in `genesis_command.rs`.
* Added `create_and_save_genesis_keypair` function to `GenesisTools` in `genesis.rs`.
* Updated the `export_keypair_to_files` method in `ProtocolGenesisSigner` to export both secret and verification keys in `genesis.rs`.
* Added a test for the …

Feat: add `genesis generate-keypair` command in aggregator

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/http_server/routes/aggregator_status.rs
mithril-aggregator/src/http_server/routes/mod.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/http_server/routes/status.rs
mithril-aggregator/src/services/epoch_service.rs
mithril-common/Cargo.toml
mithril-common/src/entities/type_alias.rs
mithril-common/src/messages/aggregator_status.rs
mithril-common/src/messages/mod.rs
openapi.yaml

This PR includes the creation of a `/status` route on the aggregator REST API that exposes essential information about the aggregator's status.
- Branch
- PR
Closes #2071

Feat: implement `/status` route to expose aggregator information

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/chain_observer/pallas_observer.rs

This PR includes a fix for the retrieval of the Cardano era in the `PallasChainObserver` to ensure the correct era display name is returned. The offset is adjusted to align with the era mapping differences in the Cardano node implementation.
- Branch
- PR
Closes #2111

Fix: adjust era offset in `PallasChainObserver` for correct display name

---

docs/website/blog/2024-07-30-cardano-transaction-certification/index.md
docs/website/blog/2024-10-15-cardano-stake-distribution-certification.md
docs/website/docusaurus.config.js
docs/website/root/manual/getting-started/README.mdx
docs/website/root/manual/getting-started/_category_.json
docs/website/root/mithril/mithril-protocol/_category_.json
docs/website/root/mithril/mithril-protocol/certificates.md
docs/website/root/mithril/threat-model.md
docs/website/src/components/HomepageFeatures/index.js
docs/website/versioned_docs/version-maintained/manual/getting-started/README.mdx
docs/website/versioned_docs/version-maintained/manual/getting-started/_category_.json
docs/website/versioned_docs/version-maintained/mithril/mithril-protocol/_category_.json
docs/website/versioned_docs/version-maintained/mithril/mithril-protocol/certificates.md
docs/website/versioned_docs/version-maintained/mithril/threat-model.md

This PR includes the update of the links to the new **Protocol Insights Dashboard** in the documentation website. It also includes minor renaming of titles in the website.
* Updated various titles and labels to use consistent capitalization across the documentation. For example, "Get Started" was changed to "Get started" and "Mithril Protocol" was changed to "Mithril protocol". [[1]](diffhunk://#diff-70be1076198388519bcef7adfc3fdc47f96ed6b6e6a2cb9f13f09afebebcbf8fL2-R2) [[2]](diffhunk://#diff-21521dafbcb8b3a845dcb3fe93f56ddbec852ae4e052f1c50325b6d02d38a823L2-R2) [[3]](diffhunk://#diff-72fae1731f2ea9727ef00714be4425a72da90b90902b5063118a98bd91608c9aL2-R8) [[4]](diffhunk://#diff-7a0982d40448485c939f52f893c97b903f1082d8eb46d27bd943d4421a5f662fL3-R3) …

Docs: update Protocol Insights Dashboard links

---

Cargo.lock
mithril-stm/Cargo.toml
mithril-stm/src/stm.rs

For two different random configurations of the STM property test `batch_verify`, in one iteration of each batch, not enough unique signatures were collected to meet the quorum. This caused the batch verification functionality test to fail intermittently, leading to flaky CI behavior.
This PR updates the STM parameters for this test to ensure the quorum is always met, enabling consistent testing of batch verification functionality.
- Branch
- PR
Closes #2109

Fix for Failing STM Proptests

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/router.rs

This PR fix the handling of `404` errors in the aggregator http server.
In case of a `404` the custom rejection middleware  immediatly emit a rejection _(this custom rejection was added to set the appropriate status code for API Version Mistmatch errors)_.
This means that no other middleware would be applied nor our custom headers.
- Branch
- PR
This problem cascade to the browser javascript `fetch` api, the missing headers make the api immediately throw an error thus making impossible [to handle the `404` in a idiomatic way](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_response_status).
In this example the status code can't be checked in the `then` block since a exception is raised _(note: the exception doesn't contains the status code)_.
```javascript …
```

fix(aggregator): properly handle `404` errors in http server

---

docs/website/docusaurus.config.js
docs/website/package-lock.json
docs/website/package.json
docs/website/root/mithril/mithril-protocol/security.md
docs/website/versioned_docs/version-maintained/mithril/mithril-protocol/security.md

This PR includes a page for **Mithril protocol security** in the documentation website (which nows supports mathematical notations by integrating `remark-math` and `rehype-katex`).
> [!NOTE]
> Here is a screenshot of the rendered page:
> ![Screenshot from 2024-11-20 15-10-43](https://github.com/user-attachments/assets/07cc2eaf-784f-48ef-8637-80624f4c979e)
- Branch
- PR

Docs: protocol security page on documentation website

---

docs/website/blog/2024-11-25-one-line-binaries-installer.md
docs/website/root/compiled-binaries.mdx
docs/website/versioned_docs/version-maintained/compiled-binaries.mdx

* [`docs/website/blog/2024-11-25-one-line-binaries-installer.md`](diffhunk://#diff-bf61a68c6a366f97d3cd6c504015e5a9a30621b8f9df7fa9510c1108e8f4559bR1-R64): Added a new blog post detailing the one-line installer for Mithril binaries, including examples and usage instructions.
* [`docs/website/root/compiled-binaries.mdx`](diffhunk://#diff-e68bd7c47d62dcacb564ed9e4e403ec27f49e3a3c6ea21117a928be3e2895325L12-R14): Updated the code block to use the new one-line installer command for installing the latest Mithril binaries.
* [`docs/website/versioned_docs/version-maintained/compiled-binaries.mdx`](diffhunk://#diff-e68bd7c47d62dcacb564ed9e4e403ec27f49e3a3c6ea21117a928be3e2895325L12-R14): Updated the code block to use the new one-line installer command for installing the latest …

Docs: dev blog post for one line installer

---

docs/devbook/README.md
docs/devbook/bump-versions/README.md
docs/devbook/bump-versions/bump_versions.sh
docs/devbook/upgrade-crates-and-openapi-versions/upgrade_crates_and_openapi_versions.sh

This PR add to the upgrade version scrip in the devbook the capacity to bump js packages versions and rename it from `upgrade-crates-and-openapi-versions` to simply `bump-versions`.
It works the following way:
1. Detect all `package.json` files in the project, excluding those auto-generated or from imported packages
1. If there was a change compared to the `main` branch in a `package.json` directory
- _In dry run_ only print the updated version
- _else_ use `npm version patch` to bump the patch version (with `--no-git-tag-version` to handle the commit our-self)
1. Append the modified versions to the commit message
> [!NOTE]
> `docs/website/` is excluded as we don't want to bump its version if its articles or blog posts changed.
- Branch
- PR

Also bump versions of js packages in upgrade version script

---

.github/workflows/ci.yml

This PR fixes our swagger ui page, https://mithril.network/openapi-ui/,  that has been broken since merging #2062:
The faulty PR modified the version of our openapi file to `3.1.1`, but the action that we use (`Legion2/swagger-ui-action@v1`) is configured by default to use swagger ui version 3 or up, said swagger ui is only compatible with openapi `3.1` [since version 5](https://github.com/swagger-api/swagger-ui/tree/master?tab=readme-ov-file#compatibility).
- Branch
- PR

fix(ci): fix generation of swagger-ui page

---

CHANGELOG.md
Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/hydrator.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/migration.rs
mithril-aggregator/src/metrics/service.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/services/signed_entity.rs
mithril-aggregator/src/tools/certificates_hash_migrator.rs
mithril-aggregator/tests/test_extensions/aggregator_observer.rs
mithril-common/Cargo.toml
mithril-common/src/entities/signed_entity_config.rs
mithril-common/src/entities/signed_entity_type.rs
mithril-common/src/messages/message_parts/signed_entity_type_message.rs
mithril-common/src/signable_builder/signable_builder_service.rs
mithril-signer/Cargo.toml
mithril-signer/src/database/migration.rs

This PR implements a new signed entity type, `CardanoDatabase`, for the incremental Cardano database signature.
The use of panics with `todo!()` or `unimplemented!()` has been avoided in the `SignableBuilder` and the `compute_artifact` function in favor of returning errors instead.
- Branch
- PR
Closes #2121

Feat: create new signed entity type for Incremental Cardano DB

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/sqlite/connection_builder.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/status.rs
mithril-common/Cargo.toml
mithril-common/src/messages/aggregator_status.rs
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-explorer/src/components/ControlPanel/AggregatorStatus/index.js
openapi.yaml

This PR add a `cardano_network` key in the data returned by the aggregator `/status` route and update the explorer to display it in its `AggregatorStatus` component.
- Branch
- PR
Not directly related to this PR, the first commit simplify the logs of the connection builder in persistence to limit the numbers of logs to one instead of up to four when opening a connection without applying migrations.
Closes #2144

Cardano network on aggregator status and explorer

---

Cargo.lock
examples/client-cardano-stake-distribution/Cargo.toml
examples/client-cardano-stake-distribution/README.md
examples/client-cardano-stake-distribution/src/main.rs
examples/client-cardano-transaction/Cargo.toml
examples/client-cardano-transaction/README.md
examples/client-cardano-transaction/src/main.rs
examples/client-mithril-stake-distribution/Cargo.toml
examples/client-mithril-stake-distribution/README.md
examples/client-mithril-stake-distribution/src/main.rs
examples/client-snapshot/Cargo.toml
examples/client-snapshot/README.md
examples/client-snapshot/src/main.rs
examples/client-wasm-nodejs/README.md
examples/client-wasm-nodejs/index.js
examples/client-wasm-nodejs/package-lock.json
examples/client-wasm-nodejs/package.json
examples/client-wasm-web/README.md
examples/client-wasm-web/index.js
examples/client-wasm-web/package-lock.json
examples/client-wasm-web/package.json

This PR updates the aggregator used in the examples, both Rust and JS, located in the [`/examples`](https://github.com/input-output-hk/mithril/tree/main/examples) directory of the repository. Specifically:
- `testing-sanchonet` to `release-preprod`
- `testing-preview` to `release-preprod`
- Branch
- PR

Chore: update aggregator in examples

---

.github/workflows/backward-compatibility.yml
.github/workflows/ci.yml
Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/devnet/mod.rs
mithril-test-lab/mithril-end-to-end/src/devnet/runner.rs
mithril-test-lab/mithril-end-to-end/src/main.rs

This PR includes **support for retrying e2e test runs** in case of transient error on the Cardano network of the underlying devnet (which happen because of the custom configuration used for it). This will overall remove the main source of flakiness in the CI runs.
* [`mithril-test-lab/mithril-end-to-end/src/devnet/runner.rs`](diffhunk://#diff-4c3f983f30bbeca5e07e02770b654dceb5d153aed2e01a03cfdec4b119fd4331R9-R15): Introduced `UnrecoverableDevnetError` and updated error handling in `impl Devnet` to use this new error type. 
* [`mithril-test-lab/mithril-end-to-end/src/main.rs`](diffhunk://#diff-a49c167415a5a251d16e124965eb257f95ebd243022897a79f5e0e8b00e4a2f0R22): Refactored the main function to use a new `AppResult` enum for handling different exit codes and added implementation for …

Feat: support retries in e2e tests in CI

---

.github/workflows/scripts/verify-distribution.sh

This PR includes **a fix to the GPG verification command** in the GitHub releases.
- Branch
- PR

Fix: GPG verification command of released artifact

---

.github/workflows/ci.yml

This PR add to our nightly releases (and, since we promote them, to other releases) the packaged Explorer.
This will allow to have two explorer: one based on the latest released stable and one based on the latest nightly.
- Branch
- PR

feat(ci): include explorer in packaged releases

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/tools/certificates_hash_migrator.rs

This PR includes a fix to the **certificate chain hash recomputation** to support large datasets.
* [`mithril-aggregator/Cargo.toml`](diffhunk://#diff-5ae504281312c194e5e8cf6aa890f49508756041db9dbce0fd89fbf04438f90dL3-R3): Updated the package version from `0.6.0` to `0.6.1`.
* [`mithril-aggregator/src/tools/certificates_hash_migrator.rs`](diffhunk://#diff-3228ebed3a11208c88b8d7bf73520a40098014e18162acf3c8987aed190e654fR149-L162): Added chunk processing for old hashes and old certificates to improve efficiency when updating signed entities and deleting old certificates. [[1]](diffhunk://#diff-3228ebed3a11208c88b8d7bf73520a40098014e18162acf3c8987aed190e654fR149-L162) [[2]](diffhunk://#diff-3228ebed3a11208c88b8d7bf73520a40098014e18162acf3c8987aed190e654fL182-R209)
- Branch
- PR
Relates to …

Fix: recompute certificate chain hash

---

.github/workflows/actions/prepare-distribution/action.yml
.github/workflows/ci.yml
.github/workflows/pre-release.yml
.github/workflows/scripts/package-distribution.py

This PR fix the explorer packaging when doing releases.
- allow to change the prepended name of the archive built (default to `mithril` to keep current behaviour)
- allow to omit the `--target` so this script can be used to packages project aht have a "target os" and or "target arch" (such as web projects)
- Fix explorer packaging: as #2167 all the explorer files were included uncompressed at the root of the release files instead of being packaged in a single archive.
- Include the explorer package in pre-release
- Branch
- PR

Fix explorer packaging in releases

---

Cargo.lock
docs/runbook/recompute-certificates-hash/README.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/tools/certificates_hash_migrator.rs

This PR includes includes an enhanced version of the [recompute certificates hash](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/recompute-certificates-hash) runbook that takes advantage of the new one line installer for Mithril binaries.
- Branch
- PR
Relates to #2124

Docs: enhance recompute certificates hash runbook

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/devnet/runner.rs

This PR includes **support for retryable errors when the underlying `devnet` bootstrap fails** in the e2e tests in the CI.
- Branch
- PR
Closes #2176

Feat: retryable `devnet` bootstrap errors in e2e tests

---

docs/website/root/manual/operate/run-signer-node.md
docs/website/versioned_docs/version-maintained/manual/develop/run-mithril-devnet.md
docs/website/versioned_docs/version-maintained/manual/getting-started/bootstrap-cardano-node.md
docs/website/versioned_docs/version-maintained/manual/operate/run-signer-node.md

This PR includes the rotation of the documentation with the release of the new `2450` distribution
* [`docs/website/root/manual/operate/run-signer-node.md`](diffhunk://#diff-ca80e5696ac46644482a8826a992f485257d43a5477a1ff0cba2537f3966d9feL121-R121): Updated the required version of `squid-cache` from 6.9 to 6.12 for production deployment. [[1]](diffhunk://#diff-ca80e5696ac46644482a8826a992f485257d43a5477a1ff0cba2537f3966d9feL121-R121) [[2]](diffhunk://#diff-ca80e5696ac46644482a8826a992f485257d43a5477a1ff0cba2537f3966d9feL562-R572) [[3]](diffhunk://#diff-ca80e5696ac46644482a8826a992f485257d43a5477a1ff0cba2537f3966d9feL610-R610)
* [`docs/website/versioned_docs/version-maintained/manual/develop/run-mithril-devnet.md`](diffhunk://#diff-9b1c827511f2848dc14970675395f36ec2d053ab96645ebd90089ce2a5e …

Docs: rotate documentation for `2450` distribution

---

docs/website/blog/2024-09-24-client-wasm-unstable-breaking-change.md
docs/website/blog/2024-10-15-cardano-stake-distribution-certification.md
docs/website/blog/2024-11-07-mithril-aggregator-prometheus-endpoint/index.md
docs/website/blog/2024-11-18-new-protocol-insights-dashboard/index.md
docs/website/blog/2024-11-25-one-line-binaries-installer.md

Dev blog copy review main branch

---

docs/website/blog/2024-12-17-distribution-2450.md

This PR includes a **dev blog post announcing the release of the [`2450`](https://github.com/input-output-hk/mithril/releases/tag/2450.0) distribution**.
- Branch
- PR
Relates to #2124

Docs: add dev blog post for distribution `2450`

---

.github/workflows/ci.yml
CHANGELOG.md
mithril-explorer/README.md
mithril-explorer/next.config.js
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-explorer/src/app/layout.js

This PR add a 'Unstable' feature flag to the explorer, toggled by setting a `UNSTABLE` environment variable to `1` **at compile time**.
This, alongside another change that allow to parametrize the explorer base path (to have correct intra links), allow us to have two published version of the explorer:
- `https://mithril.network/explorer/`: that will use the packaged version of the explorer from the last stable release, built with `unstable` feature disabled ( :hammer_and_pick: coming soon, see comments).
- `https://mithril.network/explorer/unstable`: that will use the latest code from the `main` branch, build with `unstable` features enabled.
- Branch
- PR
This does not finish #2172 as we need to wait for a new release to have a packaged "stable" explorer build that can be …

Build and publish an unstable explorer version

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/ancillary.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/mod.rs
mithril-aggregator/src/artifact_builder/mod.rs
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/file_uploaders/local_uploader.rs
mithril-common/Cargo.toml
mithril-common/src/entities/cardano_database.rs
mithril-common/src/entities/mod.rs

This PR includes the first implementation of the ancillary builder for the Incremental Cardano Database.
It handles the upload of ancillary artifacts using a Local Uploader and adds the returned locations to the `CardanoDatabaseSnapshot`. The creation and verification of the ancillary archive will be handled in a separate PR.
- Branch
- PR
Relates to #2151

Feat: implement the Ancillary sub builder for Incremental Cardano DB

---

docs/website/blog/2024-12-17-distribution-2450.md
docs/website/blog/2024-12-17-era-switch-pythagoras.md

This PR includes a **dev blog post announcing the era switch to `Pythagoras`**.
- Branch
- PR
Relates to #2034

Docs: add dev blog post for era switch to `Pythagoras`

---

.github/workflows/ci.yml

This PR swap the packaged explorer that's published in our github pages.
Now the package deployed is fetched from our latest released instead of using the one built in the `build-test-explorer` job (that we still need since it's used in (pre-)releases).
- Branch
- PR
Closes #2172

ci: publish packaged explorer in latest release

---

.github/workflows/ci.yml

This PR fix the stable explored download step in the `publish_docs` job, the github secret token was missing in order to use `gh` cli.
- Branch
- PR
Relates to #2172

ci: fix downloading of stable explorer when publishing to pages

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_immutable_files_full.rs
mithril-aggregator/src/snapshotter.rs

This PR includes an update to the `Snapshotter` that allows it to create archives from specific directories and files.
It’s a preparatory step for the creation of archives from ancillary files.
- Branch
- PR
Relates to #2151

feat: extend `Snapshotter` to archive only specific files and directories

---

Cargo.lock
docs/website/blog/2024-12-17-era-switch-pythagoras.md
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs

This PR includes a fix to **verify the `CardanoDatabase` artifacts in the e2e test only if the signed entity type is activated**.
- Branch
- PR
Closes #2193

Fix: `CardanoDatabase` artifacts verification in e2e test

---

.github/workflows/aggregator-stress-test.yml
.github/workflows/nightly-dispatcher.yml
.github/workflows/test-client.yml

This PR includes the **trigger of new workflows with the `Nightly Dispatcher`**:
- `Aggregator Stress Test` workflow
- `Client Multi Platform` workflow
- Branch
- PR
Closes #2177

Feat: add workflows to `Nightly Dispatcher`

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/record/signed_entity.rs
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_database.rs
mithril-common/Cargo.toml
mithril-common/src/entities/cardano_database.rs
mithril-common/src/messages/cardano_database.rs
mithril-common/src/messages/cardano_database_list.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/assertions/check.rs
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
openapi.yaml

This PR includes a **fix to avoid collisions of the `CardanoDatabase` artifacts** when a snapshot is taken for the same immutable file number at two different epochs.
- Branch
- PR
Closes #2197

Fix: `CardanoDatabase` artifact identifier collisions

---

.github/workflows/aggregator-stress-test.yml
.github/workflows/backward-compatibility.yml
.github/workflows/test-client.yml

This PR includes **enhancements on inputs support** for workflow triggered with the Nightly Dispatcher workflow.
- Branch
- PR

Refactor: enhance inputs for nightly workflows

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/ancillary.rs
mithril-aggregator/src/artifact_builder/cardano_immutable_files_full.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/file_uploaders/local_snapshot_uploader.rs
mithril-aggregator/src/file_uploaders/local_uploader.rs
mithril-aggregator/src/file_uploaders/mod.rs
mithril-aggregator/src/file_uploaders/url_sanitizer.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/snapshotter.rs
mithril-client/Cargo.toml
mithril-client/tests/extensions/fake.rs
mithril-client/tests/snapshot_list_get_show_download_verify.rs
mithril-common/Cargo.toml
mithril-common/src/digesters/cardano_immutable_digester.rs
mithril-common/src/digesters/dummy_cardano_db.rs
mithril-common/src/digesters/mod.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/bin/load-aggregator/main.rs
mithril-test-lab/mithril-end-to-end/src/stress_test/payload_builder.rs

This PR updates the `AncillaryArtifactBuilder` to include the creation of an archive from the ancillary files of the Cardano database. The archive contains:
- The `/ledger` directory and its content.
- The `/volatile` directory and its content.
- The `/immutable` directory, including the latest trio of immutable files (`.chunk`, `.primary`, `.secondary`).
Additionally, the returned locations for downloading the archive are now referenced in the artifact.
- Branch
- PR
Relates to #2151

Feat: ancillary archive creation

---

.github/workflows/aggregator-stress-test.yml
.github/workflows/backward-compatibility.yml
.github/workflows/nightly-dispatcher.yml
.github/workflows/test-client.yml

This PR includes a **fix to the workflows triggered by the Nightly Dispatcher** which are failing because of missing inputs.
- Branch
- PR

Fix: nightly dispatcher workflow 

---

docs/website/blog/2024-12-17-distribution-2450.md
docs/website/blog/2024-12-17-era-switch-pythagoras.md
docs/website/root/mithril/advanced/threat-model.md
docs/website/versioned_docs/version-maintained/mithril/advanced/threat-model.md

Threat model analysis and blog post review PR

---

.github/workflows/ci.yml
Cargo.lock
examples/client-wasm-nodejs/package-lock.json
examples/client-wasm-web/package-lock.json
mithril-client-wasm/Cargo.toml
mithril-client-wasm/Makefile
mithril-client-wasm/ci-test/package-lock.json
mithril-client-wasm/package.json
mithril-client-wasm/src/certificate_verification_cache.rs
mithril-client-wasm/src/client_wasm.rs
mithril-explorer/package-lock.json

This PR includes several updates to enable running Wasm tests in Node environments:
- Adds a `test-node` feature to the `mithril-client-wasm` crate to skip code that isn't compatible with Node.
- Upgrades the default Node version from `18` to `22` in the `build-test-wasm` step of the CI, ensuring `wasm-pack test` runs smoothly with node.
- Closes the `BroadcastChannel` after usage in `handle_event`, preventing Wasm tests from hanging indefinitely with node.
- Branch
- PR
Closes #2138

Fix: execute Wasm tests on node in CI

---

internal/mithril-doc/src/lib.rs
internal/mithril-doc/src/test_doc_macro.rs
mithril-aggregator/src/file_uploaders/local_snapshot_uploader.rs
mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs
mithril-common/src/crypto_helper/cardano/key_certification.rs
mithril-common/src/entities/signer.rs
mithril-common/src/entities/single_signatures.rs
mithril-common/src/messages/message_parts/signer.rs
mithril-common/src/messages/register_signer.rs
mithril-relay/src/relay/passive.rs
mithril-relay/tests/register_signer_signature.rs
mithril-signer/src/configuration.rs
mithril-test-lab/mithril-devnet/configuration/byron/configuration.yaml
mithril-test-lab/mithril-devnet/mkfiles/mkfiles-docker.sh
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
mithril-test-lab/mithril-end-to-end/src/mithril/infrastructure.rs

This PR includes a **cleanup of some TODOs comments in the repository** that could either be removed or fixed.
```
└─ mithril
├─ internal
│  ├─ mithril-doc
│  │  ├─ lib.rs
│  │  │  └─ line 3: TODO : Some Configuration could not be generated properly because there is a lack of information. (TO EXPLAIN)
│  │  └─ test_doc_macro.rs
│  │     └─ line 44: TODO May be part of StructDoc. (FIXED)
│  └─ mithril-persistence
│     ├─ repository
│     │  └─ cardano_transaction_repository.rs
│     │     └─ line 158: TODO : remove this collect to return the iterator directly (CREATE ISSUE)
│     └─ hydrator.rs
│        └─ line 23: TODO : Maybe there is a better way of doing this. (FIXED)
├─ mithril-aggregator
│  ├─ src
│  │  ├─ dependency_injection
│  │  │  ├─ builder.rs
│  │  │  │  └─ line 1313: TODO : …
```

Chore: clean TODOs in repository

---

docs/website/docusaurus.config.js
docs/website/package-lock.json
docs/website/package.json
docs/website/root/manual/develop/nodes/mithril-client.md
docs/website/versioned_docs/version-maintained/manual/develop/nodes/mithril-client.md

This PR add windows powershell commands instruction in the docusaurus website when building or running the mithril-client CLI.
Tabs are added on the page so users can switch between previous commands, that works for Linux and Mac, and the new windows version.
This PR also add syntax highlighting for `powershell` and `bash` scripts.
- Branch
- PR
Closes #2199

doc: add windows powershell commands in client cli documentation

---

Cargo.lock
mithril-client/Cargo.toml

This PR includes a fix to the **missing `DEBUG` logs in the release binaries built in the CI**.
- Branch
- PR
Closes #2227

Fix: missing `DEBUG` logs release builds

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/ancillary.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/digest.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/immutable.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/mod.rs
mithril-aggregator/src/artifact_builder/cardano_immutable_files_full.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/file_uploaders/dumb_uploader.rs
mithril-aggregator/src/file_uploaders/gcp_uploader.rs
mithril-aggregator/src/file_uploaders/interface.rs
mithril-aggregator/src/file_uploaders/local_snapshot_uploader.rs
mithril-aggregator/src/file_uploaders/local_uploader.rs
mithril-aggregator/src/file_uploaders/mod.rs
mithril-aggregator/src/snapshotter.rs
mithril-common/Cargo.toml
mithril-common/src/entities/cardano_database.rs
mithril-common/src/entities/file_uri.rs
mithril-common/src/entities/mod.rs
mithril-common/src/messages/cardano_database.rs
openapi.yaml

The `CardanoDatabaseArtifactBuilder` can build and upload immutables files and digests file
Implement the artifact builder for the Incremental Cardano Database with the target JSON structure:
```json
{
"merkle_root": "0506e5e1f7df9314ebdbb532768a5addc2931004c5cd8fd8cd464090f95e46e4",
"beacon": {
"network": "mainnet",
"epoch": 525,
"immutable_file_number": 6550
},
"certificate_hash": "04219eb7a66c37f0d917160b8bdc617dc4ff911344f2e72bdb22c1316cbe8d71",
"total_db_size_uncompressed": 52470081414,
"created_at": "2024-12-02T04:36:40.811764301Z",
"locations": {
"digests": [
{
"type": "aggregator",
"uri": "https://aggregator.release-mainnet.api.mithril.network/aggregator/artifact/cardano-database/digests"
},
{
"type": "cloud_storage",
"uri": …
```

Feat: Create immutable builder for incremental Cardano DB

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/ancillary.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/digest.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/immutable.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/file_uploaders/gcp_uploader.rs
mithril-aggregator/src/file_uploaders/mod.rs
mithril-infra/main.cloud-storage.tf
mithril-infra/variables.tf

This PR includes the **update of the `GcpUploader` to support synchronization of Cardano database artifacts.**
- Branch
- PR
Closes #2211

Feat: `GcpUploader` implements synchronization for Cardano database artifacts

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/snapshotter.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/codec.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/crypto_helper/types/protocol_key.rs

This PR includes a **fix to the deserialization of the protocol keys to support trailing whitespace in their files**.
- Branch
- PR

Fix: support trailing whitespace in protocol key files

---

.github/workflows/release.yml

This PR includes the **upgrade of the `release-preprod` VM from `e2-highmem-2` to `e2-highmem-4`**.
- Branch
- PR

Chore: upgrade `release-preprod` VM

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_database.rs
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_stake_distribution.rs
mithril-aggregator/src/http_server/routes/artifact_routes/cardano_transaction.rs
mithril-aggregator/src/http_server/routes/artifact_routes/mithril_stake_distribution.rs
mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs
mithril-aggregator/src/http_server/routes/certificate_routes.rs
mithril-aggregator/src/http_server/routes/epoch_routes.rs
mithril-aggregator/src/http_server/routes/proof_routes.rs
mithril-aggregator/src/http_server/routes/root_routes.rs
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-aggregator/src/http_server/routes/statistics_routes.rs
mithril-aggregator/src/http_server/routes/status.rs
mithril-aggregator/src/snapshotter.rs
mithril-common/Cargo.toml
mithril-common/src/test_utils/temp_dir.rs

- A fix to the flakiness in tests that uses `snapshotter` archive verification introduced in ca3f524e0f3177cbaebe3db8b5f75c297d4d3bb3.
- A simplification of http server tests by removing all usage of the `SERVER_BASE_PATH` as the tests don't need it.
- Branch
- PR

aggregator: fix flakiness of tests that uses the snapshotter and simplify http server tests

---

Cargo.lock
docs/website/docusaurus.config.js
mithril-common/Cargo.toml
mithril-common/src/test_utils/apispec.rs
openapi.yaml

To be conform to the OpenAPI specification 3.1, in a previous commit we have changed `example` property to `examples`.
Doing that, we have created 2 issues:
- Examples are no longer verified because we only looking for `example` property
- Examples are not correctly displayed because the `examples` property must contain an array of examples.
This PR fix this two issues and adjust the relative path to `openapi.yaml`to generate locally `aggregator-api` with docusaurus.
`ApiSpec` tests are modified to take into account `examples` property.
- Branch
- PR
Closes #2235

Openapi examples check

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/digest.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/immutable.rs
mithril-aggregator/src/configuration.rs
mithril-aggregator/src/dependency_injection/builder.rs
mithril-aggregator/src/file_uploaders/local_snapshot_uploader.rs
mithril-aggregator/src/file_uploaders/local_uploader.rs
mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/tools/url_sanitizer.rs

This PR introduce a `SanitizedUrlWithTrailingSlash` struct to avoid redundant call to the url sanitizer as it guarantee that the url that it hold is already sanitized.
- Branch
- PR

refactor(aggregator): better url sanitization process by using a value object

---

CHANGELOG.md
Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs
mithril-client/src/cardano_database_client.rs
mithril-client/src/cardano_stake_distribution_client.rs
mithril-client/src/client.rs
mithril-client/src/lib.rs
mithril-client/src/type_alias.rs
mithril-common/Cargo.toml
mithril-common/src/messages/mod.rs

This PR includes the implementation of a **client for the `CardanoDatabase` signed entity type in the client library** (limited to `get` and `list` snapshots).
- Branch
- PR
Relates to #2214

Feat: implement client for `CardanoDatabase` in client library (`list` and `get`)

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/snapshotter/compressed_archive_snapshotter.rs

If an archive exists, it must not be deleted if an error occurs when trying to create an archive with the same name.
We replace an existing snapshotted file only if the snapshotting is successful.
This PR include:
- Creation of the snapshot in a temporary file (same name with a .tmp suffix)
- Renaming the temporary file to the final file name, if the snapshotting is successful 
- Deleting the temporary file in any case, even if this file already exist before snapshotting
- Branch
- PR
Closes #2215

Do not delete an already existing archive on error

---

Cargo.lock
examples/client-wasm-nodejs/package-lock.json
examples/client-wasm-web/package-lock.json
internal/mithril-build-script/Cargo.toml
internal/mithril-build-script/src/fake_aggregator.rs
mithril-client-wasm/Cargo.toml
mithril-client-wasm/ci-test/package-lock.json
mithril-client-wasm/package.json
mithril-client-wasm/src/client_wasm.rs
mithril-explorer/package-lock.json
mithril-test-lab/mithril-aggregator-fake/Cargo.toml
mithril-test-lab/mithril-aggregator-fake/src/application.rs
mithril-test-lab/mithril-aggregator-fake/src/handlers.rs
mithril-test-lab/mithril-aggregator-fake/src/shared_state.rs

This PR makes variable and function names clearer in the fake aggregator and in the Mithril client WASM tests by removing abbreviations.
- Branch
- PR

Refactor: improve variable and function names in fake aggregator

---

.github/workflows/nightly-dispatcher.yml
.github/workflows/test-notify-on-failure.yml

This PR introduces a new manual workflow to test email alert delivery when an error occurs in the nightly dispatcher.
- Branch
- PR
Closes #2251

CI: move `notify-on-failure` to a dedicated workflow

---

.github/workflows/scripts/notify-nightly-failure.js
.github/workflows/test-notify-on-failure.yml

This PR includes a fix for the `test-notify-on-failure` workflow to allow it to be triggered by the Nightly Dispatcher workflow.
- Branch
- PR

Fix: add missing `workflow_call` trigger on Test Notify on Failure workflow

---

docs/website/blog/2024-12-17-era-switch-pythagoras.md

This PR includes an **update to the [Era switch to Pythagoras](https://mithril.network/doc/dev-blog/2024/12/17/era-switch-pythagoras) dev blog post**.
- Branch
- PR
Relates to #2034

docs: update `Pythagoras` era switch dev blog post

---

.github/workflows/test-client.yml
Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db/list.rs
mithril-client-cli/src/commands/cardano_db/show.rs
mithril-client-cli/src/commands/cardano_db_v2/list.rs
mithril-client-cli/src/commands/cardano_db_v2/mod.rs
mithril-client-cli/src/commands/cardano_db_v2/show.rs
mithril-client-cli/src/commands/mod.rs
mithril-client-cli/src/main.rs
mithril-client-cli/src/utils/cardano_db.rs
mithril-client/src/type_alias.rs
mithril-common/Cargo.toml
mithril-common/src/entities/cardano_database.rs
mithril-common/src/entities/mod.rs
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/assertions/check.rs
mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs
mithril-test-lab/mithril-end-to-end/src/mithril/client.rs
mithril-test-lab/mithril-end-to-end/src/mithril/mod.rs

This PR introduces a new `unstable` command (`cardano-db-v2` with alias `cdbv2`) for the Mithril client CLI, allowing users to list and show details of Incremental Cardano DB snapshots.
Example for `snapshot list` command:
```
mithril-client --unstable cardano-db-v2 snapshot list
```
_Terminal output:_
---
Example for `snapshot show` command:
```
mithril-client --unstable cardano-db-v2 snapshot show {ARTIFACT_HASH}
```
```
mithril-client --unstable cardano-db-v2 snapshot show latest
```
_Terminal output:_
Additionally, the E2E test and the Mithril Client multi-platform test manual workflow have been updated to verify both `cardano-db-v2` commands (`show` and `list`).
- Branch
- PR
Relates to #2246

Feat: Implement `cardano-db-v2` command in client CLI (`list` and `show`)

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/main.rs

This PR adds a new debug log that specifies the version of the Mithril client CLI whenever a command is executed.
- Branch
- PR

Chore: add Mithril client CLI version in debug logs

---

.github/workflows/actions/prepare-distribution/action.yml
docs/website/blog/2025-02-04-glibc-minimum-requirement-change.md
docs/website/root/compiled-binaries.mdx
docs/website/versioned_docs/version-maintained/compiled-binaries.mdx
mithril-install.sh

This PR add warnings for the upcoming glibc minimum version upgrade (from `2.31` to `2.35`).
- Docusaurus: Add a warning in the linux requirements block
- Docusaurus: Add a blog post about the upcoming change
- CI: Add a warning in the linux requirements block in our release note
- install script: Add an automatic check of the `glibc` version when used on linux. If below the actual supported version of `2.31` the script will now fails with a message, if the version is supported but deprecated (between `2.31` and `2.34` included) a deprecation warning is shown.
- Branch
- PR
Relates to #2216

Add warning for linux requirements upgrade

---

Cargo.lock
docs/website/root/manual/develop/nodes/mithril-aggregator.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/era_command.rs
mithril-aggregator/src/tools/era.rs
mithril-common/Cargo.toml
mithril-common/src/crypto_helper/era.rs

Creation of a command on the aggregator to create test era keys for setting up a test
- a new sub-command `generate-keypair` for the era command to export non deterministic `era.sk` and `era.vk` files.
- a parameter `target-path` to define the export directory
- the update of the aggregator documentation
- Branch
- PR
Closes #2271

Add an `era` subcommand to create keypair

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/immutable.rs
mithril-aggregator/src/services/snapshotter/appender.rs
mithril-aggregator/src/services/snapshotter/compressed_archive_snapshotter.rs

This PR fixes some flakiness occurring when running aggregator tests in parallel due to collisions between temporary directory paths.
- Branch
- PR

Fix: prevent aggregator test conflicts by using unique temporary directories

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml
Cargo.lock
examples/client-wasm-nodejs/package-lock.json
examples/client-wasm-web/package-lock.json
mithril-aggregator/Cargo.toml
mithril-client-cli/Cargo.toml
mithril-client-wasm/Cargo.toml
mithril-client-wasm/ci-test/package-lock.json
mithril-client-wasm/package.json
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-explorer/package-lock.json
mithril-test-lab/mithril-aggregator-fake/Cargo.toml

This PR includes the **bump of minor versions of crates for `2506.0` distribution release**.
- Branch
- PR

Docs: bump minor versions of crates for `2506.0` distribution

---

Cargo.lock
examples/client-wasm-nodejs/package-lock.json
examples/client-wasm-web/package-lock.json
mithril-aggregator/Cargo.toml
mithril-client-wasm/Cargo.toml
mithril-client-wasm/ci-test/package-lock.json
mithril-client-wasm/package.json
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs
mithril-explorer/package-lock.json
mithril-relay/Cargo.toml
mithril-relay/src/relay/aggregator.rs
mithril-relay/src/relay/signer.rs
mithril-signer/Cargo.toml
mithril-signer/src/services/aggregator_client.rs

This PR includes the `Accept-Encoding: gzip, deflate` header for requests sent by the signer node and the Mithril client library, allowing the aggregator to respond with compressed data.
- Branch
- PR
Closes #2286

Feat: support compression in HTTP clients

---

Cargo.lock
mithril-test-lab/mithril-end-to-end/Cargo.toml
mithril-test-lab/mithril-end-to-end/src/assertions/exec.rs
mithril-test-lab/mithril-end-to-end/src/main.rs
mithril-test-lab/mithril-end-to-end/src/mithril/aggregator.rs
mithril-test-lab/mithril-end-to-end/src/mithril/infrastructure.rs
mithril-test-lab/mithril-end-to-end/src/utils/file_utils.rs
mithril-test-lab/mithril-end-to-end/src/utils/mithril_command.rs

Change protocol parameters to reduce e2e test flakiness.
We decrease the `k` parameter of the protocol to 145 to avoid an epoch gap due to a too low number of signatures (less than 150). 
This PR also print the last aggregator error in the console to help investigation when tests fail.
Example of the error shown in log when test fail
```
----------------------------------------------------------------------------------------------------
MITHRIL-AGGREGATOR LOGS - LAST 1 ERROR(S):
----------------------------------------------------------------------------------------------------
10293-{"msg":">> update_epoch_settings","v":0,"name":"mithril-aggregator","level":20,"time":"2025-02-12T11:57:08.013719446+01:00","hostname":"sfauvel-XPS-15-9560","pid":238456,"src":"MithrilEpochService"} …
```

Reduce e2e flakiness by changing protocol parameters

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder/enablers/epoch.rs
mithril-aggregator/src/dependency_injection/builder/support/stores.rs
mithril-aggregator/src/http_server/routes/status.rs
mithril-aggregator/src/services/epoch_service.rs
mithril-aggregator/src/store/epoch_settings_storer.rs
mithril-aggregator/src/tools/mocks.rs
mithril-explorer/__tests__/percent.test.js
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-explorer/src/components/ControlPanel/AggregatorStatus/index.js
mithril-explorer/src/utils.js

This PR fix a flakiness in mithril-end-to-end tests that manifest with a failure when bootstrapping the genesis certificate.
In a successful run:
1.  the stake distribution that we try to fetch (for the actual epoch, without offset) isn't immediately available since when we register them we do so with an offset of +1.
2. we don't see stake distribution unavailability errors because ... the epoch settings also isn't available because  the ones we are fetching in `EpochService::inform_epoch` are with offset -1, 0, +1 and the one we register in `handle_discrepancies_at_startup` are with offset 0, 1, 2.
3. the errors solve themself after epoch change, then the stake distribution registered in the previous epoch is now available and the epoch settings registered by …

Fix mithril-aggregator genesis bootstrap flakiness in e2e tests

---

Cargo.lock
docs/devbook/bump-versions/bump_versions.sh
examples/client-wasm-nodejs/package-lock.json
examples/client-wasm-web/package-lock.json
mithril-client-wasm/Cargo.toml
mithril-client-wasm/ci-test/package-lock.json
mithril-client-wasm/package.json
mithril-explorer/package-lock.json

This PR fix a regression in run times of mithril-stm tests.
Merge of #2282 changed the feature set used by `mithril-client-wasm`, including the activation of the `num-integer-backed` feature from the `mithril-client` crate.
With feature unification this have the side effect of enabling this slower backend for everyone when you run tests at the workspace level.
Removing this feature activation in client wasm is no-op since `mithril-stm` enforce it when building to wasm or windows.
- Branch
- PR
Here are run times before and after this change:
<details><summary>Expand</summary>
<p>
- Before:
```shell
cargo nextest run --features full,unstable --workspace -E "package(mithril-stm)"                                                                                                     
Finished …
```

fix: stm tests run time regression

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml

This PR reactivate publish test for `mithril-client`.
It was deactivated in aa55b34f57a71be972d73b7dee682ce39e96a206 because of an issue starting rust `1.84` that make `cargo publish --dry-run --no-verify` fails when a breaking version of a workspace dependency is yet to be published to crates.io.
With the release of the `2506.0` distribution, the breaking version `0.5.0` of `mithril-common` that triggered the problem with `mithril-client` is now [published to crates.io](https://crates.io/crates/mithril-common/0.5.0), solving the issue.
- Branch
- PR
Relates to #2285

chore(ci): reactivate publish test for `mithril-client`

---

Cargo.lock
docs/devbook/upgrade-repository-dependencies/upgrade_dependencies.sh
examples/client-wasm-nodejs/package-lock.json
examples/client-wasm-web/package-lock.json
mithril-client-wasm/Cargo.toml
mithril-client-wasm/ci-test/package-lock.json
mithril-client-wasm/package.json
mithril-client-wasm/src/client_wasm.rs
mithril-explorer/Makefile
mithril-explorer/next.config.js
mithril-explorer/package-lock.json
mithril-explorer/package.json
mithril-explorer/src/app/page.js
mithril-explorer/src/components/CertifyCardanoTransactionsModal/index.js
mithril-explorer/src/components/VerifyCertificate/CertificateVerifier.js
mithril-explorer/src/components/VerifyCertificate/VerifyCertificateModal.js
mithril-explorer/src/utils.js
mithril-explorer/src/wasm-client-helpers.js

This PR changes `mithril-explorer` dependency to `mithril-client-wasm` to use its main package directly instead of targeting a build artefact (`/dist/web`).
This is allowed by a small refactor of how the client wasm library is used in the explored so it's never included in Server Side Rendered builds since this cause the following error:
```
Error: ENOENT: no such file or directory, open '/mithril/mithril-explorer/.next/server/app/mithril_client_wasm_bg.wasm'
```
This error was avoided previously by using the `dist/web` version of the wasm client as it's "flagged" for client side only.
> [!NOTE]
> This change makes the explore compatible with the `bump-version` runbook script :partying_face: 
- Branch
- PR

explorer: use main `mithril-client-wasm` package

---

docs/website/blog/2025-02-04-glibc-minimum-requirement-change.md

Mithril dev blog review

---

docs/website/blog/2025-02-14-distribution-2506.md

This PR includes a **dev blog post announcing the release of the [`2506`](https://github.com/input-output-hk/mithril/releases/tag/2506.0) distribution**.
- Branch
- PR

Docs: add dev blog post for distribution `2506`

---

.github/workflows/ci.yml
Cargo.lock
demo/protocol-demo/Cargo.toml
examples/client-wasm-nodejs/package-lock.json
examples/client-wasm-web/package-lock.json
internal/mithril-metric/Cargo.toml
internal/mithril-metric/src/helper.rs
internal/mithril-persistence/Cargo.toml
mithril-aggregator/Cargo.toml
mithril-client-wasm/Cargo.toml
mithril-client-wasm/ci-test/package-lock.json
mithril-client-wasm/package.json
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-explorer/package-lock.json
mithril-relay/Cargo.toml
mithril-signer/Cargo.toml
mithril-stm/Cargo.toml
mithril-test-lab/mithril-aggregator-fake/Cargo.toml
mithril-test-lab/mithril-end-to-end/Cargo.toml

This PR removes unused dependencies in our `Cargo.toml`(s) and add a CI check to avoid adding them in the future.
[`cargo machete`](https://github.com/bnjbvr/cargo-machete) was used to track those unused dependencies (without and with `--with-metadata`) and is added to the CI for the check since it returns an error when it found at least one.
- Branch
- PR

Cleanup unused dependencies and auto CI check

---

.github/workflows/actions/prepare-distribution/action.yml
.github/workflows/ci.yml
CHANGELOG.md
docs/website/blog/2025-02-04-glibc-minimum-requirement-change.md
docs/website/root/compiled-binaries.mdx

This PR:
- bump the OS of the build runner in our CI from `ubuntu 20.04` to `ubuntu 22.04`
- update the `glibc` depreciation dev blog post to notify that the upgrade was enforced
- update the website minimum `glibc` requirement (only `next` version as the newly released `2506.0` distribution still support `glibc` `2.31`)
- update the github release notes minimum `glibc` requirement
- Branch
- PR
Relates to #2216

ci: Bump build runner to ubuntu 22.04

---

mithril-aggregator/Dockerfile
mithril-aggregator/Dockerfile.ci
mithril-client-cli/Dockerfile
mithril-client-cli/Dockerfile.ci
mithril-relay/Dockerfile
mithril-relay/Dockerfile.ci
mithril-signer/Dockerfile
mithril-signer/Dockerfile.ci
mithril-test-lab/mithril-devnet/README.md

This PR upgrade dockerfiles base images from Debian 11 to Debian 12 as the former is not supported any-more with the upgrade of the minimum supported `glibc` version to `2.35`.
- Branch
- PR
Relates to #2216

chore: upgrade dockerfiles base image version to Debian 12

---

.github/workflows/actions/toolchain-and-cache/action.yml
.github/workflows/ci.yml
.github/workflows/manual-publish-npm.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

This PR simplify the prefix for rust cache in CI.
Previously we had a version two times:  <pre>**v0**-rust-Linux-cache-**v5d9f9d8e-fb2b-4423-9700-8ae3bc62978e**-cargo-doc-Linux-e99b5096-e698f932 </pre>
Now, alongside a change of the repository `cache-version` to a simple `2`: <pre>**v2**-rust-Linux-cache-cargo-doc-Linux-e99b5096-e698f932 </pre>
- Branch
- PR

refactor(ci): use cache-version instead of 'v0-' in rust cache key prefix

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/signable_builder/interface.rs

This PR fix build of the wasm library that's failing since release of `rust 1.85`.
```shell
$ npm run build:node                                                                                                                   
> @mithril-dev/mithril-client-wasm@0.8.4 build:node                                                                                     
> wasm-pack build --target nodejs --out-dir dist/node $WASM_PACK_ARGS                                                                   
[INFO]: 🎯  Checking for the Wasm target...                                                                                             
[INFO]: 🌀  Compiling to Wasm...                                                                                                        
Compiling mithril-common …
```

Fix wasm build in rust 1.85

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db_v2/show.rs
mithril-client/Cargo.toml
mithril-client/Makefile
mithril-client/src/cardano_database_client/api.rs
mithril-client/src/cardano_database_client/download_unpack.rs
mithril-client/src/cardano_database_client/proving.rs
mithril-client/src/file_downloader/interface.rs
mithril-common/Cargo.toml
mithril-common/src/entities/cardano_database.rs
mithril-common/src/messages/cardano_database.rs

To avoid creating a breaking change in the client whenever a new location is introduced (e.g. decentralized storage).
we add a fallback variant in the artifact location types for the Incremental Cardano DB.
This PR implements an Unknown variant with the #[serde(other)] macro (as explained [here](https://serde.rs/variant-attrs.html#other)) in the artifact locations messages:
- Immutable locations
- Ancillary locations
- Digest locations
The `mithril-client-cli is adapted to not show unknown location.
- Branch
- PR
Relates to #2293

feat: Implement an Unknown variant in the artifact locations

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/client-cardano-database/.gitignore
examples/client-cardano-database/Cargo.toml
examples/client-cardano-database/README.md
examples/client-cardano-database/src/main.rs
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db_v2/download.rs
mithril-client-cli/src/commands/cardano_db_v2/mod.rs
mithril-client/Cargo.toml
mithril-client/src/cardano_database_client/immutable_file_range.rs

This PR includes an **example crate for the incremental Cardano database**.
- Branch
- PR
Closes #2330

Feat: add example crate for incremental Cardano database

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db_v2/download.rs

This PR includes enhancements to the disk space computation for incremental Cardano DB snapshot restoration in the client CLI.
It leverages updated artifact metadata to compute the required disk space for both full and partial restorations, adding ancillary files sizes when necessary.
Additionally, for partial restorations, a 10% safety margin is applied to ensure that sufficient disk space is available before download, as the computation uses the average size of an immutable file.
- Branch
- PR
Closes #2292

Feat: improve disk space calculation for Incremental DB Restoration

---

.github/workflows/nightly-dispatcher.yml
.github/workflows/scripts/notify-nightly-failure.js

This PR includes a fix for the notification script, ensuring that the job fails when email sending fails.
Before fix: https://github.com/input-output-hk/mithril/actions/runs/13677606215
After fix: https://github.com/input-output-hk/mithril/actions/runs/13677635751
Additionally, [secrets: inherit](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit) has been added to the reusable `test-notify-on-failure` workflow call, ensuring that all required secrets are passed to the notification job in scheduled workflows.
- Branch
- PR

Fix: `notify-on-failure` job succeeds despite email sending failure

---

.github/pull_request_template.md
DEV-ADR.md

This PR add a "code ADR" file to the `mithril-common` project in order to details project specific decisions that would be to specific to fit our website ADR blog.
- Branch
- PR
Relates to #2342

Code ADR for mithril-common

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/file_uploaders/interface.rs
mithril-client/Cargo.toml
mithril-client/src/file_downloader/retry.rs

Remove flakiness in test for `upload_retries` and `download_retries`
On windows, a call to `tokio::time::sleep` takes 10ms more than the duration specify.
It results that the duration is greater than what we expected after some retries.
Discussed here: [https://github.com/tokio-rs/tokio/discussions/4473](https://github.com/tokio-rs/tokio/discussions/4473)
This PR fix this issue by adding an assertion at each retry to check the delay between the last attempt instead of the global duration.
- Branch
- PR

Remove flakiness on should delay between retries tests

---

Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/cardano_database_client/download_unpack.rs
mithril-client/src/cardano_database_client/proving.rs
mithril-client/src/file_downloader/interface.rs
mithril-client/src/lib.rs
mithril-client/src/utils/mod.rs
mithril-client/src/utils/vec_deque_extensions.rs
mithril-client/src/utils/vec_extensions.rs
mithril-common/Cargo.toml
mithril-common/src/entities/file_uri.rs
mithril-common/src/messages/cardano_database.rs

This PR refactor the way cardano database v2 files are downloaded in the `mithril-client`:
- Unified download system for immutables in ancillary:
- allowing them to be in the same join set
- download tasks are now precomputed
- Fail early: as soon as the last location fails when downloading a files (instead of failing at the very end of the process)
- Continuously download `max_parallel_downloads` files:  No more threshold effect because of chunking
> [!NOTE]
> Those commands are run on a 1 Gbit/s download speed internet connection
Before, 10k immutables download took ~33 seconds:
```shell
$./mithril-client --unstable --run-mode dev cardano-db-v2 download latest --start 7345
1/6 - Checking local disk info…
2/6 - Fetching the certificate and verifying the certificate chain…
Certificate …
```

refactor(mithril-client): Optimize cardano db artifacts download

---

Cargo.lock
mithril-stm/Cargo.toml
mithril-stm/src/error.rs
mithril-stm/src/key_reg.rs
mithril-stm/src/multi_sig.rs

If there is any identity element in the following vectors:
```
let transmuted_vks: Vec<blst_p2> = vks.iter().map(vk_from_p2_affine).collect();
let transmuted_sigs: Vec<blst_p1> = signatures.iter().map(sig_to_p1).collect();
```
The content of the following vectors in `mithril-stm/src/multi_sig.rs`:
```
let grouped_vks = p2_affines::from(transmuted_vks.as_slice());
let grouped_sigs = p1_affines::from(transmuted_sigs.as_slice());
```
Becomes vectors full of identity elements.
This PR includes the changes to avoid having an identity element in signature and verification lists.
In `mithril-stm/src/multi_sig.rs`:
- `Signature::verify` function is updated: If signature is an infinity value, it returns an error.
- `VerificationKeyPoP::check` function is updated: If the verification key is an …

Fix BLST bindings: Error handling for infinite values of sigs and vks

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/digest.rs
mithril-aggregator/src/dependency_injection/builder/protocol/artifacts.rs
mithril-client/Cargo.toml
mithril-client/src/cardano_database_client/proving.rs

Compress the digests file in the digests artifact builder for the cloud locations of the Incremental Cardano DB.
:hand: We create the digests archive in self.configuration.get_snapshot_dir()?.join("digests". Is it OK ?
- Branch
- PR
Closes #2356

Compress the digests file uploaded on gcp

---

Cargo.lock
docs/website/adr/009-database-migration-squashing.md
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/mod.rs
internal/mithril-persistence/src/database/version_checker.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/database_command.rs
mithril-aggregator/src/commands/mod.rs
mithril-aggregator/src/database/migration.rs
mithril-signer/Cargo.toml
mithril-signer/src/commands/database_command.rs
mithril-signer/src/commands/mod.rs
mithril-signer/src/lib.rs
mithril-signer/src/main.rs

This PR includes the implementation of a minimum node version check for squash database migrations. In case of a version gap, an error message guides users to upgrade their node accordingly.
A new command has been added to both aggregator and signer nodes to manually trigger database migrations:
```bash
mithril-aggregator database migrate --stores-directory ./stores
```
```bash
mithril-signer database migrate --stores-directory ./stores
```
- Branch
- PR
Closes #2357

Feat: verify minimum node version with squash database migration

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/database_command.rs
mithril-aggregator/src/commands/serve_command.rs
mithril-aggregator/src/services/upkeep.rs
mithril-aggregator/src/tools/mod.rs
mithril-aggregator/src/tools/vacuum_tracker.rs

This PR includes a fix for the API unavailability during epoch transitions by moving database vacuum operation from the upkeep service to aggregator startup.
The main changes are:
- Removed vacuum operation from the epoch transition process
- Created a `VacuumTracker` utility that tracks when the last vacuum operation was performed
- Added a controlled vacuum process at aggregator startup with a minimum interval (1 week)
- Added a clap command to execute vacuum manually
- Branch
- PR
Closes #2364

Feat: move database vacuum to aggregator startup to avoid API interruptions during epoch transitions

---

Cargo.lock
mithril-stm/CHANGELOG.md
mithril-stm/Cargo.toml
mithril-stm/src/eligibility_check.rs
mithril-stm/src/error.rs
mithril-stm/src/key_reg.rs
mithril-stm/src/merkle_tree.rs
mithril-stm/src/multi_sig.rs
mithril-stm/src/stm.rs

This PR covers:
- Implementations right after their structures,
- Property tests re-ordered,
- Branch
- PR
Relates to #2369

Organize STM code

---

Cargo.lock
DEV-ADR.md
docs/website/adr/010-http-status-code.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/reply.rs
mithril-aggregator/src/http_server/routes/signer_routes.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/state_machine.rs
mithril-signer/src/services/aggregator_client.rs
openapi.yaml

- a new 550 error code in the aggregator when signer registration is not opened yet
- increment following metrics on errors considered as a warning: 
- `signer_registration_success_since_startup_counter`
- `get_signer_registration_total_since_startup_counter metric`
- Create ADR to specify the reserved ranges of 4XX and 5XX codes that we can use in the Mithril nodes (see https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml)
- Branch
- PR
Closes #2363

Error messages as warning in signer

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder/mod.rs
mithril-aggregator/src/dependency_injection/containers.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/src/services/certifier/certifier_service.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs

This PR remove the deprecated `configuration` field from `DependencyContainer`.
This field was problematic as the `Configuration` structure is not fully validated, meaning that consumer of this attribute may have to re-validate the fields they needed, something not necessary as the field should have been validated when constructing the dependency builder.
Also, leaving this field as is would complicate #2384 work as the `Configuration` structure will likely not be used anymore in the `DependenciesBuilder` (used to build the container).
- Branch
- PR
Relates to #2384

refactor(aggregator): remove deprecated `configuration` field from `DependencyContainer`

---

mithril-install.sh

This PR includes the **bump of the minimum `glibc` version to `2.35` in the one-line installer script**.
- Branch
- PR
Relates to #2332

Chore: bump `glibc` requirement to `2.35+` in one-line installer

---

docs/website/versioned_docs/version-maintained/compiled-binaries.mdx
docs/website/versioned_docs/version-maintained/glossary.md
docs/website/versioned_docs/version-maintained/manual/develop/nodes/mithril-client-library-wasm.md
docs/website/versioned_docs/version-maintained/manual/develop/nodes/mithril-client-library.md
docs/website/versioned_docs/version-maintained/manual/develop/nodes/mithril-client.md
docs/website/versioned_docs/version-maintained/manual/develop/run-mithril-devnet.md
docs/website/versioned_docs/version-maintained/manual/getting-started/bootstrap-cardano-node.md

This PR includes the **rotation of the documentation with the release of the new `2513` distribution**.
- Branch
- PR
Relates to #2332

Docs: rotate documentation for `2513` distribution

---

docs/website/blog/2025-03-28-distribution-2513.md

This PR includes a **dev blog post announcing the release of the [`2513`](https://github.com/input-output-hk/mithril/releases/tag/2513.0) distribution**.
- Branch
- PR
Relates to #2332

Docs: add dev blog post for distribution `2513`

---

Cargo.lock
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/query/block_range_root/insert_block_range.rs
internal/mithril-persistence/src/database/query/cardano_transaction/insert_cardano_transaction.rs
internal/mithril-persistence/src/sqlite/condition.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/query/certificate/insert_certificate.rs
mithril-aggregator/src/database/query/signer/import_signer.rs
mithril-aggregator/src/database/query/stake_pool/insert_or_replace_stake_pool.rs
mithril-common/Cargo.toml
mithril-common/src/digesters/immutable_file_observer.rs
mithril-common/src/messages/cardano_transactions_proof.rs
mithril-common/src/test_utils/certificate_chain_builder.rs
mithril-signer/Cargo.toml
mithril-signer/src/database/query/stake_pool/insert_or_replace_stake_pool.rs
mithril-signer/src/store/mktree_store_sqlite.rs

This PR fix preemptively clippy lint added with `rust 1.86`:
- use `repeat_n` instead of `repeat(..).take(n)`
- use `next_back` instead of `last` on iterator to avoid walking through
the whole iterator
- simplify a `matches!` in `mithril-common::messages::cardano_transactions_proof`
- Branch
- PR

chore: anticipate rust `1.86`

---

.github/workflows/backward-compatibility.yml

This PR adds `CardanoDatabase` in the list of default signed entity type to verify in the Backward compatibility Github workflow (manual trigger and nightly scheduled). 
Result of a backward compatibility test that asses the signer node compatibility with `CardanoDatabase` from release `2450.0` (signer node version `0.2.221`): https://github.com/input-output-hk/mithril/actions/runs/14336068335
- Branch
- PR
Relates to #2409

CI: include `CardanoDatabase` in the backward compatibility test 

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/immutable.rs
mithril-aggregator/src/services/snapshotter/compressed_archive_snapshotter.rs
mithril-aggregator/src/services/snapshotter/interface.rs
mithril-aggregator/src/services/snapshotter/test_doubles.rs

This PR fix the computation of the immutable files average and total size in cardano database v2.
It was incorrectly based on the `immutables_storage_dir` of the artifact builder, since this directory contains the archives of each immutable trio the computation always returned `0`.
As the artifact builder has no knowledge of the cardano node database, the actual computation was moved to the snapshotter.
- Branch
- PR
Relates to #2415

fix(aggregator): incorrect immutable files average and total size in cardano database v2

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/snapshotter/compressed_archive_snapshotter.rs
mithril-aggregator/src/services/snapshotter/mod.rs
mithril-aggregator/src/services/snapshotter/test_doubles.rs
mithril-aggregator/src/tools/file_archiver/appender.rs
mithril-client/Cargo.toml
mithril-client/src/cardano_database_client/download_unpack/download_task.rs
mithril-client/src/file_downloader/mock_builder.rs
mithril-client/src/snapshot_client.rs
mithril-client/src/utils/ancillary_verifier.rs
mithril-common/Cargo.toml
mithril-common/src/test_utils/dir_eq.rs
mithril-common/src/test_utils/mod.rs

This PR make the aggregator copy the files that are included in an ancillary archive into a temporary folder so those files doesn't evolve while the snapshotting of ancillary is in progress, avoiding mismatch between sha of files in the ancillary manifest and the sha of files in the archive.
This PR also add a new test macro: `assert_dir_eq!` that allow comparison of two directories together or, more interestingly,  against a string that codify the expected dir structure, i.e:
```
* folder 1/
** file 1
** file 2
* folder 2/
** file 3
* 100
* 20
* 300
* abc
* xyz
```
- Branch
- PR
Relates to #2362

fix(aggregator): ancillary signing on evolving files

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder/enablers/cardano_node.rs
mithril-aggregator/src/dependency_injection/builder/enablers/epoch.rs
mithril-aggregator/src/dependency_injection/builder/enablers/misc.rs
mithril-aggregator/src/dependency_injection/builder/enablers/ticker.rs
mithril-aggregator/src/dependency_injection/builder/mod.rs
mithril-aggregator/src/dependency_injection/builder/protocol/artifacts.rs
mithril-aggregator/src/dependency_injection/builder/protocol/certificates.rs
mithril-aggregator/src/dependency_injection/builder/protocol/proving.rs
mithril-aggregator/src/dependency_injection/builder/protocol/signables.rs
mithril-aggregator/src/dependency_injection/builder/support/compatibility.rs
mithril-aggregator/src/dependency_injection/builder/support/observability.rs
mithril-aggregator/src/dependency_injection/builder/support/sqlite.rs
mithril-aggregator/src/dependency_injection/builder/support/stores.rs
mithril-aggregator/src/dependency_injection/builder/support/upkeep.rs
mithril-aggregator/src/dependency_injection/containers/dependencies_container.rs
mithril-aggregator/src/dependency_injection/containers/dependency_container.rs
mithril-aggregator/src/dependency_injection/containers/mod.rs
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/http_server/routes/statistics_routes.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/tests/test_extensions/runtime_tester.rs

* creation of a macro to create getter functions
* renaming of `DependencyContainer` to `DependenciesContainer`
* change `DependencyContainer attributes visibility from 'pub' to 'pub(crate)' to identify unused attribute for those which are not used in integration test
* remove unused attribute in `DependenciesContainer`
* refactor some function to align `attribute`, `getter` and `build` names
* refactor test to avoid usage of container attribute only for test
* remove dead functions in integration tests
- Branch
- PR
We looked into the possibility of deleting code for attributes used only once. 
In the end, this removes very little code and makes it more difficult to detect the double creation of an instance.
Similarly, the creation of sub-structures to …

Simplify injection container in aggregator

---

Cargo.lock
docs/runbook/genesis-manually/README.md
docs/website/root/manual/develop/nodes/mithril-aggregator.md
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/genesis_command.rs
mithril-aggregator/src/database/repository/epoch_settings_store.rs
mithril-aggregator/src/dependency_injection/builder/enablers/cardano_node.rs
mithril-aggregator/src/dependency_injection/builder/mod.rs
mithril-aggregator/src/dependency_injection/builder/support/stores.rs
mithril-aggregator/src/dependency_injection/containers/genesis.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/store/epoch_settings_storer.rs
mithril-aggregator/src/store/mod.rs
mithril-aggregator/src/tools/genesis.rs

This PR introduces a specific configuration for the aggregator's `genesis` command to avoid relying on the `serve` configuration.
- Branch
- PR
Relates to #2384

Refactor: Simplify the configuration of genesis command in aggregator

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/ancillary.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/digest.rs
mithril-aggregator/src/artifact_builder/cardano_database_artifacts/immutable.rs
mithril-aggregator/src/lib.rs
mithril-aggregator/src/runtime/error.rs
mithril-aggregator/src/services/upkeep.rs
mithril-client/Cargo.toml
mithril-client/src/lib.rs
mithril-client/src/snapshot_client.rs
mithril-common/Cargo.toml
mithril-common/src/logging.rs
mithril-common/src/test_utils/memory_logger.rs
mithril-common/src/test_utils/mod.rs
mithril-relay/Cargo.toml
mithril-signer/Cargo.toml
mithril-signer/src/lib.rs
mithril-signer/src/runtime/error.rs
mithril-signer/src/services/aggregator_client.rs
mithril-signer/src/services/upkeep_service.rs

This PR add the `MemoryDrainForTest` that write log to memory, it allow to remove the need to write logs to files for tests that needs to check log content.
Logging to file in test was error prone as it was difficult to guarantee that all logs were effectively flushed to the file before the assertions, leading to error, often in the hydra ci:
- `mithril-common`: Add `MemoryDrainForTest` in test tools
- A [`slog::Drain`](https://docs.rs/slog/2.7.0/slog/trait.Drain.html) that write logs to in memory `Vec<String>` shared using a `Arc<RwLock<..>>`
- Optimized for tests, not speed, **it should not be used in production**.
- It's created along a `MemoryDrainForTestInspector`:
- it can search for log entries or if a log was written
- this struct allow to move the `MemoryDrainForTest` to the …

test: use a in memory logger for tests that needs to check logs

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/runtime/state_machine.rs
mithril-signer/Cargo.toml
mithril-signer/src/runtime/state_machine.rs

This PR changes the type of wait that is done between cycles of aggregator and signer states machines.
Instead of using a simple `sleep` that will always wait, they now uses `interval` so the time that was passed running the last cycle is taken into account in the amount of time to sleep.
This means that if the last cycle was longer that the set `run_interval` the state machines will execute their next cycle immediately.
The logs at the end of each cycle has been updated to this change:
```json
{
"msg": "… Cycle finished", "time": "2025-04-30T16:31:33.83372259+02:00",
"run_interval_in_ms": 125, "approximate_next_cycle_time": "16:31:33.957",
"name": "mithril-signer", "level": 30, "src": "StateMachine" 
}
{
"msg": "New cycle: ReadyToSign - 27", "time": "2025-04-30T16:31:33.95800507+02:00", …
```

Optimize signer and aggregator state machines run interval

---

docs/website/blog/2025-03-28-distribution-2513.md
docs/website/blog/2025-05-05-distribution-2517.md

This PR includes a **dev blog post announcing the release of the [`2517`](https://github.com/input-output-hk/mithril/releases/tag/2517.0) distribution**.
- Branch
- PR
Relates to #2410

Docs: add dev blog post for distribution `2517`

---

Cargo.lock
internal/mithril-doc-derive/Cargo.toml
internal/mithril-doc-derive/src/lib.rs
internal/mithril-doc/Cargo.toml
internal/mithril-doc/src/extract_clap_info.rs
internal/mithril-doc/src/lib.rs
internal/mithril-doc/src/markdown_formatter.rs
internal/mithril-doc/src/test_doc_macro.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/commands/config_association.rs
mithril-aggregator/src/commands/database_command.rs
mithril-aggregator/src/commands/era_command.rs
mithril-aggregator/src/commands/genesis_command.rs
mithril-aggregator/src/commands/mod.rs
mithril-aggregator/src/commands/serve_command.rs
mithril-aggregator/src/commands/tools_command.rs
mithril-common/Cargo.toml
mithril-common/src/test_utils/mod.rs
mithril-signer/Cargo.toml
mithril-signer/src/main.rs

This PR includes enhancements to the documentation tool, enabling it to support subcommand configurations.
- Branch
- PR
Additionally, an assessment of the differences between the documentation generated by `mithril-doc` and the currently published website documentation has been completed. The identified differences are as follows:
- Default configuration discrepancies: There are mismatches between the default configuration structure and the serve command configuration structure (fields are not exactly the same). In addition, default configuration details for subcommands are missing. The `mithril-doc` merge mechanism for default configurations may need improvement.
- Environment variable representation: The generated documentation does not take into account environment …

Feat: extend documentation tool for subcommand configurations

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client/Cargo.toml
mithril-client/src/cardano_database_client/download_unpack/internal_downloader.rs
mithril-client/src/snapshot_client.rs
mithril-client/src/utils/bootstrap_files.rs
mithril-client/src/utils/mod.rs

This PR includes the hotfix release in the distribution `2517.1`, adding the missing `protocolMagicId` file when restoring a snapshot.
- Branch
- PR
Relates to #2464

Fix: Apply hot fix for client restoration

---

docs/website/blog/2025-05-05-distribution-2517.md
docs/website/blog/2025-05-07-client-security-advisory.md

This PR includes a dev blog post for the [Mithril snapshots for Cardano database could be compromised by an adversary ](https://github.com/input-output-hk/mithril/security/advisories/GHSA-qv97-5qr8-2266) security advisory
- Branch
- PR

Docs: add dev blog post for client security advisory

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db/download.rs
mithril-client-cli/src/commands/cardano_db_v2/download.rs
mithril-client-cli/src/utils/cardano_db.rs
mithril-client/Cargo.toml
mithril-client/src/cardano_database_client/download_unpack/internal_downloader.rs
mithril-client/src/snapshot_client.rs
mithril-client/src/utils/mod.rs

Objective is to warn users using Client CLI and Client library that : 
- ancillary files are not signed by Mithril 
- without including ancillary files, fast bootstrap will not be available
- Branch
- PR
Closes #2459

Add warning in client about ancillary files

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/file_uploaders/cloud_uploader/gcloud_backend.rs
mithril-aggregator/src/file_uploaders/cloud_uploader/mod.rs
mithril-aggregator/src/file_uploaders/interface.rs
mithril-client/Cargo.toml
mithril-client/src/file_downloader/retry.rs

This PR try to fix the upload of files to GCP storages and enhance logging of failures when a retried operation fails.
The upload of files to GCP after merging #2475 fails when applying the ACL to make the file public but the associated error is not log (when only see that it failed after retrying x time).
After investigating the internal difference between the new and old backend crate we found a difference: the previous crate was enforcing itself [GCP url encoding rules](https://cloud.google.com/storage/docs/request-endpoints#encoding) but the new crate doesn't.
This PR align the behavior of the new implementation with the previous one by enforcing manually the encoding rule.
- Add the source error of the last failure when all retries fails in `mithril-aggregator` file upload and …

aggregator: fix setting public access to files uploaded to GCP storage

---

mithril-install.sh

This PR includes enhancements to the `mithril-install` script to ensure proper error handling when executing the downloaded binary (with `--version` argument), preventing misleading success messages.
- Branch
- PR

Fix: improve error handling in `mithril-install` script

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/services/snapshotter/compressed_archive_snapshotter.rs
mithril-aggregator/src/services/snapshotter/interface.rs

This PR includes a fix that adds the two most recent ledger state snapshots to the ancillary archive. 
It improves the reliability of Cardano node fast bootstrap, preventing full chain replays when restarting the node.
- Branch
- PR
Closes #2474

Fix: include the two latest ledger state snapshots in the ancillary archive

---

.github/workflows/ci.yml

This PR includes updates to the `test` job in the CI. It now runs tests across the full workspace on macOS and Windows, skipping unsupported packages.
- Branch
- PR
Closes #2486

Test: execute full workspace tests on macOS/Windows excluding unsupported packages

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder/enablers/misc.rs
mithril-aggregator/src/http_server/routes/signatures_routes.rs
mithril-aggregator/src/metrics/service.rs
mithril-aggregator/src/services/signature_consumer/fake.rs
mithril-aggregator/src/services/signature_consumer/interface.rs
mithril-aggregator/src/services/signature_consumer/noop.rs
mithril-aggregator/src/services/signature_processor.rs

We want to record the number of incoming signatures coming from the DMQ network. Once the DMQ is delivering enough signatures to reach the quorum, we will be able to sunset signature publication to the aggregator REST API.
- Extend the `SignatureConsumer` trait to expose the origin metric of the consumer
- increment the `get_signature_registration_total_received_since_startup` metric with the origin for every signature processed
- Modify usage of metric `signature_registration_total_received_since_startup` incremented in HTTP server when calling register-signatures with `HTTP` value instead of `origin_tag`
- remove usage of `origin_tag` header in register-signatures endpoint
- Branch
- PR
Closes #2478

Record signatures origin in the signature processor

---

Cargo.lock
mithril-common/Cargo.toml
mithril-common/src/test_utils/test_http_server.rs

This PR includes an update to the `Drop` implementation of `TestHttpServer`, removing the `recv_timeout` call that was previously used to wait for the server thread to signal its shutdown.
This change fixes flakiness in CI tests, likely caused by the blocking behavior of `block_on`, which can delay the server thread's shutdown signal.
- Branch
- PR

Fix: Simplify `TestHttpServer` `Drop` logic to prevent test flakiness

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_db/download.rs
mithril-client-cli/src/commands/cardano_db_v2/download.rs

Read argument ancillary_verification_key from both clap arguments and configuration files by : 
- removing clap requirement
- read ancillary_verification_key from both clap and configuration files
- add custom verification step and throw error if include_ancillary is true and ancillary_verification_key is not provided
in both v1 and v2.
- Branch
- PR
Closes #2491

feat: read ancillary verification key from both clap arguments and configuration files

---

Cargo.lock
mithril-client/Cargo.toml
mithril-client/src/cardano_database_client/download_unpack/internal_downloader.rs
mithril-client/src/snapshot_client.rs
mithril-client/src/utils/mod.rs
mithril-client/src/utils/unexpected_downloaded_file_verifier.rs

This PR add a two phase tool in the `mithril-client` that:
1. compute the expected state of the immutable folder after download
2. remove any file or directory that is not in the expectation
3. report offenders in a warning log
The removal is executed even if the download fail.
- The tool can be tricked in some specific case, i.e: download of a Range of immutable, if a downloaded immutable archive contains a immutable below the downloaded range it won't be identified
- The tool enforce the current directory structure of the Cardano node immutable directory: if the node change it's immutable naming scheme this tool will need to be adapted, else it will remove the files with the new scheme
- The reported offenders are only in a warning log, if library users don't enable the logs they won't …

feat: cleanup unexpected files in immutable folder after download

---

.github/workflows/test-client.yml
Cargo.lock
docs/website/root/manual/develop/nodes/mithril-client.md
docs/website/root/manual/getting-started/bootstrap-cardano-node.md
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/tools/snapshot_converter.rs
mithril-client-cli/src/utils/github_release_retriever/interface.rs
mithril-client-cli/src/utils/github_release_retriever/reqwest.rs

This PR includes the documentation of the unstable `mithril-client` CLI command that converts a ledger state snapshot from the `InMemory` format to another flavor (`LMDB` or `Legacy`).
It also adds verification steps in the CI to ensure the command executes correctly across multiple environments (Ubuntu, macOS, and Windows).
- Branch
- PR
Relates to #2492

Feat: documentation and CI tests for UTxO-HD ledger state snapshot conversion `mithril-client` CLI command

---

Cargo.lock
mithril-client-cli/Cargo.toml
mithril-client/Cargo.toml
mithril-client/src/cardano_database_client/download_unpack/download_unpack_options.rs

This PR lower the default value of `DownloadUnpackOptions.max_parallel_downloads` from `100` to `20`.
Investigation (cf: [this comment](https://github.com/input-output-hk/mithril/issues/2493#issuecomment-2959330896)) found that starting from 5, the `max_parallel_downloads` value did not really matter for download total time, as such lowering it will have no impact on those times and may lower overhead of the client-cli.
- Branch
- PR
Relates to #2493

client-lib/client-cli: calibrate max parallel dl

---

.github/workflows/test-client.yml

This PR includes the renaming of the uploaded artifact in case of a failure in the `test-mithril-client-wasm` job of the `Mithril Client multi-platform test` GitHub workflow.
- Branch
- PR

fix: rename artifact on wasm test failure in `Mithril Client multi-platform test` workflow.

---

Cargo.lock
Cargo.toml
README.md
internal/mithril-ticker/Cargo.toml
internal/mithril-ticker/Makefile
internal/mithril-ticker/README.md
internal/mithril-ticker/src/lib.rs
internal/mithril-ticker/src/ticker_service.rs
mithril-aggregator/Cargo.toml
mithril-aggregator/src/dependency_injection/builder/enablers/ticker.rs
mithril-aggregator/src/dependency_injection/builder/mod.rs
mithril-aggregator/src/dependency_injection/containers/serve.rs
mithril-aggregator/src/runtime/runner.rs
mithril-aggregator/tests/test_extensions/aggregator_observer.rs
mithril-common/Cargo.toml
mithril-common/src/lib.rs
mithril-signer/Cargo.toml
mithril-signer/src/dependency_injection/builder.rs
mithril-signer/src/dependency_injection/containers.rs
mithril-signer/src/runtime/runner.rs
mithril-signer/tests/test_extensions/certificate_handler.rs
mithril-signer/tests/test_extensions/state_machine_tester.rs

This PR extract the `TickerService` from `mithril-common` into a dedicated `mithril-ticker` internal crate. This allow to remove a unused dependency for `mithril-client`.
- Branch
- PR
Relates to #2392

Split `mithril-common` phase 2: extract Mithril ticker

---

CHANGELOG.md
Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/http_server/routes/router.rs
mithril-aggregator/src/services/aggregator_client.rs
mithril-client/Cargo.toml
mithril-client/src/aggregator_client.rs
mithril-signer/Cargo.toml
mithril-signer/src/services/aggregator_client.rs
openapi.yaml

This PR removes the HTTP response status code `412 Precondition Failed` returned by the aggregator on OpenAPI version mismatch and adds a client-side warning log when a mismatch is detected.
- Branch
- PR
Closes #2535

feat: revise OpenAPI compatibility enforcement

---

Cargo.lock
mithril-common/Cargo.toml

This PR includes the **update of the `mithril-stm` package version constraint in the `mithril-common` crate**.
- Branch
- PR
Relates to #2488

chore: bump `mithril-stm` dependency version constraint in `mithril-common`

---

.github/workflows/actions/publish-crate-package/action.yml
.github/workflows/actions/publish-npm-package/action.yml
.github/workflows/ci.yml

This PR publish of wasm packages to npm when Cargo.toml version dont match package.json.
Also it adds a new check step in the CI to ensure that both version matches (only for `mithril-client-wasm` as it's the only wasm crate right now).
Failure example: https://github.com/input-output-hk/mithril/actions/runs/15685837062/job/44188672258#step:13:26
- Branch
- PR
Closes #2585

fix(ci): publish of wasm packages to npm when Cargo.toml version dont match package.json

---

.github/workflows/test-client.yml

This PR includes the separation of the Cardano Database snapshot download and the Ledger state snapshot conversion into two distinct steps in the `test-docker` job of the `Mithril Client multi-platform test` GitHub workflow.
The step that removes downloaded artifacts to free up disk space has also been reintroduced, as files are now persisted between steps.
- Branch
- PR
Closes #2578

ci: split Cardano DB download and ledger state snapshot conversion in `test-docker` job

---

.prettierignore
CHANGELOG.md
README.md
SECURITY.md
docs/website/blog/2022-10-11-keys-certification-badge/index.md
docs/website/blog/2024-12-17-era-switch-pythagoras.md
docs/website/blog/2025-06-17-client-cli-cardano-database-backends.md
docs/website/root/manual/operate/run-signer-node.md
docs/website/root/mithril/advanced/mithril-protocol/protocol.md
docs/website/root/mithril/advanced/threat-model.md
docs/website/versioned_docs/version-maintained/manual/operate/run-signer-node.md
docs/website/versioned_docs/version-maintained/mithril/advanced/mithril-protocol/protocol.md
docs/website/versioned_docs/version-maintained/mithril/advanced/threat-model.md

This PR applies new formatting rules from [prettier 3.6](https://prettier.io/blog/2025/06/23/3.6.0).
- Branch
- PR

prettier 3.6

---

Cargo.lock
internal/cardano-node/mithril-cardano-node-chain/Cargo.toml
internal/cardano-node/mithril-cardano-node-chain/src/entities/datum.rs
internal/mithril-doc-derive/Cargo.toml
internal/mithril-doc-derive/src/doc.rs
internal/mithril-doc-derive/src/lib.rs
internal/mithril-persistence/Cargo.toml
internal/mithril-persistence/src/database/version_checker.rs
mithril-client-cli/Cargo.toml
mithril-client-cli/src/commands/cardano_stake_distribution/download.rs
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-stm/Cargo.toml
mithril-stm/src/aggregate_signature/mod.rs
mithril-stm/src/bls_multi_signature/mod.rs

This PR includes the preparatory work for migrating the project codebase to the Rust `2024` edition, as described in the [transitioning guide and tooling](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html).
- Ran `cargo update`
- Fixed missing import and clippy warnings following the `cargo update`
- Refactoring to anticipate clippy warnings with the `2024` edition (`returning the result of a 'let' binding from a block`)
- Run `cargo fix --edition`
- Remove `_2021` suffixes from macro expressions added by `cargo fix --edition`
- Update the root `Cargo.toml` and set the edition field to the `2024` edition
- Run `cargo clippy` and `cargo nextest`
- Run `cargo fmt`
- Branch
- PR
Relates to #2582

Prepare project upgrade to Rust `2024` edition

---

.github/workflows/scripts/run-wasm-tests-browser-headless.py
.github/workflows/test-client.yml

This PR uploads Chrome console and driver logs, and Firefox driver logs, when WASM headless tests fail in the `test-mithril-client-wasm` step of the `Mithril Client multi-platform test` workflow.
Note: Firefox WebDriver does not currently support retrieving browser console logs via `get_log('browser')`.
- Branch
- PR
Closes #2579

ci: improve `test-mithril-client-wasm` job debugging by uploading logs as artifacts

---

Cargo.lock
mithril-aggregator/Cargo.toml
mithril-aggregator/src/database/query/certificate/get_certificate.rs
mithril-aggregator/src/database/query/certificate/insert_certificate.rs
mithril-aggregator/src/database/record/certificate.rs
mithril-aggregator/src/database/repository/certificate_repository.rs
mithril-client/Cargo.toml
mithril-client/src/certificate_client/verify.rs
mithril-common/Cargo.toml
mithril-common/src/certificate_chain/certificate_verifier.rs
mithril-common/src/crypto_helper/tests_setup.rs
mithril-common/src/test_utils/certificate_chain_builder.rs
mithril-common/src/test_utils/mock_extensions.rs
mithril-common/src/test_utils/mod.rs

This PR enhance the certificate chain builder and add propose a tooling to create mock in a standardized way.
- Rework `CertificateChainBuilder`:
- Now `.build()` return a `CertificateChainFixture` that's contains the same data as the previous returned tuple (the chain ordered from latest to genesis and the genesis verifier)
- The addition of `CertificateChainFixture` allow to attach utility methods related to the produced certificates:
- `genesis_certificate(&self)`: shortcut to get the generated genesis
- `chain_reversed`: return a copy of the generated chain reversed
- `certificate_path_to_genesis`: return a list with the given certificate hash  and all it's previous certificates, useful when testing certificate chain validation
- Additionally `CertificateChainFixture` implement:
- …

test:enhance certificate chain builder and mock build

---

.github/workflows/actions/prepare-distribution/action.yml
.github/workflows/ci.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

This PR includes improvements to the GitHub release notes by adding missing information:
- A `Download a binary asset` section explaining how to use the one-line installer
- A `Download a Docker image` section with a table listing Docker image tags and registry URLs
---
---
- Branch
- PR
Closes #2638

ci: add extra information to release notes

---

.github/workflows/actions/prepare-distribution/action.yml

This PR includes a fix for the release note following the merge of the PR https://github.com/input-output-hk/mithril/pull/2646.
- Branch
- PR
Relates to #2638

fix: escape `$(pwd)` and format installation commands

---

Cargo.lock
internal/mithril-build-script/Cargo.toml
internal/mithril-build-script/src/open_api.rs
internal/tests/mithril-api-spec/Cargo.toml
internal/tests/mithril-api-spec/src/apispec.rs

This PR includes the replacement of [`serde_yaml`](https://crates.io/crates/serde-yaml) by [`serde_yml`](https://crates.io/crates/serde_yml) in `mithril-build-script` and `mithril-api-spec`, as `serde_yaml` is no longer maintained.
- Branch
- PR
Closes #2639

chore: replace `serde_yaml` with `serde_yml`

---

Cargo.lock
internal/mithril-metric/Cargo.toml

This PR fix a compilation issue with `mithril-metric` introduced by the merge of #2650.
- Branch
- PR
Relates to #2580

fix: mithril metric tests build

---

internal/cardano-node/mithril-cardano-node-internal-database/README.md
internal/mithril-build-script/README.md
mithril-client-wasm/README.md
mithril-client/README.md
mithril-common/README.md
mithril-relay/README.md
mithril-stm/README.md

This PR includes make all published projects have the same set of badge in the same order:
- CI badge
- Package repository badge (crates.io or npmjs.com)
- License
- Discord (IOG tech community)
Also all badges now links to their associated page instead of a link to the badge image.
- Branch
- PR

chore: add and unify badges to all published projects

---

.github/workflows/actions/prepare-distribution/action.yml

This PR includes a fix that restores a section missing from the `unstable` release notes (`Fetch the latest version of the unstable tag`) due to an incorrect input reference. The `version-name` input was removed in favor of `tag`.
This regression was introduced after the merge of #2646.
- Branch
- PR
Relates to #2638

fix: restore missing section in unstable release notes

---

.github/workflows/backward-compatibility.yml
.github/workflows/scripts/download-distribution-binaries.sh

This PR includes support for specifying a release to test (default: `unstable`) in the `Backward compatibility` GitHub workflow. It also adds the ability to define which release is used to build the e2e binary (default: `unstable`).
- Branch
- PR
Closes #2093

ci: add support for testing a specific release in `Backward compatibility` workflow

---

mithril-install.sh

This PR includes a fix to the one-line installer script to ensure the provided install path is writable before proceeding. This avoids misleading errors when the path is not writable.
The creation of the install path directory has also been moved after the command-line argument parsing step to avoid attempting to create a directory with an undefined value.
- Branch
- PR

fix: add write access check for install path in one-line installer

---

Cargo.lock
DEV-ADR.md
flake.nix
internal/cardano-node/mithril-cardano-node-chain/Cargo.toml
internal/cardano-node/mithril-cardano-node-internal-database/Cargo.toml
internal/mithril-aggregator-client/Cargo.toml
internal/mithril-dmq/Cargo.toml
internal/mithril-era/Cargo.toml
internal/mithril-metric/Cargo.toml
internal/mithril-persistence/Cargo.toml
internal/mithril-resource-pool/Cargo.toml
internal/signed-entity/mithril-signed-entity-preloader/Cargo.toml
internal/tests/mithril-api-spec/Cargo.toml
mithril-aggregator/Cargo.toml
mithril-client-cli/Cargo.toml
mithril-client/Cargo.toml
mithril-common/Cargo.toml
mithril-common/Makefile
mithril-common/src/api_version.rs
mithril-common/src/crypto_helper/cardano/key_certification.rs
mithril-common/src/entities/block_range.rs
mithril-common/src/lib.rs
mithril-relay/Cargo.toml
mithril-signer/Cargo.toml
mithril-test-lab/mithril-end-to-end/Cargo.toml

This PR add a new Dev-Adr entries, "Guidelines for crate test utilities", and remove the `test_tools` and `full` features from `mithril-common` in order to enhance Rust compiler ability to reuse built artifacts.
- Branch
- PR
Closes #2662, Relates to #2580

chore: add dev adr for guidelines on writting test utilities + remove `test_tools` and `full` features from `mithril-common`

---

Cargo.lock
mithril-common/Cargo.toml
mithril-stm/CHANGELOG.md
mithril-stm/Cargo.toml
mithril-stm/src/aggregate_signature/aggregate_key.rs
mithril-stm/src/aggregate_signature/basic_verifier.rs
mithril-stm/src/aggregate_signature/clerk.rs
mithril-stm/src/bls_multi_signature/verification_key.rs
mithril-stm/src/lib.rs
mithril-stm/src/merkle_tree/commitment.rs
mithril-stm/src/merkle_tree/tree.rs
mithril-stm/src/participant/initializer.rs
mithril-stm/src/participant/signer.rs
mithril-stm/src/single_signature/signature.rs

This PR includes the **bump of the STM library to a new minor `0.5.0`**.
- Branch
- PR
Relates to #2625

chore: bump STM minor to `0.5.0`

---

Cargo.lock
mithril-stm/Cargo.toml
mithril-stm/README.md
mithril-stm/src/lib.rs

This PR includes a **fix to the doctests of the STM library which was using deprecated functions**.
- Branch
- PR

fix: doctests using deprecated functions in STM

---

Cargo.lock
mithril-stm/Cargo.toml
mithril-stm/src/bls_multi_signature/mod.rs
mithril-stm/src/bls_multi_signature/verification_key.rs
mithril-stm/src/key_registration.rs

Fixing a typo in verify_proof_of_possession in mithril-stm/src/bls_multi_signature/verfication_key.rs.

Fixing typo in bls PoP.

---

Cargo.lock
internal/mithril-dmq/Cargo.toml
internal/mithril-dmq/src/test/double/mod.rs
internal/mithril-dmq/src/test/double/timestamp.rs
internal/mithril-dmq/src/test/fake_message.rs
internal/mithril-dmq/tests/publisher_client_server.rs

This PR includes a **fix for the DMQ integration tests flakiness which was due to non deterministic timestamp provider when signing DMQ messages with KES keys**.
- Branch
- PR
Closes #2728

fix: flakiness in DMQ integration tests in CI
