input-output-hk/mithril

CONTRIBUTING.md, README.md, docs/docusaurus.config.js
This PR adds the link to the discord channel `#moria`
Relates to #92
=> Add discord channel

docs/yarn.lock, mithril-explorer/Makefile, mithril-explorer/components/CertificateModal/index.js, mithril-explorer/components/PendingCertificate/index.js, mithril-explorer/components/SnapshotsList/index.js, mithril-explorer/package.json, mithril-explorer/pages/_app.js, mithril-explorer/styles/globals.css, mithril-explorer/yarn.lock
Also upgrade docs & explorer dependencies & rework Pending Certificate & Snapshots layout.
=> Plausible tracking for explorer

docs/root/manual/getting-started/run-signer-node.md
Added "DATA_STORE_DIRECTORY=/opt/mithril/mithril-signer/store" in environment file
=> DATA_STORE_DIRECTORY

mithril-aggregator/src/dependency.rs, mithril-aggregator/src/entities.rs, mithril-aggregator/src/lib.rs, mithril-aggregator/src/multi_signer.rs, mithril-aggregator/src/runtime/runner.rs, mithril-aggregator/src/runtime/state_machine.rs, mithril-aggregator/src/snapshot_stores/local_snapshot_store.rs, mithril-aggregator/src/snapshot_uploaders/dumb_snapshot_uploader.rs, mithril-aggregator/src/snapshotter.rs, mithril-aggregator/src/store/certificate_store.rs, mithril-aggregator/src/store/pending_certificate_store.rs, mithril-aggregator/src/store/protocol_parameters_store.rs, mithril-aggregator/src/store/single_signature_store.rs, mithril-aggregator/src/store/verification_key_store.rs, mithril-client/src/lib.rs, mithril-common/src/store/error.rs, mithril-common/src/store/stake_store.rs
Add missing code documentation in the aggregator library.
=> add missing aggregator code documentation

mithril-signer/src/runtime/signer_services.rs
This PR makes the Signer to auto create the `stores` directory if not already existing.
=> Fix auto create 'stores' directory in Signer

mithril-aggregator/src/bin/mithril-aggregator-migrate.rs
---
name: Pull Request Standard
about: You want to include modifications to the code base
title: 'fix verification key aggregator migration'
labels: 'Pull Request'
assignees: ''
---
Hot bugfix for aggregator SQLite migration.
=> fix verification_key migration

mithril-signer/src/bin/mithril-signer-migrate.rs
---
name: Pull Request Standard
about: You want to include modifications to the code base
title: 'fix signer migration splash message'
labels: 'Pull Request'
---
This patch fixes the Signer migration tool welcome message.
- Branch
- PR
=> fix migration spash message

Cargo.lock, mithril-core/Cargo.toml
This PR includes updates Cargo dependencies by running `cargo update`
=> Update cargo dependencies

docs/root/manual/developer-docs/nodes/mithril-client.md, docs/root/manual/developer-docs/nodes/mithril-signer.md, mithril-aggregator/README.md, mithril-client/README.md, mithril-signer/README.md
This PR includes some typos fix
=> Fix typos in doc

docs/root/manual/getting-started/run-signer-node.md
This PR includes some improvements on the [Run a Mithril Signer node (SPO)](https://mithril.network/doc/manual/getting-started/run-signer-node) as reported by a SPO on discord channel.
=> Update 'run signer guide' doc

docs/blog/2022-10-28-updated-environments.md, docs/root/manual/developer-docs/references.md
* A dev blog post explaining the evolution of the testing environments for SPOs
* The updated list of `Mithril Networks`
Relates to #500 or Closes #542
=> New environments documentation

.github/workflows/ci.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, docs/root/manual/developer-docs/references.md, mithril-explorer/pages/index.js, mithril-infra/main.cloud-storage.tf
This PR includes the deployment of the new `testing-preview`, `pre-release-preview` and `release-preprod` networks in the CI/CD:
| Mithril Network | Workflow | 
| ------- | ------- | 
| `testing-preview` | CI | 
| `pre-release-preview` | Pre-Release | 
| `release-preprod` | Release | 
- Branch
- PR
Closes #542
=> Activate new Mithril networks

.github/workflows/pre-release.yml, .github/workflows/release.yml
This PR includes a fix of the names of the Docker images used in Pre-Release and Release to enable incremental deployment.
- Branch
- PR
Relates to #500
=> Fix docker images names Pre-Release/Release

docs/root/manual/getting-started/bootstrap-cardano-node.md
These items are required to successfully run `make test`
- Branch
- PR
=> More refined list of pre-reqs

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-client/Cargo.toml, mithril-common/Cargo.toml, mithril-signer/Cargo.toml
This PR includes update of the node versions:
* mithril-aggregator to `0.1.1`
* mithril-client to `0.1.1`
* mithril-common to `0.1.1`
* mithril-signer to `0.1.1`
- Branch
- PR
=> Update Mithril node versions

.github/workflows/ci.yml
This PR includes a update to the full security parameters for the `testing-preview` network.
These parameters have already been tested thoroughly on a [`dev-preview`](https://mithril.network/explorer?aggregator=https%3A%2F%2Faggregator.dev-preview.api.mithril.network%2Faggregator) environment :
* `k`: **2422**
* `m`: **20973**
* `f`: **0.2**
- Branch
- PR
=> Update 'testing-preview' protocol parameters

mithril-stm/README.md, mithril-stm/src/lib.rs, mithril-stm/src/multi_sig.rs, mithril-stm/tests/integration.rs
This PR includes the updates in the `README.md` file of **mithril-stm**.
- Branch
- PR
Closes #615
=> STM Readme update

.github/workflows/ci.yml, .github/workflows/docs.yml
This PR fix the condition used to trigger the push of doc, the docker images, the creation of the unstable release & the deployment to the testing environment.
- Branch
- PR
Fix regression introduced by #613
=> Fix ci & doc workflow push/release condition

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-client/Cargo.toml, mithril-common/Cargo.toml, mithril-signer/Cargo.toml
This PR includes updates of the crates version in preparation of the distribution `2248`
- Branch
- PR
=> Update crates version 2248

.github/workflows/ci.yml, mithril-infra/assets/tools/pool/create-keys.sh
This PR includes a fix in CI configration for `testing-preview` that prevents the network from working as expected
- Branch
- PR
Relates to #563
=> Fix typos in CI

.github/workflows/pre-release.yml
This PR adds a verified signer to the `pre-release-preview` network
- Branch
- PR
Relates to #621
=> Add a verified signer to 'pre-release-preview'

.github/workflows/release.yml
This PR adds a verified signer to the `release-preprod` network
- Branch
- PR
Relates to #621
=> Add a verified signer to 'release-preprod'

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-client/Cargo.toml, mithril-common/Cargo.toml, mithril-signer/Cargo.toml
This PR includes updates of the crates version in preparation of the distribution `2250`
- Branch
- PR
=> Update crates version 2250

mithril-aggregator/src/command_args.rs, mithril-aggregator/src/dependency.rs, mithril-aggregator/src/multi_signer.rs, mithril-aggregator/src/runtime/runner.rs, mithril-aggregator/tests/test_extensions/runtime_tester.rs, mithril-common/src/entities/epoch.rs, mithril-common/src/lib.rs, mithril-signer/src/runtime/runner.rs, mithril-signer/src/runtime/state_machine.rs, mithril-signer/tests/test_extensions/certificate_handler.rs
This PR includes enhance epoch offsetting computations by only use a Result when the resulting epoch can be negative.
- Branch
- PR
Relates to #662
=> Simplify epoch offset computations

Cargo.lock, docs/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-signer.md, docs/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md, mithril-aggregator/Cargo.toml, mithril-client/Cargo.toml, mithril-signer/Cargo.toml
This PR includes updates of the crates version, as well as the documentation, in preparation of the distribution `2302`. 
- Branch
- PR
=> Update crates version 2302

docs/adr/001-use-adr.md, docs/adr/002-use-structured-logging.md, docs/adr/003-release/index.md, docs/adr/004-mithril-network-update-strategy.md, docs/docusaurus.config.js, docs/package-lock.json, docs/package.json, docs/yarn.lock
This PR adds the ADR regarding how to upgrade nodes without breaking the certificate chain.
Closes #671
=> Mithril Network Update ADR

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/http_server/routes/epoch_routes.rs, mithril-aggregator/src/lib.rs, mithril-aggregator/src/message_adapters/mod.rs, mithril-aggregator/src/message_adapters/to_epoch_settings_message.rs, mithril-common/Cargo.toml, mithril-common/src/messages/epoch_settings.rs, mithril-common/src/messages/mod.rs, mithril-signer/Cargo.toml, mithril-signer/src/certificate_handler.rs, mithril-signer/src/lib.rs, mithril-signer/src/message_adapters/from_epoch_settings.rs, mithril-signer/src/message_adapters/mod.rs, openapi.yaml
=> [695] add epoch settings message & adapter

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/main.rs, mithril-signer/Cargo.toml, mithril-signer/src/main.rs
This PR includes a fix to display better error messages on the CLI.
- Branch
- PR
Some more work may be needed to handle error in a more elegant way in the Signer.
None
=> display better errors

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/http_server/routes/middlewares.rs, mithril-aggregator/src/http_server/routes/signer_routes.rs, mithril-aggregator/src/signer_registerer.rs, mithril-aggregator/utils/monitoring/README.md, mithril-aggregator/utils/monitoring/stake_signer_version.sql, mithril-common/src/entities/signer.rs
This PR includes a tool to monitor the distribution of the stake distribution against the signers node versions.
- Branch
- PR
=> #743 monitor stake distribution Vs Signer version

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/runtime/error.rs, mithril-aggregator/src/runtime/runner.rs, mithril-aggregator/src/runtime/state_machine.rs, mithril-common/src/era/era_reader.rs, mithril-common/src/era/supported_era.rs, mithril-signer/Cargo.toml, mithril-signer/src/runtime/runner.rs, mithril-signer/src/runtime/state_machine.rs
make signer warn when coming era is unsupported
- Branch
- PR
None
None
=> make signer warn when coming era is unsupported

.github/workflows/test-docker.yml
This PR includes a fix to the test Docker image workflow which was not working properly.
- Branch
- PR
Relates to #777
=> Fix test Docker image workflow

docs/blog/2023-03-02-era-switch-feature/index.md, docs/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-aggregator.md, docs/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-signer.md, docs/versioned_docs/version-maintained/manual/getting-started/run-mithril-devnet.md, docs/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md, docs/versioned_docs/version-maintained/networks-matrix.md
This PR includes an update to the Era Switch documentation:
- update of the dev blog post
- update the current version of the documentation with new signer configuration
- Branch
- PR
Relates to #752
=> Update Era Switch documentation

docs/blog/2023-03-02-era-switch-feature/index.md
This PR includes an update to the [Era Switch Feature](https://mithril.network/doc/dev-blog/2023/03/02/era-switch-feature) dev blog post following activation on the `release-preprod` network
- Branch
- PR
Relates to #752
=> Update dev blog post Era Switch

.github/workflows/test-client.yml
This PR includes an update to the `Mithril Client multi-platform test` GitHub action workflow so that it can also test the Docker image implementation of the Client.
- Branch
- PR
Relates to #794
=> Update `Mithril Client multi-platform test` workflow

docs/root/manual/developer-docs/nodes/mithril-aggregator.md
This PR includes add missing documentation for the `genesis` command of the aggregator (it was deleted by mistake)
- Branch
- PR
Relates to #803
=> Add aggregator 'genesis' command doc

Cargo.lock, mithril-common/Cargo.toml, mithril-common/src/crypto_helper/types.rs, mithril-signer/Cargo.toml, mithril-signer/src/runtime/state_machine.rs, mithril-signer/src/single_signer.rs
This PR enhances the handling of `ProtocolInitializer` setup errors to handle them as `Critical` and to provide explicit error message.
- Branch
- PR
Closes #820
=> Enhance Key Registration errors

Cargo.lock, demo/protocol-demo/Cargo.toml, mithril-aggregator/Cargo.toml, mithril-client/Cargo.toml, mithril-common/Cargo.toml, mithril-signer/Cargo.toml, mithril-stm/Cargo.toml, mithril-test-lab/mithril-end-to-end/Cargo.toml
This PR includes an update to Rust dependencies in order to fix some security issues with `OpenSSL` 
- Branch
- PR
=> Update Rust dependencies

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/migration.rs, mithril-aggregator/src/database/provider/epoch_setting.rs, mithril-aggregator/src/database/provider/mod.rs, mithril-aggregator/src/dependency_injection/builder.rs
=> Create/Migrate `epoch settings` store

docs/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-aggregator.md, docs/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-client.md, docs/versioned_docs/version-maintained/manual/getting-started/bootstrap-cardano-node.md
This PR updates the `next` documentation to `current`
- Branch
- PR
=> Update current documentation

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/migration.rs, mithril-aggregator/src/database/provider/epoch_setting.rs, mithril-aggregator/src/database/provider/mod.rs, mithril-aggregator/src/database/provider/open_message.rs, mithril-aggregator/src/dependency_injection/builder.rs, mithril-aggregator/src/dependency_injection/error.rs, mithril-common/Cargo.toml, mithril-common/src/entities/signed_entity_type.rs, mithril-common/src/sqlite/projection.rs, mithril-common/src/sqlite/source_alias.rs
This PR includes a migration to create the `open_message` table plus the associated providers and repository.
- Branch
- PR
None
Closes #827
=> #827 open message provider & repository

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/migration.rs, mithril-aggregator/src/database/provider/mod.rs, mithril-aggregator/src/database/provider/signer.rs, mithril-aggregator/src/database/provider/signer_registration.rs, mithril-aggregator/src/dependency.rs, mithril-aggregator/src/dependency_injection/builder.rs, mithril-aggregator/src/runtime/runner.rs, mithril-aggregator/src/signer_registerer.rs
=> Create/Migrate `signer` store

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/migration.rs, mithril-aggregator/src/database/provider/mod.rs, mithril-aggregator/src/database/provider/single_signature.rs, mithril-aggregator/src/dependency_injection/builder.rs
=> Create/Migrate `single_signature` store

mithril-aggregator/src/artifact_builder/artifact_builder_service.rs, mithril-aggregator/src/artifact_builder/dummy_artifact.rs, mithril-aggregator/src/artifact_builder/interface.rs, mithril-client/src/artifact_restorer/dummy_artifact.rs, mithril-client/src/artifact_restorer/interface.rs, mithril-client/src/artifact_restorer/mod.rs, mithril-common/src/signable_builder/interface.rs
This PR includes the definition of the trait and test double for:
- `Artifact Restorer` in `mithril-client`
- Branch
- PR
Closes #868
=> Implement Artifact Restorer

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/dependency_injection/builder.rs, mithril-aggregator/src/http_server/routes/epoch_routes.rs, mithril-aggregator/src/signable_builder/mithril_stake_distribution.rs, mithril-aggregator/src/signable_builder/mod.rs, mithril-aggregator/src/signable_builder/signable_builder_service.rs
This PR includes the implementation of:
- Mithril Stake Distribution Signable builder in aggregator
- Branch
- PR
Relates to #851
=> Mithril Stake Distribution Signable builder in aggregator

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/artifact_builder/mithril_stake_distribution.rs, mithril-aggregator/src/dependency_injection/builder.rs, mithril-aggregator/src/lib.rs, mithril-aggregator/src/signable_builder/mithril_stake_distribution.rs, mithril-aggregator/src/signable_builder/mod.rs, mithril-aggregator/src/signable_builder/signable_builder_service.rs, mithril-common/Cargo.toml, mithril-common/src/signable_builder/mithril_stake_distribution.rs, mithril-common/src/signable_builder/mod.rs, mithril-signer/Cargo.toml, mithril-signer/src/runtime/runner.rs, mithril-signer/src/runtime/signer_services.rs, mithril-signer/src/signable_builder/signable_builder_service.rs, mithril-signer/tests/test_extensions/state_machine_tester.rs
This PR includes the implementation of:
- Mithril Stake Distribution Signable builder in signer
- Branch
- PR
Closes #851
=> Mithril Stake Distribution Signable builder

mithril-explorer/components/Artifacts/MithrilStakeDistributionsList/index.js, mithril-explorer/components/Artifacts/SnapshotsList/index.js, mithril-explorer/components/PendingCertificate/index.js, mithril-explorer/components/RawJsonButton.js, mithril-explorer/components/SignedEntityType.js, mithril-explorer/next.config.js, mithril-explorer/package.json, mithril-explorer/pages/index.js
This PR move the snapshots list of the explorer in a tab and add another tab that contains the list of Mithril Stake Distributions artifacts.
It also update the Certificate Pending cart to show its Signed Entity Type.  
- Branch
- PR
Closes #927
=> Add mithril stake distribution to explorer

.github/workflows/test-docker.yml, Cargo.lock, docs/root/manual/getting-started/run-signer-node.md, docs/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md, mithril-aggregator/Dockerfile, mithril-aggregator/Dockerfile.ci, mithril-infra/variables.tf, mithril-signer/Dockerfile, mithril-signer/Dockerfile.ci, mithril-test-lab/mithril-devnet/README.md, mithril-test-lab/mithril-devnet/devnet-mkfiles.sh, mithril-test-lab/mithril-end-to-end/Cargo.toml, mithril-test-lab/mithril-end-to-end/src/end_to_end_spec.rs, mithril-test-lab/mithril-end-to-end/src/main.rs
This PR upgrades the Cardano node to version `8.0.0` in test networks and `devnet`
- Branch
- PR
Closes #920
=> Upgrade Cardano node to `8.0.0`

.github/workflows/test-client.yml, docs/docusaurus.config.js
This PR includes a fix in the `Mithril Client multi-platform test` workflow in order to use the latest client command interface
- Branch
- PR
Closes #956
=> Fix `Mithril Client multi-platform test` workflow

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/command_args.rs, mithril-signer/Cargo.toml, mithril-signer/src/main.rs
This PR includes a new log at startup of the aggregator and signer. This log displays node version for each node.
- Branch
- PR
None
Closes #944
=> Add log with node version at startup in aggregator/signer

flake.nix
=> Fix darwin nix build

flake.lock
=> nix: bump nixpkgs to get newer rustc

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/provider/certificate.rs, mithril-aggregator/src/database/provider/epoch_setting.rs, mithril-aggregator/src/database/provider/open_message.rs, mithril-aggregator/src/database/provider/signed_entity.rs, mithril-aggregator/src/database/provider/signer.rs, mithril-aggregator/src/database/provider/signer_registration.rs, mithril-aggregator/src/database/provider/single_signature.rs, mithril-aggregator/src/database/provider/stake_pool.rs, mithril-aggregator/src/database/provider/test_helper.rs, mithril-aggregator/src/event_store/event.rs, mithril-common/Cargo.toml, mithril-common/src/database/db_version.rs, mithril-common/src/database/version_checker.rs, mithril-common/src/sqlite/cursor.rs, mithril-common/src/sqlite/mod.rs, mithril-common/src/sqlite/provider.rs, mithril-common/src/store/adapter/sqlite_adapter.rs, mithril-signer/Cargo.toml
This PR upgrades the version of the [`sqlite` crate](https://crates.io/crates/sqlite) to it's current last version (`0.31.0`).
Upgrading from `0.28.0` was not trivial since the crate api changed.
The last version also add a `bundled` features, this allow our binaries to not depends on the system sqlite version anymore. 
- Branch
- PR
Relates to #837
=> Sqlite upgrade and bundling

flake.nix
=> nix: increase cargo verbosity to avoid hitting max-silent-time

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/certifier_service.rs, mithril-aggregator/src/runtime/runner.rs, mithril-aggregator/src/runtime/state_machine.rs, mithril-aggregator/tests/genesis_to_signing.rs, mithril-common/Cargo.toml, mithril-common/src/certificate_chain/certificate_verifier.rs, mithril-common/src/entities/epoch.rs
This PR will make the certificate chain verifier to fail when the current Epoch is different than the first certificate's.
- Branch
- PR
=> check epoch when validating certificate chain

docs/blog/2023-06-28-signer-deployment-models/index.md, docs/root/manual/getting-started/run-signer-node.md, docs/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md
This PR includes an update of the **Signer Deployment Models** documentation:
- Fix the `ufw` firewall command
- Add an `iptable` firewall command
- Update dev blog post
- Branch
- PR
Closes #1040 and #1041
=> Update Signer Deployment Models Firewall documentation

.gitignore, flake.lock, flake.nix
This should speed up builds.
Also added nix build of stm and common so that tests can be run.
=> nix: improve caching strategy to share deps among artifacts.

docs/root/manual/getting-started/bootstrap-cardano-node.md
Suggested grammar & style edits
=> Tech writing review

docs/blog/2023-07-21-mainnet-beta-launch/index.md
This PR includes an update to the `Mainnet Beta Launch` dev blog post following the genesis of the certificate chain for the `release-mainnet`
- Branch
- PR
Relates to #918
=> Update Mainnet Beta Launch dev blog post

docs/root/mithril/intro.md
This PR includes minor changes to adhere to IOG style guide.
- Branch
- PR
=> ECS-3111 Apply style guide, minor changes.

docs/root/mithril/mithril-network/aggregator.md, docs/root/mithril/mithril-network/signer.md
This PR will include several reviews.
=> TW review of: aggregator.md & signer.md

docs/root/mithril/mithril-network/architecture.md
This PR includes a review of Architecture.md to apply the IOG style guide.
- Branch
- PR
=> ECS-3112 Review architecture.md, apply style guide.

docs/website/root/manual/getting-started/run-signer-node.md, docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md
This PR includes a fix on Run a Mithril signer as an SPO guide which update the example provided in "Verify your signer is section" part.
- Branch
- PR
Run a Mithril signer as an SPO guide was updated for both versions (current & next).
Closes #1152
=> Fix run-signer-node doc

.github/workflows/actions/prepare-distribution/action.yml
This PR fix the network compatibility table generation: single quotes should have been used instead of double quotes.
- Branch
- PR
Relates to #1151,  #1177
=> Fix network compatibility table generation

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/dependency_injection/builder.rs, mithril-common/Cargo.toml, mithril-common/src/beacon_provider.rs, mithril-common/src/lib.rs, mithril-signer/Cargo.toml, mithril-signer/src/runtime/runner.rs
This PR includes an update of `beacon_provider` error handling with `anyhow` crate.
- Branch
- PR
=> Implement anyhow context for beacon_provider

docs/website/versioned_docs/version-maintained/glossary.md, docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-client.md, docs/website/versioned_docs/version-maintained/manual/getting-started/bootstrap-cardano-node.md, docs/website/versioned_docs/version-maintained/manual/getting-started/run-mithril-devnet.md
This PR includes the update of the previous `next` version to the now `current` version of the documentation website following re-writings and improvements that do not modify its functional scope.
- Branch
- PR
=> Update current documentation for distribution `2335.0`

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/provider/certificate.rs, mithril-client/Cargo.toml, mithril-client/src/aggregator_client/certificate_client.rs, mithril-client/src/services/mock.rs, mithril-common/Cargo.toml, mithril-common/src/certificate_chain/certificate_genesis.rs, mithril-common/src/certificate_chain/certificate_retriever.rs, mithril-common/src/certificate_chain/certificate_verifier.rs, mithril-common/src/certificate_chain/mod.rs
This PR includes an update of `certificate_chain` module in order to implement `anyhow` context.
- Branch
- PR
=> Implement anyhow context for certificate chain

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/migration.rs
This PR includes a database migration to add Cardano Node version to snapshots.
- Branch
- PR
None
*
Relates to #948
=> add database migration for snapshots

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/dependency_injection/builder.rs, mithril-common/Cargo.toml, mithril-common/src/database/version_checker.rs
This PR includes an update of `database` module in `mithril-common` in order to implement `anyhow` context.
- Branch
- PR
=> Implement anyhow context in mithril-common database

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/dependency_injection/builder.rs, mithril-aggregator/src/runtime/state_machine.rs, mithril-common/Cargo.toml, mithril-common/src/era/era_reader.rs, mithril-common/src/era/supported_era.rs
=> Use anyhow in Era framework

mithril-common/Cargo.toml, mithril-common/src/messages/message_parts/signer.rs
This PR provides error refactoring for Mithril common message parts.
- Branch
- PR
None
=> refacto message parts

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/provider/epoch_setting.rs, mithril-aggregator/src/database/provider/open_message.rs, mithril-aggregator/src/database/provider/signed_entity.rs, mithril-aggregator/src/database/provider/signer_registration.rs, mithril-aggregator/src/services/certifier.rs, mithril-aggregator/src/services/signed_entity.rs, mithril-aggregator/src/tools/certificates_hash_migrator.rs, mithril-aggregator/src/tools/genesis.rs, mithril-aggregator/tests/test_extensions/runtime_tester.rs
This PR includes an update of `database` module in `mithril-aggregator` in order to implement `anyhow` context.
- Branch
- PR
=> Implement anyhow context in mithril-aggregator database

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/runtime/runner.rs, mithril-common/Cargo.toml, mithril-common/src/signable_builder/signable_builder_service.rs, mithril-signer/Cargo.toml, mithril-signer/src/runtime/runner.rs
This PR includes an update of the `signable_builder` to implement anyhow context.
- Branch
- PR
=> Implement anyhow context for signable_builder

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/multi_signer.rs, mithril-common/Cargo.toml, mithril-common/src/protocol/multi_signer.rs, mithril-common/src/protocol/signer_builder.rs, mithril-common/src/protocol/single_signer.rs, mithril-signer/Cargo.toml, mithril-signer/src/single_signer.rs
This PR includes an update of mithril-common `protocol` with `anyhow` context.
- Branch
- PR
=> Implement anyhow context for common/protocol

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/artifact_builder/cardano_immutable_files_full.rs, mithril-aggregator/src/artifact_builder/mithril_stake_distribution.rs
This PR includes an update of mithril-aggregator `artifact_builder` with `anyhow` context.
- Branch
- PR
=> Implement anyhow context for artifact builder

Cargo.lock, mithril-common/Cargo.toml, mithril-common/src/crypto_helper/cardano/codec.rs, mithril-common/src/crypto_helper/cardano/key_certification.rs, mithril-common/src/crypto_helper/era.rs, mithril-common/src/crypto_helper/genesis.rs, mithril-common/src/era/adapters/cardano_chain.rs, mithril-signer/Cargo.toml, mithril-signer/src/runtime/runner.rs, mithril-signer/src/single_signer.rs
This PR includes the update of the crypto helpers to use `anyhow`.
- Branch
- PR
=> Use anyhow in `common/crypto_helper`

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/configuration.rs, mithril-aggregator/src/dependency_injection/builder.rs
This PR includes an update of mithril-aggregator `configuration` with `anyhow` context.
- Branch
- PR
=> Implement anyhow context for aggregator configuration

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/commands/genesis_command.rs, mithril-aggregator/src/commands/serve_command.rs, mithril-aggregator/src/commands/tools_command.rs
This PR includes an update of mithril-aggregator `dependency_injection` with `anyhow` context.
- Branch
- PR
=> Implement anyhow context: dependency_injection

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/runtime/runner.rs, mithril-aggregator/src/runtime/state_machine.rs
This PR includes an update of mithril-aggregator `runtime` with `anyhow` context.
- Branch
- PR
=> Implement anyhow context in aggregator runtime

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/artifact_builder/cardano_immutable_files_full.rs, mithril-aggregator/src/snapshotter.rs
This PR includes an update of mithril-aggregator `snapshotter` with `anyhow` context.
- Branch
- PR
=> Implement anyhow context in aggregator/snapshotter

Cargo.lock, mithril-signer/Cargo.toml, mithril-signer/src/aggregator_client.rs, mithril-signer/tests/test_extensions/certificate_handler.rs
This PR includes a refactoring of Mithril Signer's Aggregator client errors.
- Branch
- PR
None
=> refactored aggregator client errors

Cargo.lock, mithril-common/Cargo.toml, mithril-common/src/era/adapters/builder.rs, mithril-signer/Cargo.toml, mithril-signer/src/configuration.rs, mithril-signer/src/runtime/signer_services.rs
This PR features a rework of Configuration errors.
- Branch
- PR
None
=> refactored client configuration errors

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/provider/stake_pool.rs, mithril-common/Cargo.toml, mithril-common/src/sqlite/entity.rs
This PR includes a simple fix of SQLite errors.
- Branch
- PR
None
=> refactor common sqlite errors

Cargo.lock, mithril-client/Cargo.toml, mithril-client/src/aggregator_client/certificate_client.rs, mithril-client/src/aggregator_client/http_client.rs, mithril-client/src/aggregator_client/mithril_stake_distribution_client.rs, mithril-client/src/aggregator_client/snapshot_client.rs, mithril-client/src/services/snapshot.rs
This PR includes an update of mithril-client `aggregator-client` with `anyhow` context.
- Branch
- PR
=> Add anyhow context mithril-client/aggregator-client

Cargo.lock, mithril-client/Cargo.toml, mithril-client/src/commands/mithril_stake_distribution/download.rs, mithril-client/src/commands/mithril_stake_distribution/list.rs, mithril-client/src/commands/snapshot/download.rs, mithril-client/src/commands/snapshot/list.rs, mithril-client/src/commands/snapshot/show.rs
This PR includes an update of mithril-client `commands` with `anyhow` context.
- Branch
- PR
=> Add anyhow context in mithril-client/commands

Cargo.lock, mithril-client/Cargo.toml, mithril-client/src/dependencies/builder.rs
This PR includes an update of mithril-client `dependencies` with `anyhow` context.
- Branch
- PR
=> Add anyhow context in mithril-client/dependencies

Cargo.lock, mithril-test-lab/mithril-end-to-end/Cargo.toml, mithril-test-lab/mithril-end-to-end/src/bin/load-aggregator/main.rs, mithril-test-lab/mithril-end-to-end/src/stress_test/fake_client.rs, mithril-test-lab/mithril-end-to-end/src/stress_test/wait.rs
This PR includes some optimizations and fine tuning of the aggregator stress test tool to make it scale with more clients.
More details are available here: https://github.com/input-output-hk/mithril/issues/1207#issuecomment-1731669634
- Branch
- PR
Closes #1207
=> Fix aggregator stress test bottleneck with client traffic

Cargo.lock, mithril-client/Cargo.toml, mithril-client/src/services/mithril_stake_distribution.rs, mithril-client/src/services/snapshot.rs
This PR includes an update of mithril-client `services` with `anyhow` context.
- Branch
- PR
=> Add anyhow context for mithril-client/services

docs/website/root/manual/getting-started/run-signer-node.md
This PR includes some enhancements to the [SPO guide to setup a Mithril signer](https://mithril.network/doc/manual/getting-started/run-signer-node):
- Add a process when updating the KES keys and OpCert
- Update the recommended listening port of the Mithril relay 
- Add configuration instructions for relay in front of multiple block producers
- Branch
- PR
Closes #1267
=> Enhance signer setup guide for SPO

Cargo.lock, mithril-test-lab/mithril-end-to-end/Cargo.toml, mithril-test-lab/mithril-end-to-end/README.md, mithril-test-lab/mithril-end-to-end/benchmark-aggregator.sh, mithril-test-lab/mithril-end-to-end/src/stress_test/entities.rs
This PR includes a tool to benchmark the aggregator on a bi-dimensional range of signers and clients.
- Branch
- PR
Closes #1220
=> Benchmark aggregator performances

Cargo.lock, demo/protocol-demo/Cargo.toml, docs/website/package.json, docs/website/yarn.lock, mithril-aggregator/Cargo.toml, mithril-client/Cargo.toml, mithril-common/Cargo.toml, mithril-explorer/package.json, mithril-explorer/yarn.lock, mithril-signer/Cargo.toml, mithril-stm/Cargo.toml, mithril-test-lab/mithril-end-to-end/Cargo.toml
This PR includes updates of Rust dependencies for the nodes and libraries.
- Branch
- PR
=> Upgrade dependencies

docs/runbook/README.md, docs/runbook/upgrade-vm/README.md
This PR includes a new runbook with a detailed process to **upgrade or downgrade the VM of a Mithril network** infrastructure
- Branch
- PR
Closes #1218
=> Infrastructure VM upgrade runbook

docs/website/blog/2023-10-10-relay-security-advisory.md
This PR includes a dev blog post for the [Mithril relay security advisory](https://github.com/input-output-hk/mithril/security/advisories/GHSA-9m3h-72xj-x2gq)
- Branch
- PR
=> Mithril relay security advisory dev blog post

docs/website/blog/2023-10-10-relay-security-advisory.md
This PR includes a fix of a typo in the dev blog post: [Mithril Relay Security Advisory](https://mithril.network/doc/dev-blog/2023/10/10/relay-security-advisory)
- Branch
- PR
=> Fix typo in relay security advisory dev blog post

mithril-aggregator/src/database/provider/certificate.rs
This reverts the SQL soft limit implementation (commit b8b0b83d1409dc998e6ba7da2c577b7e96a3bbd3) since theses changes did not prove to increase performances (in reality they even worsen them).
- Branch
- PR
None
Relates to #1314 and #1310
=> Revert "add soft limit in certificate query"

.github/workflows/actions/deploy-terraform-infrastructure/action.yml, .github/workflows/ci.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
This PR includes the usage of a custom Cardano node version (set in the environment deployed) during deployments steps of the CI/CD.
- Branch
- PR
Closes #1355
=> Use Cardano node custom version CI/CD

.github/workflows/test-deploy.yml, .github/workflows/test-docker.yml
This PR includes the GitHub actions workflows necessary to:
- Manually create test distributions (upgrade of existing workflow)
- Manually deploy test distributions to test Mithril network
- Branch
- PR
Relates to #1356
=> Manual deployment of test Mithril network

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/message_adapters/to_mithril_stake_distribution_list_message.rs, mithril-aggregator/src/message_adapters/to_mithril_stake_distribution_message.rs, mithril-aggregator/src/message_adapters/to_snapshot_list_message.rs, mithril-aggregator/src/message_adapters/to_snapshot_message.rs, mithril-aggregator/src/services/message.rs, mithril-common/Cargo.toml, mithril-common/src/entities/signed_entity.rs
This PR includes an update of `SignedEntity`. It adds a dummy for each `SignedEntity` type that simplifies code in tests.
- Branch
- PR
=> Create dummies for SignedEntities

docs/website/blog/2024-01-03-signer-service-recommended-configuration-updated.md, docs/website/root/manual/getting-started/run-signer-node.md, docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md
This PR includes an update of Mithril signer node service recommended configuration.
- Branch
- PR
Closes #1404
=> Fix signer service recommended configuration

Cargo.lock, mithril-client-wasm/Cargo.toml, mithril-client-wasm/src/client_wasm.rs, mithril-client-wasm/src/lib.rs
This PR includes a first implementation of tests in `mithril-client-wasm`.
This is a first step with data fetched from `testing-preview` network.
The second step will be to use the fake aggregator binary to expand the testing coverage.
- Branch
- PR
Relates to #1407
=> Implement tests for WASM library

.github/workflows/ci.yml
This PR includes an upgrade of the `testing-preview` VM with `4` more CPUS.
- Branch
- PR
=> Upgrade `testing-preview` VM in infra

Cargo.lock, docs/website/root/manual/developer-docs/nodes/mithril-aggregator.md, mithril-aggregator/Cargo.toml, mithril-aggregator/src/artifact_builder/cardano_transactions.rs, mithril-aggregator/src/artifact_builder/mod.rs, mithril-aggregator/src/database/migration.rs, mithril-aggregator/src/database/provider/open_message.rs, mithril-aggregator/src/dependency_injection/builder.rs, mithril-aggregator/src/services/certifier.rs, mithril-aggregator/src/services/signed_entity.rs, mithril-aggregator/src/tools/certificates_hash_migrator.rs, mithril-aggregator/tests/test_extensions/aggregator_observer.rs, mithril-common/Cargo.toml, mithril-common/src/entities/cardano_transactions_commitment.rs, mithril-common/src/entities/mod.rs, mithril-common/src/entities/protocol_message.rs, mithril-common/src/entities/signed_entity.rs, mithril-common/src/entities/signed_entity_type.rs, mithril-common/src/signable_builder/cardano_transactions.rs, mithril-common/src/signable_builder/mod.rs, mithril-common/src/signable_builder/signable_builder_service.rs, mithril-signer/Cargo.toml, mithril-signer/src/runtime/runner.rs, mithril-signer/src/runtime/signer_services.rs, mithril-signer/tests/test_extensions/state_machine_tester.rs, mithril-test-lab/mithril-end-to-end/Cargo.toml, mithril-test-lab/mithril-end-to-end/src/main.rs
This PR includes the setup of a new `CardanoTransactions` signed entity type in the Mithril networks.
- Branch
- PR
Closes #1434
=> Support `CardanoTransactions` signed entity type

docs/website/root/manual/developer-docs/nodes/mithril-client-library-wasm.md, mithril-client-wasm/npm/README.md
This PR includes a fix in the `README.md` file which is published on `npm` and in the dev documentation.
The modification concerns the basic javascript example, which can be directly copied and pasted to run most of the functions exposed by the Mithril client WASM library.
- Branch
- PR
=> Fix `mithril-client wasm` basic JS code example

Cargo.lock, mithril-client-wasm/Cargo.toml
This PR includes an update of `mithril-client-wasm` crate version to authorize publishing on `npm`.
- Branch
- PR
=> Increment `mithril-client-wasm` version for `npm` publish

docs/website/blog/2024-02-08-testing-sanchonet-network-available.md, docs/website/root/networks-matrix.md, docs/website/versioned_docs/version-maintained/networks-matrix.md
This PR adds a dev blog post that announces the availability of the new `testing-sanchonet` Mithril network.
- Branch
- PR
Relates to #1173
=> Add dev blog post announcing `testing-sanchonet` network

Cargo.lock, mithril-client-wasm/Cargo.toml
This PR includes an update of the minor version of the crate `mithril-client-wasm`.
This follows the implementation of the new signing type Cardano transaction.
- Branch
- PR
=> Upgrade `mithril-client-wasm` minor version to 0.2.0

docs/runbook/test-client-multiplatform/README.md
This PR includes a fix in the new runbook after the merge of the PR #1534.
- Branch
- PR
Relates to #1530
=> Fix runbook broken link

Cargo.lock, internal/mithril-persistence/Cargo.toml, internal/mithril-persistence/src/store/adapter/dumb_adapter.rs, mithril-aggregator/Cargo.toml, mithril-aggregator/src/http_server/routes/artifact_routes/cardano_transaction.rs, mithril-aggregator/src/http_server/routes/artifact_routes/mithril_stake_distribution.rs, mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs, mithril-aggregator/src/http_server/routes/certificate_routes.rs, mithril-aggregator/src/http_server/routes/epoch_routes.rs, mithril-aggregator/src/http_server/routes/proof_routes.rs, mithril-aggregator/src/http_server/routes/root_routes.rs, mithril-aggregator/src/http_server/routes/signatures_routes.rs, mithril-aggregator/src/http_server/routes/signer_routes.rs, mithril-aggregator/src/http_server/routes/statistics_routes.rs, mithril-common/Cargo.toml, mithril-common/src/test_utils/apispec.rs, mithril-test-lab/mithril-aggregator-fake/Cargo.toml, mithril-test-lab/mithril-aggregator-fake/src/application.rs, mithril-test-lab/mithril-aggregator-fake/src/error.rs, mithril-test-lab/mithril-aggregator-fake/src/handlers.rs
This PR includes enhancements of the aggregator HTTP server tests.
A verification of the status code of the response has been added.
Some additional tests and refactoring has been done in `api_spec` to improve tests reliability.
- Branch
- PR
Closes #1524
=> Improve aggregator HTTP server tests

CONTRIBUTING.md, README.md, docs/website/blog/2023-03-02-era-switch-feature/index.md, docs/website/blog/2023-06-28-signer-deployment-models/index.md, docs/website/docusaurus.config.js, docs/website/package.json, docs/website/root/manual/getting-started/SPO-on-boarding-guide.md, docs/website/versioned_docs/version-maintained/manual/getting-started/SPO-on-boarding-guide.md
This PR includes the renaming of the `moria1 Discord channel to `ask-mithril`
- Branch
- PR
=> Rename `moria` Discord channel to `ask-mithril`

docs/website/blog/2024-03-26-mithril-signer-prometheus-endpoint/index.md, docs/website/root/manual/getting-started/run-signer-node.md, docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md
This PR includes an update to the documentation website to reference the **Grafana Dashboard template** for the signer: https://grafana.com/grafana/dashboards/20776-mithril-signer/
- Branch
- PR
Relates to #1559
=> Make Grafana Dashboard template for signer available in docs

README.md
This PR includes a rewriting of the **mainnet availability** section of the README file:
- Ready for deployment in the SPO infrastructure
- Not completely ready for usage of artifacts
- Legal disclaimer
- Branch
- PR
=> Update README `mainnet availability` section

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-client-cli/Cargo.toml, mithril-client-wasm/Cargo.toml, mithril-client/Cargo.toml, mithril-common/Cargo.toml
This PR includes an increment for minor versions of crates after a breaking change.
- Branch
- PR
=> Upgrade crates minor versions

CHANGELOG.md, Cargo.lock, internal/mithril-build-script/Cargo.toml, internal/mithril-build-script/src/open_api.rs, internal/mithril-doc/Cargo.toml, internal/mithril-doc/src/lib.rs, mithril-aggregator/Cargo.toml, mithril-aggregator/src/database/provider/cardano_transaction/get_cardano_transaction.rs, mithril-aggregator/src/database/repository/cardano_transaction_repository.rs, mithril-aggregator/src/dependency_injection/builder.rs, mithril-aggregator/src/message_adapters/to_cardano_transaction_list_message.rs, mithril-aggregator/src/message_adapters/to_cardano_transaction_message.rs, mithril-aggregator/src/message_adapters/to_mithril_stake_distribution_list_message.rs, mithril-aggregator/src/message_adapters/to_mithril_stake_distribution_message.rs, mithril-aggregator/src/message_adapters/to_snapshot_list_message.rs, mithril-aggregator/src/message_adapters/to_snapshot_message.rs, mithril-aggregator/src/services/prover.rs, mithril-aggregator/src/signer_registerer.rs, mithril-aggregator/src/tools/certificates_hash_migrator.rs, mithril-common/Cargo.toml, mithril-common/build.rs, mithril-common/src/certificate_chain/certificate_verifier.rs, mithril-common/src/chain_observer/cli_observer.rs, mithril-common/src/crypto_helper/merkle_tree.rs, mithril-common/src/digesters/immutable_file.rs, mithril-stm/Cargo.toml, mithril-stm/src/merkle_tree.rs
This PR includes the computation of the **Cardano Transactions** proof with the pre-computed **Block Range Merkle Roots** retrieved from the store.
- Branch
- PR
Closes #1635
=> Prove `Cardano Transactions` with `Block Range Merkle Roots`

docs/runbook/README.md, docs/runbook/maintain-cardano-min-versions-file/README.md, docs/runbook/maintain-networks-configuration-file/README.md, networks.json
This PR includes the `mithril-networks` configuration for the Cardano networks (mainnet, preprod, preview, and sanchonet) in the `networks.json` file.
- Branch
- PR
Closes #1638
=> Adding Mithril networks configuration to `networks.json`

Cargo.lock, demo/protocol-demo/Cargo.toml, examples/client-cardano-transaction/Cargo.toml, examples/client-mithril-stake-distribution/Cargo.toml, examples/client-snapshot/Cargo.toml, internal/mithril-build-script/Cargo.toml, internal/mithril-doc-derive/Cargo.toml, internal/mithril-doc/Cargo.toml, internal/mithril-persistence/Cargo.toml, mithril-aggregator/Cargo.toml, mithril-client-cli/Cargo.toml, mithril-client-wasm/Cargo.toml, mithril-client/Cargo.toml, mithril-common/Cargo.toml, mithril-relay/Cargo.toml, mithril-signer/Cargo.toml, mithril-stm/Cargo.toml, mithril-test-lab/mithril-aggregator-fake/Cargo.toml, mithril-test-lab/mithril-end-to-end/Cargo.toml
This PR includes ugrades of the Rust dependencies of the repository (including patched versions for [rustls](https://github.com/advisories/GHSA-6g7w-8wpp-frhj) and [h2](https://github.com/advisories/GHSA-q6cp-qfwq-4gcv))
- Branch
- PR
=> Upgrade project dependencies

docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-aggregator.md, docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-client.md, docs/website/versioned_docs/version-maintained/manual/developer-docs/nodes/mithril-signer.md, docs/website/versioned_docs/version-maintained/manual/getting-started/bootstrap-cardano-node.md, docs/website/versioned_docs/version-maintained/manual/getting-started/run-mithril-devnet.md, docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md
This PR includes the rotation of the current documentation.
- Branch
- PR
=> Rotate current documentation

docs/website/docusaurus.config.js
This PR includes a new link in the footer of the website to the [**Mithril Protocol Insights**](https://lookerstudio.google.com/s/oi6CR5eZrnQ) dashboard.
- Branch
- PR
=> Add `Mithril Protocol Insights` dashboard link on website

Cargo.lock, internal/mithril-persistence/Cargo.toml, internal/mithril-persistence/src/database/repository/cardano_transaction_repository.rs, mithril-aggregator/Cargo.toml, mithril-aggregator/src/dependency_injection/builder.rs, mithril-aggregator/src/services/prover.rs
This PR includes a fix to make the **Cardano transaction prover** able to certify more than `5` transactions.
| Total Requests | Concurrency | Transactions/Request | Pool (x50): Request/s | Pool (x50) + Optimization 'get_all_transactions_for_block_ranges': Request/s |
| -------------- | ----------- | -------------------- | --------------------- | ---------------------------------------------------------------------------- |
| 1000           | 100         | 1                    | **233.7**                 | **256.29**                                                                       |
| 1000           | 100         | 2                    | **170.75**                | **181.31**                                                                       |
| 1000           | 100         | 3 …
=> Make Cardano transaction prover able to certify more than 5 transactions

docs/website/package-lock.json
This PR includes an upgrade of the documentation website dependencies (including patched version `3.0.3` for [braces](https://github.com/advisories/GHSA-grv7-fg5c-xmjg))
- Branch
- PR
=> Upgrade doc dependencies

CHANGELOG.md
This PR includes the final change log for `2428.0` release.
- Branch
- PR
Relates to #1810
=> Update CHANGELOG for `2428.0` distribution release

Cargo.lock, docs/website/root/manual/getting-started/run-signer-node.md, docs/website/versioned_docs/version-maintained/manual/getting-started/run-signer-node.md, mithril-signer/Cargo.toml, mithril-signer/src/metrics/mod.rs
Add metrics table in the "Activate Prometheus endpoint" section of the "Run a Mithril signer as an SPO" guide.
- Branch
- PR
Closes #1834
=> Add metrics table in the "Activate Prometheus endpoint" section

CHANGELOG.md
This PR includes the rotation of the `CHANGELOG` file preparing the release of the `2430` distribution.
- Branch
- PR
Relates to #1830
=> Update CHANGELOG for `2430` distribution release

CHANGELOG.md
This PR includes the final change log for `2430.0` release.
- Branch
- PR
Relates to #1830
=> Update CHANGELOG for `2430.0` distribution release

.github/workflows/ci.yml
Escape slashes in `sed` command
- Branch
- PR
Closes #1867
=> Escape slashes in sed command

docs/website/root/manual/developer-docs/nodes/mithril-client-library-wasm.md
This PR includes documentation improvements for the Mithril client WASM library, including the addition of a missing JavaScript example for `CardanoStakeDistribution`.
- Branch
- PR
Relates to #1844
=> Add missing Cardano stake distribution example in developer documentation

CHANGELOG.md, Cargo.lock, mithril-common/Cargo.toml, mithril-common/src/era/supported_era.rs
This PR includes the creation of a new `Pythagoras` Mithril era.
- Branch
- PR
Relates to #1946
=> Feat: create new 'Pythagoras' Mithril era

CHANGELOG.md, Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/tools/genesis.rs, mithril-common/Cargo.toml, mithril-common/src/certificate_chain/certificate_genesis.rs, mithril-common/src/crypto_helper/tests_setup.rs, mithril-common/src/entities/protocol_message.rs, mithril-common/src/test_utils/mithril_fixture.rs
This PR includes an upgrade of the **Genesis certificate** to embed the protocol parameters of the next epoch.
- Branch
- PR
=> Feat: sign protocol parameters in Genesis certificate

.github/workflows/aggregator-stress-test.yml, .github/workflows/ci.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/test-client.yml, .github/workflows/test-docker-distribution.yml
This PR upgrade all github actions in our workflows to their latest version available if any.
- Branch
- PR
Closes #2018
=> Upgrade actions to latest

CHANGELOG.md
This PR includes the final change log for `2450.0` release.
- Branch
- PR
Relates to #2124
=> Docs: update CHANGELOG for `2450.0` distribution release

CHANGELOG.md
This PR includes the final change log for `2450.0` distribution release.
- Branch
- PR
Relates to #2124
=> Docs: final CHANGELOG for '2450.0' distribution

docs/website/blog/2024-10-15-cardano-stake-distribution-certification.md
- Updates on the [Certification of Cardano stake distribution](https://mithril.network/doc/dev-blog/2024/10/15/cardano-stake-distribution-certification) dev blog post.
- Branch
- PR
Relates to #2218
=> Docs: dev blog post for activation of the Cardano stake distribution certification 

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/http_server/routes/artifact_routes/cardano_database.rs, mithril-aggregator/src/http_server/routes/artifact_routes/snapshot.rs, mithril-aggregator/src/http_server/routes/statistics_routes.rs, mithril-aggregator/src/metrics/service.rs, mithril-aggregator/src/services/signed_entity.rs, mithril-aggregator/tests/certificate_chain.rs, mithril-aggregator/tests/create_certificate.rs, mithril-aggregator/tests/open_message_expiration.rs, mithril-aggregator/tests/open_message_newer_exists.rs, mithril-aggregator/tests/test_extensions/aggregator_observer.rs, mithril-aggregator/tests/test_extensions/metrics_tester.rs
This PR includes the **integration testing of the Cardano database certification in the aggregator.**
- Branch
- PR
Relates to #2211
=> Feat(tests): integration testing for `CardanoDatabase` certification

docs/website/blog/2024-12-17-era-switch-pythagoras.md
This PR includes  **an update to the [Era switch to Pythagoras](https://mithril.network/doc/dev-blog/2024/12/17/era-switch-pythagoras) dev blog post**.
- Branch
- PR
Relates to #2034
=> docs: update era switch dev blog post

CHANGELOG.md
This PR includes the **final change log for `2506.0` distribution release**.
- Branch
- PR
=> Docs: update CHANGELOG for `2506.0` distribution release

CHANGELOG.md
This PR includes the **final change log for `2506.0` distribution release**.
- Branch
- PR
=> Docs: final CHANGELOG for '2506.0' distribution

Cargo.lock, mithril-client/Cargo.toml, mithril-client/tests/cardano_db_snapshot_list_get_download_verify.rs, mithril-client/tests/extensions/fake.rs, mithril-client/tests/extensions/routes/cardano_db_snapshot.rs, mithril-client/tests/extensions/routes/mod.rs, mithril-client/tests/extensions/routes/statistics.rs, mithril-common/Cargo.toml, mithril-common/src/digesters/dummy_cardano_db.rs
This PR includes a new integration test for the `CardanoDatabaseSnapshot` in `mithril-client`.
- Branch
- PR
Closes #2328
=> Test: add integration test for incremental Cardano database in `mithril-client`

docs/website/root/glossary.md, docs/website/root/manual/develop/nodes/mithril-client-library-wasm.md, docs/website/root/manual/develop/nodes/mithril-client-library.md, docs/website/root/manual/develop/nodes/mithril-client.md, mithril-client-wasm/README.md
This PR includes an update of the website documentation for the Incremental Cardano DB part of the clients.
- Branch
- PR
Closes #2329
=> Docs: update clients documentation for incremental Cardano DB

docs/devbook/bump-versions/README.md, docs/devbook/bump-versions/bump_versions.sh, docs/devbook/upgrade-repository-dependencies/README.md
This PR includes enhancements to the version bump script, including upgrading the version file for infrastructure, devnet and benchmark and fixing the inclusion of updated Cargo.toml examples in the commit.
- Branch
- PR
=> Chore: enhance versions bump script

Cargo.lock, mithril-client/Cargo.toml, mithril-client/src/lib.rs
This PR includes the documentation of optional Cargo features available in `mithril-client` which provides a list of features, their purpose, and their default status.
- Branch
- PR
=> Docs: add features documentation for `mithril-client` library

CHANGELOG.md
This PR includes the **final change log for `2513.0` distribution release**.
- Branch
- PR
Relates to #2332
=> docs: final CHANGELOG for `2513.0` distribution

docs/website/root/manual/develop/nodes/mithril-aggregator.md, docs/website/root/manual/develop/nodes/mithril-client.md, docs/website/root/manual/develop/nodes/mithril-signer.md, docs/website/versioned_docs/version-maintained/manual/develop/nodes/mithril-aggregator.md, docs/website/versioned_docs/version-maintained/manual/develop/nodes/mithril-client.md, docs/website/versioned_docs/version-maintained/manual/develop/nodes/mithril-signer.md, mithril-relay/README.md
This PR includes missing information in the aggregator node documentation and improves the clarity of existing content.
- Branch
- PR
=> Docs: fix website documentation

docs/website/blog/2025-04-14-cardano-node-database-v2-certification.md
This PR includes a new blog post announcing the certification of Cardano node database v2.
- Branch
- PR
Relates to #2409
=> Docs: blog post for the Cardano node database v2 certification

docs/website/blog/2025-04-14-cardano-node-database-v2-certification.md
This PR includes the update of the **Cardano node database v2** dev blog post following activation on the `release-preprod` network
- Branch
- PR
Relates to #2409
=> Doc: update Cardano node database v2 dev blog post

docs/website/package-lock.json, examples/client-wasm-web/package-lock.json, mithril-client-wasm/ci-test/package-lock.json, mithril-client-wasm/ci-test/package.json, mithril-explorer/package-lock.json
This PR includes **fix for security vulnerabilities** in the:
- documentation website
- explorer website
- WASM client ci-test website
- WASM client web example wesite
- Branch
- PR
=> Fix: websites vulnerabilities

.github/workflows/test-client.yml
This PR adds `ancillary_verification_key` and `include_ancillary` inputs to the `Mithril Client multi-platform test` GitHub workflow.
These inputs enable the Mithril client CLI to handle ancillary file download and verification during snapshot restoration.
- Branch
- PR
Closes #2458
=> test(ci): add ancillary verification key and include ancillary option in `Mithril Client multi-platform test` workflow

CHANGELOG.md
This PR includes the **final change log for `2517.0` distribution release**.
- Branch
- PR
Relates to #2410
=> Docs: final CHANGELOG for `2517.0` distribution

docs/website/blog/2025-04-14-cardano-node-database-v2-certification.md
This PR includes an **update on the [Certification of Cardano node database v2](https://mithril.network/doc/dev-blog/2025/04/14/cardano-node-database-v2-certification) dev blog post**.
- Branch
- PR
Relates to #2409
=> Docs: update dev blog post for `Cardano DB v2` activation

Cargo.lock, mithril-client-cli/Cargo.toml, mithril-client-cli/src/utils/cardano_db.rs
better text formatting for print about fast boostrap
- Branch
- PR
=> fix(client-cli): improve message format about fast boostrap

Cargo.lock, Cargo.toml, demo/protocol-demo/Cargo.toml, docs/website/package-lock.json, docs/website/package.json, examples/client-wasm-nodejs/package-lock.json, examples/client-wasm-nodejs/package.json, examples/client-wasm-web/package-lock.json, examples/client-wasm-web/package.json, flake.lock, internal/mithril-metric/Cargo.toml, mithril-aggregator/Cargo.toml, mithril-client-wasm/ci-test/package-lock.json, mithril-client-wasm/ci-test/package.json, mithril-client-wasm/package.json, mithril-client/Cargo.toml, mithril-common/Cargo.toml, mithril-explorer/package-lock.json, mithril-explorer/package.json, mithril-signer/Cargo.toml, mithril-stm/Cargo.toml, mithril-stm/src/bls_multi_signature/mod.rs, mithril-stm/src/merkle_tree/tree.rs, mithril-stm/src/stm.rs, mithril-test-lab/mithril-aggregator-fake/Cargo.toml
This PR **upgrades the repository dependencies to their latest version in preparation of the distribution `2523`** by running the [upgrade script from the devbook](https://github.com/input-output-hk/mithril/tree/main/docs/devbook/upgrade-repository-dependencies).
- Branch
- PR
Relates to #2488
=> Chore: update dependencies for distribution `2523`

mithril-stm/CHANGELOG.md, mithril-stm/Cargo.toml, mithril-stm/src/lib.rs, mithril-stm/src/participant/signer.rs, mithril-stm/src/single_signature/mod.rs, mithril-stm/src/single_signature/signature.rs, mithril-stm/src/single_signature/signature_registered_party.rs, mithril-stm/src/stm.rs
This PR includes `single_signature` module covering the functionalities of `StmSig` and `StmSigRegParty`.
- Branch
- PR
Relates to #2369
=> Organize STM - Module Single Signature

Cargo.lock, mithril-aggregator/Cargo.toml, mithril-aggregator/src/http_server/routes/router.rs
Allow new header client type to authorized headers (to avoid falling request due to CORS)
- Branch
- PR
Relates to #2494
=> Allow new header client type

CHANGELOG.md
This PR includes the **final change log for `2524.0` distribution release**.
- Branch
- PR
Relates to #2488
=> docs: final CHANGELOG for '2524.0' distribution

docs/website/blog/2025-06-17-client-cli-cardano-database-backends.md, docs/website/root/mithril/advanced/mithril-certification/cardano-node-database-v2.md, docs/website/root/mithril/advanced/mithril-certification/cardano-node-database.md, docs/website/versioned_docs/version-maintained/mithril/advanced/mithril-certification/cardano-node-database-v2.md, docs/website/versioned_docs/version-maintained/mithril/advanced/mithril-certification/cardano-node-database.md
This PR includes a dev blog post that details the **plan to switch from Cardano database full certification (v1) to incremental certification (v2)**.
- Branch
- PR
Relates to #2488
=> Docs: dev blog post for Cardano database backend switch

docs/website/blog/2025-06-16-client-cli-utxo-snapshot-converter-command.md
This PR includes an **update to the dev blog post about UTxO-HD ledger state snapshot converter**.
- Branch
- PR
=> docs: update post for UTxO-HD ledger state snapshot converter

docs/website/src/pages/index.tsx
Adding a client side wrapper to ensure framer motion scroll-based animations work on it (header/whymithril)
=> filip(fix): add client side wrapper to homepage

.github/workflows/nightly-dispatcher.yml
This PR includes the update the **schedule of the [Nightly Dispatcher](https://github.com/input-output-hk/mithril/actions/workflows/nightly-dispatcher.yml) workflow from 2 am to 1 am**.
- Branch
- PR
=> chore: update nightly workflow schedule
